# coding: utf-8

"""
    Cartotool

    Cartotool api project for using the cartotool.com application with Python scripts  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Contact: info@cartotool.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cartotool.configuration import Configuration


class Project(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'code': 'str',
        'name': 'str',
        'description': 'str',
        'watermark': 'str',
        'workspace': 'Workspace',
        'image': 'ProjectImage',
        'creation_date': 'datetime',
        'longitude': 'float',
        'latitude': 'float',
        'zoom': 'int',
        'base_url': 'str',
        'public': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'code': 'code',
        'name': 'name',
        'description': 'description',
        'watermark': 'watermark',
        'workspace': 'workspace',
        'image': 'image',
        'creation_date': 'creationDate',
        'longitude': 'longitude',
        'latitude': 'latitude',
        'zoom': 'zoom',
        'base_url': 'baseUrl',
        'public': 'public'
    }

    def __init__(self, id=None, code=None, name=None, description=None, watermark=None, workspace=None, image=None, creation_date=None, longitude=None, latitude=None, zoom=None, base_url=None, public=None, local_vars_configuration=None):  # noqa: E501
        """Project - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._code = None
        self._name = None
        self._description = None
        self._watermark = None
        self._workspace = None
        self._image = None
        self._creation_date = None
        self._longitude = None
        self._latitude = None
        self._zoom = None
        self._base_url = None
        self._public = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if code is not None:
            self.code = code
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if watermark is not None:
            self.watermark = watermark
        if workspace is not None:
            self.workspace = workspace
        if image is not None:
            self.image = image
        if creation_date is not None:
            self.creation_date = creation_date
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude
        if zoom is not None:
            self.zoom = zoom
        if base_url is not None:
            self.base_url = base_url
        if public is not None:
            self.public = public

    @property
    def id(self):
        """Gets the id of this Project.  # noqa: E501


        :return: The id of this Project.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Project.


        :param id: The id of this Project.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def code(self):
        """Gets the code of this Project.  # noqa: E501


        :return: The code of this Project.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Project.


        :param code: The code of this Project.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501


        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.


        :param name: The name of this Project.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Project.  # noqa: E501


        :return: The description of this Project.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Project.


        :param description: The description of this Project.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def watermark(self):
        """Gets the watermark of this Project.  # noqa: E501


        :return: The watermark of this Project.  # noqa: E501
        :rtype: str
        """
        return self._watermark

    @watermark.setter
    def watermark(self, watermark):
        """Sets the watermark of this Project.


        :param watermark: The watermark of this Project.  # noqa: E501
        :type: str
        """

        self._watermark = watermark

    @property
    def workspace(self):
        """Gets the workspace of this Project.  # noqa: E501


        :return: The workspace of this Project.  # noqa: E501
        :rtype: Workspace
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this Project.


        :param workspace: The workspace of this Project.  # noqa: E501
        :type: Workspace
        """

        self._workspace = workspace

    @property
    def image(self):
        """Gets the image of this Project.  # noqa: E501


        :return: The image of this Project.  # noqa: E501
        :rtype: ProjectImage
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this Project.


        :param image: The image of this Project.  # noqa: E501
        :type: ProjectImage
        """

        self._image = image

    @property
    def creation_date(self):
        """Gets the creation_date of this Project.  # noqa: E501


        :return: The creation_date of this Project.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this Project.


        :param creation_date: The creation_date of this Project.  # noqa: E501
        :type: datetime
        """

        self._creation_date = creation_date

    @property
    def longitude(self):
        """Gets the longitude of this Project.  # noqa: E501


        :return: The longitude of this Project.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this Project.


        :param longitude: The longitude of this Project.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this Project.  # noqa: E501


        :return: The latitude of this Project.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this Project.


        :param latitude: The latitude of this Project.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def zoom(self):
        """Gets the zoom of this Project.  # noqa: E501


        :return: The zoom of this Project.  # noqa: E501
        :rtype: int
        """
        return self._zoom

    @zoom.setter
    def zoom(self, zoom):
        """Sets the zoom of this Project.


        :param zoom: The zoom of this Project.  # noqa: E501
        :type: int
        """

        self._zoom = zoom

    @property
    def base_url(self):
        """Gets the base_url of this Project.  # noqa: E501


        :return: The base_url of this Project.  # noqa: E501
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url):
        """Sets the base_url of this Project.


        :param base_url: The base_url of this Project.  # noqa: E501
        :type: str
        """

        self._base_url = base_url

    @property
    def public(self):
        """Gets the public of this Project.  # noqa: E501


        :return: The public of this Project.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this Project.


        :param public: The public of this Project.  # noqa: E501
        :type: bool
        """

        self._public = public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Project):
            return True

        return self.to_dict() != other.to_dict()
