# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric6/Preferences/ConfigurationPages/DebuggerPython2Page.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebuggerPython2Page(object):
    def setupUi(self, DebuggerPython2Page):
        DebuggerPython2Page.setObjectName("DebuggerPython2Page")
        DebuggerPython2Page.resize(455, 500)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DebuggerPython2Page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerLabel = QtWidgets.QLabel(DebuggerPython2Page)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line11_2 = QtWidgets.QFrame(DebuggerPython2Page)
        self.line11_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line11_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line11_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line11_2.setObjectName("line11_2")
        self.verticalLayout_3.addWidget(self.line11_2)
        self.groupBox_4 = QtWidgets.QGroupBox(DebuggerPython2Page)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.venvComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.venvComboBox.setObjectName("venvComboBox")
        self.horizontalLayout_2.addWidget(self.venvComboBox)
        self.venvDlgButton = QtWidgets.QToolButton(self.groupBox_4)
        self.venvDlgButton.setText("")
        self.venvDlgButton.setObjectName("venvDlgButton")
        self.horizontalLayout_2.addWidget(self.venvDlgButton)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(DebuggerPython2Page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.debugClientPicker = E5PathPicker(self.groupBox_2)
        self.debugClientPicker.setEnabled(False)
        self.debugClientPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.debugClientPicker.setObjectName("debugClientPicker")
        self.gridLayout.addWidget(self.debugClientPicker, 1, 0, 1, 2)
        self.standardButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.standardButton.setObjectName("standardButton")
        self.gridLayout.addWidget(self.standardButton, 0, 0, 1, 1)
        self.customButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.customButton.setObjectName("customButton")
        self.gridLayout.addWidget(self.customButton, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(DebuggerPython2Page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sourceExtensionsEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.sourceExtensionsEdit.setReadOnly(True)
        self.sourceExtensionsEdit.setObjectName("sourceExtensionsEdit")
        self.verticalLayout.addWidget(self.sourceExtensionsEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(self.groupBox_3)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.pyRedirectCheckBox = QtWidgets.QCheckBox(DebuggerPython2Page)
        self.pyRedirectCheckBox.setObjectName("pyRedirectCheckBox")
        self.verticalLayout_3.addWidget(self.pyRedirectCheckBox)
        self.pyNoEncodingCheckBox = QtWidgets.QCheckBox(DebuggerPython2Page)
        self.pyNoEncodingCheckBox.setObjectName("pyNoEncodingCheckBox")
        self.verticalLayout_3.addWidget(self.pyNoEncodingCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(435, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)

        self.retranslateUi(DebuggerPython2Page)
        self.customButton.toggled['bool'].connect(self.debugClientPicker.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DebuggerPython2Page)
        DebuggerPython2Page.setTabOrder(self.venvComboBox, self.venvDlgButton)
        DebuggerPython2Page.setTabOrder(self.venvDlgButton, self.standardButton)
        DebuggerPython2Page.setTabOrder(self.standardButton, self.customButton)
        DebuggerPython2Page.setTabOrder(self.customButton, self.debugClientPicker)
        DebuggerPython2Page.setTabOrder(self.debugClientPicker, self.sourceExtensionsEdit)
        DebuggerPython2Page.setTabOrder(self.sourceExtensionsEdit, self.refreshButton)
        DebuggerPython2Page.setTabOrder(self.refreshButton, self.pyRedirectCheckBox)
        DebuggerPython2Page.setTabOrder(self.pyRedirectCheckBox, self.pyNoEncodingCheckBox)

    def retranslateUi(self, DebuggerPython2Page):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("DebuggerPython2Page", "<b>Configure Python2 Debugger</b>"))
        self.groupBox_4.setTitle(_translate("DebuggerPython2Page", "Python2 Virtual Environment"))
        self.venvComboBox.setToolTip(_translate("DebuggerPython2Page", "Select the virtual environment to be used"))
        self.venvDlgButton.setToolTip(_translate("DebuggerPython2Page", "Press to open the virtual environment manager dialog"))
        self.groupBox_2.setTitle(_translate("DebuggerPython2Page", "Debug Client Type"))
        self.debugClientPicker.setToolTip(_translate("DebuggerPython2Page", "Enter the path of the Debug Client to be used.  Leave empty to use the default."))
        self.standardButton.setToolTip(_translate("DebuggerPython2Page", "Select the standard debug client"))
        self.standardButton.setText(_translate("DebuggerPython2Page", "Standard"))
        self.customButton.setToolTip(_translate("DebuggerPython2Page", "Select the custom selected debug client"))
        self.customButton.setText(_translate("DebuggerPython2Page", "Custom"))
        self.groupBox_3.setTitle(_translate("DebuggerPython2Page", "Source association"))
        self.label.setText(_translate("DebuggerPython2Page", "Please configure the associated file extensions on the \'Python\' page."))
        self.refreshButton.setToolTip(_translate("DebuggerPython2Page", "Press to update the display of the source associations"))
        self.refreshButton.setText(_translate("DebuggerPython2Page", "Refresh"))
        self.pyRedirectCheckBox.setToolTip(_translate("DebuggerPython2Page", "Select, to redirect stdin, stdout and stderr of the program being debugged to the eric6 IDE"))
        self.pyRedirectCheckBox.setText(_translate("DebuggerPython2Page", "Redirect stdin/stdout/stderr"))
        self.pyNoEncodingCheckBox.setToolTip(_translate("DebuggerPython2Page", "Select to not set the debug client encoding"))
        self.pyNoEncodingCheckBox.setText(_translate("DebuggerPython2Page", "Don\'t set the encoding of the debug client"))
from E5Gui.E5PathPicker import E5PathPicker
