[tool.poetry]
name = "ttmr"
version = "0.5.15"
description = ""
authors = ["Mark Gemmill <gitlab@markgemmill.com>"]

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4.3"
arrow = "^0.15.5"
colorama = "^0.4.1"
docopt-ng = "^0.7.2"
prompt-toolkit = "^3.0.3"
python-dateutil = "^2.8.1"
tabulate = "^0.8.6"
tomlkit = "^0.5.8"
sqlalchemy = "^1.3.13"
pendulum = "^2.0.5"
pytest-cov = "^2.8.1"
csvy = {version = "^0.1.0-alpha.0", allow-prereleases = true}
plyer = "^1.4.2"
dbus-python = {version = "^1.2.16", platform = "linux"}
typer = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
freezegun = "^0.3.15"
isort = "^4.3.21"
black = "^19.10b0"
xini = "^0.2.2"
flake8 = "^3.7.9"
alembic = "^1.4.0"
vulture = "^1.3"
pylint = "^2.4.4"
radon = "^4.1.0"

[tool.dover]
versioned_files = [
    "src/ttmr/cli.py",
    "pyproject.toml"
]

[tool.poetry.scripts]
ttmr = 'ttmr.cli:main'
ttmrc = 'ttmr.clic:main'


[tool.black]
verbose = true

[tool.isort]
line_length = 90
force_single_line = true
no_lines_before = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pylint]
disable = [
    "missing-docstring",
    "line-too-long",
    "bad-continuation",
    "invalid-name",
    "logging-format-interpolation",
    "consider-using-ternary"
]

[tool.flake8]
statistics = true
ignore = ["E501","W503","E241","E731", "E262"]
max-line-length = 80
max-complexity = 7
tee = true
exclude = [
    ".git",
    ".tox",
    "__pycache__",
    "docs",
    "build",
    "dist",
    "src/ttmr/orig",
    "old_cmd.py",
    "old_stuff.py",
    "ui.py",
    "domain.py",
    "scripts",
]

[tool.pytest]
addopts = "-vv --strict --cov=ttmr --cov-report=term-missing"

[tool.coverage.run]
source = "ttmr"
branch = true

[tool.coverage.paths]
source = "ttmr"

[tool.coverage.report]
show_missing = true
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

