name: hydrodata-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - numba
  - matplotlib
  - descartes
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - rasterio
  - pyproj
  - proj
  - gdal
  - networkx
  - geojson
  - simplejson
  - pytables
  - flake8
  - flake8-comprehensions
  - flake8-builtins
  - flake8-rst-docstrings
  - flake8-blind-except
  - pycodestyle
  - pytest-runner
  - pytest-cov
  - pytest-xdist
  - codecov
  - numpydoc
  - coverage
  - defusedxml
  - pip:
    - pqdm
    - arcgis2geojson
