[tool.poetry]
name = "moic"
version = "1.3.1"
description = "My Own Issue CLI (Jira, Gitlab etc...)"
authors = ["Brice Santus <brice.santus@gmail.com>"]
readme = "README.md"
homepage = "https://moic.readthedocs.io/"
documentation = "https://moic.readthedocs.io/"
repository = "https://gitlab.com/brice.santus/moic"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: POSIX :: Linux"
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.1"
jira = "^2.0?0"
dynaconf = "^2.2.3"
pyyaml = "^5.3"
keyring = "^21.1.1"
antidote = "^0.7.0"
rich = "^0.8.8"
tomd = "^0.1.3"
commonmark = "^0.9.1"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
black = "^19.10b0"
ipdb = "^0.13.2"
pre-commit = "^2.2.0"
isort = "^4.3.21"
pytest = "^5.4.1"
pytest-mock = "^2.0.0"
pytest-cov = "^2.8.1"
mock = "^4.0.2"
python-semantic-release = "^5.0.2"
pdbpp = "^0.10.2"
flake8-docstrings = "^1.5.0"
sphinx = "^3.0.4"
sphinx-rtd-theme = "^0.4.3"

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | build
    | dist
  )/
)
'''

[tool.semantic_release]
version_source = "commit"
commit_changes = "True"
version_variable = "pyproject.toml:version"
hvcs = "gitlab"
upload_to_pypi = "True"
upload_to_release = "False"
build_command = "poetry build"

[tool.poetry.scripts]
moic = 'moic.base:run'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
