- name: Install Zabbix Repo
  yum:
    name: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present
- name: insert allow zabbix agent port rule into iptables (no internal network)
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ item }} -m state --state NEW -m multiport --dport 10050 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for zabbix agent {{ item }}"
  with_items: "{{ (ansible_play_batch | map('extract', hostvars, 'hive_private_ip') | list) + [hive_safe_zabbix_subnet | ipaddr(2) | ipaddr('address')] }}"
  when: hive_internal_net_addr is not defined
  notify: require reboot
- name: insert allow zabbix agent port rule into iptables for internal network
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ hive_internal_net_addr }}/{{ hive_internal_net_cidr }} -m state --state NEW -m multiport --dport 10050 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for zabbix agent for internal network"
  when: hive_internal_net_addr is defined
  notify: require reboot
- name: yum install
  yum:
    name=zabbix-agent
    state=installed
- name: modify zabbix_agentd config
  template: >
    src=zabbix_agentd.conf.j2
    dest='/etc/zabbix/zabbix_agentd.conf'
    owner=root
    group=root
    mode=0644
- name: put docker-volume zabbix_agentd config
  template: >
    src=docker-volume.j2
    dest='/etc/zabbix/zabbix_agentd.d/docker-volume'
    owner=root
    group=root
    mode=0644
- name: put script to discover docker volumes
  copy:
    src: docker-volume-discover.py
    dest: "{{ hive_home_dir }}/docker-volume-discover.py"
    owner: "{{hive_safe_admin}}"
    group: "{{hive_admin_group | default(hive_safe_admin)}}"
- name: put sudoers file for zabbix agent
  copy:
    src: sudoers.zabbix
    dest: /etc/sudoers.d/zabbix
    owner: root
    group: root
    mode: 0440
- name: enabled and start zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes