# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtypes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtypes.proto',
  package='mas.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x64types.proto\x12\nmas.common\"0\n\rVector3dProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"0\n\rVector3fProto\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x1f\n\x12Vector3fArrayProto\x12\t\n\x01v\x18\x01 \x03(\x02\"\x1f\n\x12Vector3dArrayProto\x12\t\n\x01v\x18\x01 \x03(\x01\"%\n\rVector2dProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x1f\n\x12Vector2dArrayProto\x12\t\n\x01v\x18\x01 \x03(\x01\"<\n\rMatrix3dProto\x12\r\n\x05row_1\x18\x01 \x03(\x01\x12\r\n\x05row_2\x18\x02 \x03(\x01\x12\r\n\x05row_3\x18\x03 \x03(\x01\"n\n\x0fIsometry3dProto\x12.\n\x0btranslation\x18\x01 \x01(\x0b\x32\x19.mas.common.Vector3dProto\x12+\n\x08rotation\x18\x02 \x01(\x0b\x32\x19.mas.common.Matrix3dProto\">\n\x10QuaterniondProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"]\n\x0b\x41\x41\x42\x42\x32\x64Proto\x12&\n\x03min\x18\x01 \x01(\x0b\x32\x19.mas.common.Vector2dProto\x12&\n\x03max\x18\x02 \x01(\x0b\x32\x19.mas.common.Vector2dProto\"<\n\x0e\x43\x45NTERBOXProto\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\"\xc5\x01\n\tImageData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\x12\x10\n\x08url_only\x18\x05 \x01(\x08\x12\x0b\n\x03url\x18\x06 \x01(\t\x12+\n\x06\x66ormat\x18\x07 \x01(\x0e\x32\x1b.mas.common.ImageData.Codec\x12\x0c\n\x04\x64\x61ta\x18\x08 \x01(\x0c\"0\n\x05\x43odec\x12\x0b\n\x07NOT_SET\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03PNG\x10\x02\x12\x07\n\x03GIF\x10\x03\"\'\n\x0f\x43\x41NBusDataProto\x12\x14\n\x0craw_can_data\x18\x01 \x01(\x0c\x62\x06proto3'
)



_IMAGEDATA_CODEC = _descriptor.EnumDescriptor(
  name='Codec',
  full_name='mas.common.ImageData.Codec',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIF', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=811,
  serialized_end=859,
)
_sym_db.RegisterEnumDescriptor(_IMAGEDATA_CODEC)


_VECTOR3DPROTO = _descriptor.Descriptor(
  name='Vector3dProto',
  full_name='mas.common.Vector3dProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mas.common.Vector3dProto.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mas.common.Vector3dProto.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='mas.common.Vector3dProto.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=76,
)


_VECTOR3FPROTO = _descriptor.Descriptor(
  name='Vector3fProto',
  full_name='mas.common.Vector3fProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mas.common.Vector3fProto.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mas.common.Vector3fProto.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='mas.common.Vector3fProto.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=126,
)


_VECTOR3FARRAYPROTO = _descriptor.Descriptor(
  name='Vector3fArrayProto',
  full_name='mas.common.Vector3fArrayProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='mas.common.Vector3fArrayProto.v', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=159,
)


_VECTOR3DARRAYPROTO = _descriptor.Descriptor(
  name='Vector3dArrayProto',
  full_name='mas.common.Vector3dArrayProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='mas.common.Vector3dArrayProto.v', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=192,
)


_VECTOR2DPROTO = _descriptor.Descriptor(
  name='Vector2dProto',
  full_name='mas.common.Vector2dProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mas.common.Vector2dProto.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mas.common.Vector2dProto.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=231,
)


_VECTOR2DARRAYPROTO = _descriptor.Descriptor(
  name='Vector2dArrayProto',
  full_name='mas.common.Vector2dArrayProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='mas.common.Vector2dArrayProto.v', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=264,
)


_MATRIX3DPROTO = _descriptor.Descriptor(
  name='Matrix3dProto',
  full_name='mas.common.Matrix3dProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_1', full_name='mas.common.Matrix3dProto.row_1', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_2', full_name='mas.common.Matrix3dProto.row_2', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_3', full_name='mas.common.Matrix3dProto.row_3', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=326,
)


_ISOMETRY3DPROTO = _descriptor.Descriptor(
  name='Isometry3dProto',
  full_name='mas.common.Isometry3dProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='mas.common.Isometry3dProto.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='mas.common.Isometry3dProto.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=438,
)


_QUATERNIONDPROTO = _descriptor.Descriptor(
  name='QuaterniondProto',
  full_name='mas.common.QuaterniondProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mas.common.QuaterniondProto.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mas.common.QuaterniondProto.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='mas.common.QuaterniondProto.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='mas.common.QuaterniondProto.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=502,
)


_AABB2DPROTO = _descriptor.Descriptor(
  name='AABB2dProto',
  full_name='mas.common.AABB2dProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='mas.common.AABB2dProto.min', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='mas.common.AABB2dProto.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=597,
)


_CENTERBOXPROTO = _descriptor.Descriptor(
  name='CENTERBOXProto',
  full_name='mas.common.CENTERBOXProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mas.common.CENTERBOXProto.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mas.common.CENTERBOXProto.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='mas.common.CENTERBOXProto.w', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='mas.common.CENTERBOXProto.h', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=659,
)


_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='mas.common.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='mas.common.ImageData.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='mas.common.ImageData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='mas.common.ImageData.depth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url_only', full_name='mas.common.ImageData.url_only', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='mas.common.ImageData.url', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='mas.common.ImageData.format', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='mas.common.ImageData.data', index=6,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGEDATA_CODEC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=859,
)


_CANBUSDATAPROTO = _descriptor.Descriptor(
  name='CANBusDataProto',
  full_name='mas.common.CANBusDataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_can_data', full_name='mas.common.CANBusDataProto.raw_can_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=861,
  serialized_end=900,
)

_ISOMETRY3DPROTO.fields_by_name['translation'].message_type = _VECTOR3DPROTO
_ISOMETRY3DPROTO.fields_by_name['rotation'].message_type = _MATRIX3DPROTO
_AABB2DPROTO.fields_by_name['min'].message_type = _VECTOR2DPROTO
_AABB2DPROTO.fields_by_name['max'].message_type = _VECTOR2DPROTO
_IMAGEDATA.fields_by_name['format'].enum_type = _IMAGEDATA_CODEC
_IMAGEDATA_CODEC.containing_type = _IMAGEDATA
DESCRIPTOR.message_types_by_name['Vector3dProto'] = _VECTOR3DPROTO
DESCRIPTOR.message_types_by_name['Vector3fProto'] = _VECTOR3FPROTO
DESCRIPTOR.message_types_by_name['Vector3fArrayProto'] = _VECTOR3FARRAYPROTO
DESCRIPTOR.message_types_by_name['Vector3dArrayProto'] = _VECTOR3DARRAYPROTO
DESCRIPTOR.message_types_by_name['Vector2dProto'] = _VECTOR2DPROTO
DESCRIPTOR.message_types_by_name['Vector2dArrayProto'] = _VECTOR2DARRAYPROTO
DESCRIPTOR.message_types_by_name['Matrix3dProto'] = _MATRIX3DPROTO
DESCRIPTOR.message_types_by_name['Isometry3dProto'] = _ISOMETRY3DPROTO
DESCRIPTOR.message_types_by_name['QuaterniondProto'] = _QUATERNIONDPROTO
DESCRIPTOR.message_types_by_name['AABB2dProto'] = _AABB2DPROTO
DESCRIPTOR.message_types_by_name['CENTERBOXProto'] = _CENTERBOXPROTO
DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['CANBusDataProto'] = _CANBUSDATAPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3dProto = _reflection.GeneratedProtocolMessageType('Vector3dProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3DPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector3dProto)
  })
_sym_db.RegisterMessage(Vector3dProto)

Vector3fProto = _reflection.GeneratedProtocolMessageType('Vector3fProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3FPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector3fProto)
  })
_sym_db.RegisterMessage(Vector3fProto)

Vector3fArrayProto = _reflection.GeneratedProtocolMessageType('Vector3fArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3FARRAYPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector3fArrayProto)
  })
_sym_db.RegisterMessage(Vector3fArrayProto)

Vector3dArrayProto = _reflection.GeneratedProtocolMessageType('Vector3dArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3DARRAYPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector3dArrayProto)
  })
_sym_db.RegisterMessage(Vector3dArrayProto)

Vector2dProto = _reflection.GeneratedProtocolMessageType('Vector2dProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2DPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector2dProto)
  })
_sym_db.RegisterMessage(Vector2dProto)

Vector2dArrayProto = _reflection.GeneratedProtocolMessageType('Vector2dArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2DARRAYPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Vector2dArrayProto)
  })
_sym_db.RegisterMessage(Vector2dArrayProto)

Matrix3dProto = _reflection.GeneratedProtocolMessageType('Matrix3dProto', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX3DPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Matrix3dProto)
  })
_sym_db.RegisterMessage(Matrix3dProto)

Isometry3dProto = _reflection.GeneratedProtocolMessageType('Isometry3dProto', (_message.Message,), {
  'DESCRIPTOR' : _ISOMETRY3DPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.Isometry3dProto)
  })
_sym_db.RegisterMessage(Isometry3dProto)

QuaterniondProto = _reflection.GeneratedProtocolMessageType('QuaterniondProto', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNIONDPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.QuaterniondProto)
  })
_sym_db.RegisterMessage(QuaterniondProto)

AABB2dProto = _reflection.GeneratedProtocolMessageType('AABB2dProto', (_message.Message,), {
  'DESCRIPTOR' : _AABB2DPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.AABB2dProto)
  })
_sym_db.RegisterMessage(AABB2dProto)

CENTERBOXProto = _reflection.GeneratedProtocolMessageType('CENTERBOXProto', (_message.Message,), {
  'DESCRIPTOR' : _CENTERBOXPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.CENTERBOXProto)
  })
_sym_db.RegisterMessage(CENTERBOXProto)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

CANBusDataProto = _reflection.GeneratedProtocolMessageType('CANBusDataProto', (_message.Message,), {
  'DESCRIPTOR' : _CANBUSDATAPROTO,
  '__module__' : 'dtypes_pb2'
  # @@protoc_insertion_point(class_scope:mas.common.CANBusDataProto)
  })
_sym_db.RegisterMessage(CANBusDataProto)


# @@protoc_insertion_point(module_scope)
