name: Django Extra Checks CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e $(tox -a | grep $PYTHON_VERSION  | python -c "import sys;print(sys.stdin.read().strip().replace('\n', ' -e '))")
        env:
          PYTHON_VERSION: ${{ matrix.python }}
      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: .coverage.*

  lint:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Download coverage
        uses: actions/download-artifact@v1
        with:
          name: coverage
      - name: Prepare env
        run: |
          pip install tox
          mv coverage/* .
      - name: Run Tox
        run: tox -e flake8 -e black -e isort -e manifest -e coverage

  publish:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
