# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/slam/metrics/proto/combined_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.avs.messages import lyft_car_time_pb2 as src_dot_avs_dot_messages_dot_lyft__car__time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/slam/metrics/proto/combined_error.proto',
  package='avsoftware.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+src/slam/metrics/proto/combined_error.proto\x12\x10\x61vsoftware.proto\x1a$src/avs/messages/lyft_car_time.proto\"~\n\x18TimestampedCombinedError\x12*\n\ttimestamp\x18\x01 \x01(\x0b\x32\x17.avsoftware.LyftCarTime\x12\x17\n\x0f\x64istance_meters\x18\x02 \x01(\x01\x12\x1d\n\x15\x63ombined_error_meters\x18\x03 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[src_dot_avs_dot_messages_dot_lyft__car__time__pb2.DESCRIPTOR,])




_TIMESTAMPEDCOMBINEDERROR = _descriptor.Descriptor(
  name='TimestampedCombinedError',
  full_name='avsoftware.proto.TimestampedCombinedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='avsoftware.proto.TimestampedCombinedError.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance_meters', full_name='avsoftware.proto.TimestampedCombinedError.distance_meters', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='combined_error_meters', full_name='avsoftware.proto.TimestampedCombinedError.combined_error_meters', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=229,
)

_TIMESTAMPEDCOMBINEDERROR.fields_by_name['timestamp'].message_type = src_dot_avs_dot_messages_dot_lyft__car__time__pb2._LYFTCARTIME
DESCRIPTOR.message_types_by_name['TimestampedCombinedError'] = _TIMESTAMPEDCOMBINEDERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampedCombinedError = _reflection.GeneratedProtocolMessageType('TimestampedCombinedError', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMPEDCOMBINEDERROR,
  __module__ = 'src.slam.metrics.proto.combined_error_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.proto.TimestampedCombinedError)
  ))
_sym_db.RegisterMessage(TimestampedCombinedError)


# @@protoc_insertion_point(module_scope)
