- hosts: primary
  name: Autoconverted job legacy-grenade-dsvm-cinder-mn-sub-volschbak from old job
    gate-grenade-dsvm-cinder-mn-sub-volschbak-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_CONFIGDRIVE=0
          export DEVSTACK_GATE_GRENADE=pullup
          export DEVSTACK_GATE_USE_PYTHON3=True
          export PROJECTS="openstack/grenade $PROJECTS"
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          export DEVSTACK_GATE_TOPOLOGY="multinode"
          export SERVICES=volschbak
          if [ "$SERVICES" == "bak" ] ; then
            export DEVSTACK_GATE_CINDER_MN_GRENADE_SUB_BAK=1
          elif [ "$SERVICES" == "volschbak" ] ; then
            export DEVSTACK_GATE_CINDER_MN_GRENADE_SUB_VOLSCHBAK=1
          else
            export DEVSTACK_GATE_CINDER_MN_GRENADE=1
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
