[tool.poetry]
name = "s3bucketencryptor"
version = "0.1.0"
description = "It set Server Side Encryption as AES256 for Objects in a S3 Bucket."
authors = ["oi73ooh <cindian@amazingbutuseless.net>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.13.21"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
s3enc = 's3bucketencryptor:encrypt_bucket'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
