# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/common/kinematics/proto/motionstate3d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.common.serialization import eigen_serialization_pb2 as src_dot_common_dot_serialization_dot_eigen__serialization__pb2
from FireSpark.protos.src.common.kinematics.proto import vehicle_motion_state_pb2 as src_dot_common_dot_kinematics_dot_proto_dot_vehicle__motion__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/common/kinematics/proto/motionstate3d.proto',
  package='avsoftware.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/src/common/kinematics/proto/motionstate3d.proto\x12\x11\x61vsoftware.common\x1a\x32src/common/serialization/eigen_serialization.proto\x1a\x36src/common/kinematics/proto/vehicle_motion_state.proto\"\xa7\x06\n\x12MotionState3DProto\x12K\n\x14timestamped_isometry\x18\x01 \x01(\x0b\x32-.avsoftware.common.TimeStampedIsometry3dProto\x12=\n\x13linear_velocity_mps\x18\x02 \x01(\x0b\x32 .avsoftware.common.Vector3dProto\x12@\n\x16\x61ngular_velocity_radps\x18\x03 \x01(\x0b\x32 .avsoftware.common.Vector3dProto\x12\x42\n\x18linear_acceleration_mps2\x18\x04 \x01(\x0b\x32 .avsoftware.common.Vector3dProto\x12\x45\n\x1b\x61ngular_acceleration_radps2\x18\x05 \x01(\x0b\x32 .avsoftware.common.Vector3dProto\x12\x43\n\x14vehicle_motion_state\x18\x06 \x01(\x0e\x32%.avsoftware.common.VehicleMotionState\x12T\n\x13motion_state_source\x18\x07 \x01(\x0e\x32\x37.avsoftware.common.MotionState3DProto.MotionStateSource\"\x9c\x02\n\x11MotionStateSource\x12\x1f\n\x1bMOTION_STATE_SOURCE_NOT_SET\x10\x00\x12\"\n\x1eMOTION_STATE_SOURCE_LOCAL_SLAM\x10\x01\x12\x32\n.MOTION_STATE_SOURCE_GRAVITY_ALIGNED_LOCAL_SLAM\x10\x02\x12#\n\x1fMOTION_STATE_SOURCE_GLOBAL_SLAM\x10\x03\x12%\n!MOTION_STATE_SOURCE_SENSOR_FUSION\x10\x04\x12\x1b\n\x17MOTION_STATE_SOURCE_INS\x10\x05\x12%\n!MOTION_STATE_SOURCE_DRIVE_BY_WIRE\x10\x06\x62\x06proto3')
  ,
  dependencies=[src_dot_common_dot_serialization_dot_eigen__serialization__pb2.DESCRIPTOR,src_dot_common_dot_kinematics_dot_proto_dot_vehicle__motion__state__pb2.DESCRIPTOR,])



_MOTIONSTATE3DPROTO_MOTIONSTATESOURCE = _descriptor.EnumDescriptor(
  name='MotionStateSource',
  full_name='avsoftware.common.MotionState3DProto.MotionStateSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_NOT_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_LOCAL_SLAM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_GRAVITY_ALIGNED_LOCAL_SLAM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_GLOBAL_SLAM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_SENSOR_FUSION', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_INS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION_STATE_SOURCE_DRIVE_BY_WIRE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=702,
  serialized_end=986,
)
_sym_db.RegisterEnumDescriptor(_MOTIONSTATE3DPROTO_MOTIONSTATESOURCE)


_MOTIONSTATE3DPROTO = _descriptor.Descriptor(
  name='MotionState3DProto',
  full_name='avsoftware.common.MotionState3DProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamped_isometry', full_name='avsoftware.common.MotionState3DProto.timestamped_isometry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_velocity_mps', full_name='avsoftware.common.MotionState3DProto.linear_velocity_mps', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity_radps', full_name='avsoftware.common.MotionState3DProto.angular_velocity_radps', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_acceleration_mps2', full_name='avsoftware.common.MotionState3DProto.linear_acceleration_mps2', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_acceleration_radps2', full_name='avsoftware.common.MotionState3DProto.angular_acceleration_radps2', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_motion_state', full_name='avsoftware.common.MotionState3DProto.vehicle_motion_state', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motion_state_source', full_name='avsoftware.common.MotionState3DProto.motion_state_source', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOTIONSTATE3DPROTO_MOTIONSTATESOURCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=986,
)

_MOTIONSTATE3DPROTO.fields_by_name['timestamped_isometry'].message_type = src_dot_common_dot_serialization_dot_eigen__serialization__pb2._TIMESTAMPEDISOMETRY3DPROTO
_MOTIONSTATE3DPROTO.fields_by_name['linear_velocity_mps'].message_type = src_dot_common_dot_serialization_dot_eigen__serialization__pb2._VECTOR3DPROTO
_MOTIONSTATE3DPROTO.fields_by_name['angular_velocity_radps'].message_type = src_dot_common_dot_serialization_dot_eigen__serialization__pb2._VECTOR3DPROTO
_MOTIONSTATE3DPROTO.fields_by_name['linear_acceleration_mps2'].message_type = src_dot_common_dot_serialization_dot_eigen__serialization__pb2._VECTOR3DPROTO
_MOTIONSTATE3DPROTO.fields_by_name['angular_acceleration_radps2'].message_type = src_dot_common_dot_serialization_dot_eigen__serialization__pb2._VECTOR3DPROTO
_MOTIONSTATE3DPROTO.fields_by_name['vehicle_motion_state'].enum_type = src_dot_common_dot_kinematics_dot_proto_dot_vehicle__motion__state__pb2._VEHICLEMOTIONSTATE
_MOTIONSTATE3DPROTO.fields_by_name['motion_state_source'].enum_type = _MOTIONSTATE3DPROTO_MOTIONSTATESOURCE
_MOTIONSTATE3DPROTO_MOTIONSTATESOURCE.containing_type = _MOTIONSTATE3DPROTO
DESCRIPTOR.message_types_by_name['MotionState3DProto'] = _MOTIONSTATE3DPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotionState3DProto = _reflection.GeneratedProtocolMessageType('MotionState3DProto', (_message.Message,), dict(
  DESCRIPTOR = _MOTIONSTATE3DPROTO,
  __module__ = 'src.common.kinematics.proto.motionstate3d_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.common.MotionState3DProto)
  ))
_sym_db.RegisterMessage(MotionState3DProto)


# @@protoc_insertion_point(module_scope)
