language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - pip install . -r requirements.txt
script:
  # command to lint code
  - flake8 --config .flake8
  # command to run tests with coverage
  - make coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)

# operating system tested on
os: linux
