
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "98e5d212174ca3513ce75ffd0a76bcefb23f2b01",
 "version": "1.1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
