# Base Configuration file for artellapipe-tools-artellamanager in Solstice

# Defines icon of the tool
icon: artellamanager

# URL to tool documentation web page
help_url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/artellamanager/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False