# pyproject.toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4"
]

[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
line-length = 79

