
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-06T11:31:10+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ca3733873ff8a241b590e3e03049e23d3c268a6",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
