BBBB BBBBBB BBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBBB BBBB
        XXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBBBBBBBBBB BBBBBBBBXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBBBBBBBBBB BBBBBBBBXXX
        
        
        BBBBB BBB
        BBBBBBBB BBB
    BBBBBBBB BBBB
    BBBBB BBBBB

    BBBBBBBB BBBBB
XXXXXXX
XXXXX XXXXXXXXXXXXXX

BBBBB BBBB

BBBBBBBB BBBB

BBBBB BBBBBBB

BBBBBBBB BBBBBBB
XXXXXXX
XXXXXXX