[tool.poetry]
name = "versionkit"
version = "0.1.0"
description = ""
authors = ["Edward George <edwardgeorge@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
ipython = "^7.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
