depends = ('ITKPyBase', 'ITKThresholding', 'ITKIOImageBase', )
templates = (
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS2ISS2', True, 'itk::Image< unsigned short,2 >, itk::Image< signed short,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS3ISS3', True, 'itk::Image< unsigned short,3 >, itk::Image< signed short,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS2IUC2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS3IUC3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('MorphologicalDistanceTransformImageFilter', 'itk::MorphologicalDistanceTransformImageFilter', 'itkMorphologicalDistanceTransformImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS2ISS2', True, 'itk::Image< unsigned short,2 >, itk::Image< signed short,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS3ISS3', True, 'itk::Image< unsigned short,3 >, itk::Image< signed short,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS2IUC2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS3IUC3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('MorphologicalSignedDistanceTransformImageFilter', 'itk::MorphologicalSignedDistanceTransformImageFilter', 'itkMorphologicalSignedDistanceTransformImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ParabolicCloseImageFilter', 'itk::ParabolicCloseImageFilter', 'itkParabolicCloseImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ParabolicDilateImageFilter', 'itk::ParabolicDilateImageFilter', 'itkParabolicDilateImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ParabolicErodeImageFilter', 'itk::ParabolicErodeImageFilter', 'itkParabolicErodeImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ParabolicOpenImageFilter', 'itk::ParabolicOpenImageFilter', 'itkParabolicOpenImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MorphologicalSharpeningImageFilter', 'itk::MorphologicalSharpeningImageFilter', 'itkMorphologicalSharpeningImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
)
snake_case_functions = ('parabolic_open_close_safe_border_image_filter', 'parabolic_erode_image_filter', 'morphological_signed_distance_transform_image_filter', 'parabolic_erode_dilate_image_filter', 'parabolic_open_image_filter', 'parabolic_dilate_image_filter', 'parabolic_close_image_filter', 'morphological_sharpening_image_filter', 'morphological_distance_transform_image_filter', )
