[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm"]

[tool.black]
target-version = ["py36"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_first_party = "ufoLib2"
