[tool.poetry]
name = "gsrest"
version = "0.2.1"
description = "GeoServer python REST API client"
authors = ["Eduardo Suarez-Santana"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/esuarezsantana/gsrest"
keywords = ["geoserver", "gis", "client", "rest"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering :: GIS"
]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
Sphinx = "^3.0.3"
pytest-cov = "^2.8.1"
pytest-docker = "^0.7.2"
interrogate = "^1.1.4"
pytest-sugar = "^0.9.3"
pytest-tldr = "^0.2.1"
licenseheaders = "^0.8.5"
bump2version = "^1.0.0"

[tool.poetry.scripts]
gsrest = "gsrest.cli:main"

[tool.black]
line-length = 79
target-version = ['py37']

[tool.isort]
# black compatible
# https://black.readthedocs.io/en/stable/the_black_code_style.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

