[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
line_length = 120
atomic = true
force_single_line = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
filter_files = true

known_first_party = "zealous"
known_third_party = [
    "pydantic",
    "pytest",
]

[tool.poetry]
name = "zealous"
version = "0.2.2"
description = "Zealous Framework"
authors = ["Jonathan Gravel <jo@stashed.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.4"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pylint = "^2.5.0"
pytest = "^5.2"
pytest-asyncio = "^0.11.0"
pytest-cov = "^2.8.1"
pre-commit = "^2.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
