[tool.poetry]
name = "aircloak-tools"
version = "0.1.0"
description = ""
authors = ["dlennon <3168260+dandanlen@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
psycopg2 = "^2.8.5"
pandas = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
