# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectInputFilesGB_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.selectInputFilesGB_2.setObjectName("selectInputFilesGB_2")
        self.gridLayout = QtWidgets.QGridLayout(self.selectInputFilesGB_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.selectInputFilesGB_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.polygonShapefileLE = QtWidgets.QLineEdit(self.selectInputFilesGB_2)
        self.polygonShapefileLE.setObjectName("polygonShapefileLE")
        self.gridLayout.addWidget(self.polygonShapefileLE, 0, 1, 1, 1)
        self.selectInputFilesGB = QtWidgets.QLabel(self.selectInputFilesGB_2)
        self.selectInputFilesGB.setObjectName("selectInputFilesGB")
        self.gridLayout.addWidget(self.selectInputFilesGB, 0, 0, 1, 1)
        self.pointShapefileLE = QtWidgets.QLineEdit(self.selectInputFilesGB_2)
        self.pointShapefileLE.setObjectName("pointShapefileLE")
        self.gridLayout.addWidget(self.pointShapefileLE, 1, 1, 1, 1)
        self.polygonShapefileTB = QtWidgets.QToolButton(self.selectInputFilesGB_2)
        self.polygonShapefileTB.setObjectName("polygonShapefileTB")
        self.gridLayout.addWidget(self.polygonShapefileTB, 0, 2, 1, 1)
        self.pointShapefileTB = QtWidgets.QToolButton(self.selectInputFilesGB_2)
        self.pointShapefileTB.setObjectName("pointShapefileTB")
        self.gridLayout.addWidget(self.pointShapefileTB, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.selectInputFilesGB_2)
        self.selectByAttributeGB = QtWidgets.QGroupBox(self.centralwidget)
        self.selectByAttributeGB.setObjectName("selectByAttributeGB")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectByAttributeGB)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.shopTypeChB = QtWidgets.QCheckBox(self.selectByAttributeGB)
        self.shopTypeChB.setText("")
        self.shopTypeChB.setObjectName("shopTypeChB")
        self.horizontalLayout_4.addWidget(self.shopTypeChB)
        self.label_6 = QtWidgets.QLabel(self.selectByAttributeGB)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.pointFieldCB = QtWidgets.QComboBox(self.selectByAttributeGB)
        self.pointFieldCB.setEnabled(False)
        self.pointFieldCB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.pointFieldCB.setObjectName("pointFieldCB")
        self.horizontalLayout_4.addWidget(self.pointFieldCB)
        self.label_3 = QtWidgets.QLabel(self.selectByAttributeGB)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.shopTypeCB = QtWidgets.QComboBox(self.selectByAttributeGB)
        self.shopTypeCB.setEnabled(False)
        self.shopTypeCB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.shopTypeCB.setObjectName("shopTypeCB")
        self.horizontalLayout_4.addWidget(self.shopTypeCB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.selectByAttributeGB)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.polygonFieldCB = QtWidgets.QComboBox(self.selectByAttributeGB)
        self.polygonFieldCB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.polygonFieldCB.setObjectName("polygonFieldCB")
        self.horizontalLayout_3.addWidget(self.polygonFieldCB)
        self.label_2 = QtWidgets.QLabel(self.selectByAttributeGB)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.targetCountryCB = QtWidgets.QComboBox(self.selectByAttributeGB)
        self.targetCountryCB.setEnabled(False)
        self.targetCountryCB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.targetCountryCB.setObjectName("targetCountryCB")
        self.horizontalLayout_3.addWidget(self.targetCountryCB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.selectByAttributeGB)
        self.outputShapefileGB = QtWidgets.QGroupBox(self.centralwidget)
        self.outputShapefileGB.setObjectName("outputShapefileGB")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outputShapefileGB)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.newShapefilePB = QtWidgets.QPushButton(self.outputShapefileGB)
        self.newShapefilePB.setObjectName("newShapefilePB")
        self.gridLayout_3.addWidget(self.newShapefilePB, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.outputShapefileGB)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.newShapefileLE = QtWidgets.QLineEdit(self.outputShapefileGB)
        self.newShapefileLE.setObjectName("newShapefileLE")
        self.gridLayout_3.addWidget(self.newShapefileLE, 0, 1, 1, 1)
        self.newShapefileTB = QtWidgets.QToolButton(self.outputShapefileGB)
        self.newShapefileTB.setObjectName("newShapefileTB")
        self.gridLayout_3.addWidget(self.newShapefileTB, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.outputShapefileGB)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectInputFilesGB_2.setTitle(_translate("MainWindow", "Select input files"))
        self.label.setText(_translate("MainWindow", "Point shapefile"))
        self.selectInputFilesGB.setText(_translate("MainWindow", "Polygon shapefile"))
        self.polygonShapefileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse for a shapefile</p></body></html>"))
        self.polygonShapefileTB.setText(_translate("MainWindow", "..."))
        self.pointShapefileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse for a shapefile.</p></body></html>"))
        self.pointShapefileTB.setText(_translate("MainWindow", "..."))
        self.selectByAttributeGB.setTitle(_translate("MainWindow", "Select by attribute"))
        self.shopTypeChB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Specify shop type</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Point field: "))
        self.label_3.setText(_translate("MainWindow", "Target point: "))
        self.shopTypeCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select a shop type. Default is ALL. </p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Polygon field: "))
        self.label_2.setText(_translate("MainWindow", "Target polygon:"))
        self.targetCountryCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select a country</p></body></html>"))
        self.outputShapefileGB.setTitle(_translate("MainWindow", "Output shapefile"))
        self.newShapefilePB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click me to extract features to new shapefile.</p></body></html>"))
        self.newShapefilePB.setText(_translate("MainWindow", "Create new shapefile"))
        self.label_4.setText(_translate("MainWindow", "New shapefile: "))
        self.newShapefileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse for new output shapefile</p></body></html>"))
        self.newShapefileTB.setText(_translate("MainWindow", "..."))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit program"))

