language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alertlogic
  password:
    secure: y5JZKoc9eQhfiolxul42kAoKuJ/aEspomyjf4ooir8+IqkwF5ENvPFybxjffkRB1Kwo5SMAD0kGtWtbckumVjXnrVcdYLxl6Rf6WGUyg0YyQkoMwqdjqDWEEL8QiA7KHR4BoVxSRscnVtfxA9wT0oH0jomGek2y8fKgTq3DTID2yVWSYVW8++tZaQWe8aaXSUOTASGZtHvbxxDqcE1ssLwFRMvEPnHfR7euWqydMLlitdqQGnZXfZDzvnRVVcXzo+/z8UUID+ZciQef5BU/RpexKsXRkbjf6EvkvVgEEKjAQwL9xHDrKcBFs4/hFArlA8ECkdAsCkg6ZI38sKmtGV5NHcK18qTXY7/5cy55V3GTmFexCT9SX9HNPKHlOM6QR4NixbjFmPxVlvzNJMfbbPPzVnKbRppf34Eafud4Mzx9KQAPw8AqIK0uKP3nsmRrf3J3lgP6vaXvdtsyGXy7dOFJzBNLSBBAlPMuYFLEJzMymLh5HbLPdPL3gb2WSeexiqxm+XAIlbdTmVk1oVPgiz0tvmzpUSRpqoxDAuUiz9I21Znw8kiEpG5l9i74/lW1yv7DfXyj3/hiMme8LHxIDvZoMsH4qVPzVifUbmls8OmNgkq5pGyMfdawOdqwmwAGKv15/Z1QQHV4CRRDvjihtbdmshkjD23dTWeU/Qn1xAUM=
  on:
    tags: true
    repo: anton-b/alertlogic-sdk-definitions
    python: 3.8
