[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Vectr0 <ayzan@netriza.ml>"]
description = ""
name = "jspython"
version = "1.0.0"
[tool.poetry.dependencies]
python = "^3.8"
[tool.poetry.dev-dependencies]
