# coding: utf-8
# Generated by setup.py for PyCBC on 2020-06-03 13:59:36 +0000.

version = '1.16.2'
date = '2020-06-03 12:33:49 +0000'
release = True
last_release = '1.16.2'

git_hash = 'dc519f5363f41669533e0ffe170784db4452575f'
git_branch = 'None'
git_tag = 'v1.16.2'
git_author = 'Gareth S Davies <gareth.davies@ligo.org>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2020-06-03 13:59:36 +0000'
git_verbose_msg = """Version: 1.16.2
Branch: None
Tag: v1.16.2
Id: dc519f5363f41669533e0ffe170784db4452575f
Builder: Travis CI User <travis@example.org>
Build date: 2020-06-03 13:59:36 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
