# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/robot_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import parameter_pb2 as bosdyn_dot_api_dot_parameter__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/robot_id.proto',
  package='bosdyn.api',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x62osdyn/api/robot_id.proto\x12\nbosdyn.api\x1a\x1a\x62osdyn/api/parameter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n\x07RobotId\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0f\n\x07species\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12:\n\x10software_release\x18\x04 \x01(\x0b\x32 .bosdyn.api.RobotSoftwareRelease\x12\x10\n\x08nickname\x18\x05 \x01(\t\x12\x1e\n\x16\x63omputer_serial_number\x18\x06 \x01(\t\"T\n\x0fSoftwareVersion\x12\x15\n\rmajor_version\x18\x01 \x01(\x05\x12\x15\n\rminor_version\x18\x02 \x01(\x05\x12\x13\n\x0bpatch_level\x18\x03 \x01(\x05\"\xb4\x02\n\x14RobotSoftwareRelease\x12,\n\x07version\x18\x01 \x01(\x0b\x32\x1b.bosdyn.api.SoftwareVersion\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x32\n\x0e\x63hangeset_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tchangeset\x18\x05 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x06 \x01(\t\x12\x19\n\x11\x62uild_information\x18\x07 \x01(\t\x12\x30\n\x0cinstall_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\nparameters\x18\t \x03(\x0b\x32\x15.bosdyn.api.ParameterB\x0e\x42\x0cRobotIdProtob\x06proto3')
  ,
  dependencies=[bosdyn_dot_api_dot_parameter__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ROBOTID = _descriptor.Descriptor(
  name='RobotId',
  full_name='bosdyn.api.RobotId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='bosdyn.api.RobotId.serial_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='species', full_name='bosdyn.api.RobotId.species', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='bosdyn.api.RobotId.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='software_release', full_name='bosdyn.api.RobotId.software_release', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='bosdyn.api.RobotId.nickname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computer_serial_number', full_name='bosdyn.api.RobotId.computer_serial_number', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=279,
)


_SOFTWAREVERSION = _descriptor.Descriptor(
  name='SoftwareVersion',
  full_name='bosdyn.api.SoftwareVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major_version', full_name='bosdyn.api.SoftwareVersion.major_version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor_version', full_name='bosdyn.api.SoftwareVersion.minor_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patch_level', full_name='bosdyn.api.SoftwareVersion.patch_level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=365,
)


_ROBOTSOFTWARERELEASE = _descriptor.Descriptor(
  name='RobotSoftwareRelease',
  full_name='bosdyn.api.RobotSoftwareRelease',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='bosdyn.api.RobotSoftwareRelease.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.RobotSoftwareRelease.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='bosdyn.api.RobotSoftwareRelease.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='changeset_date', full_name='bosdyn.api.RobotSoftwareRelease.changeset_date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='changeset', full_name='bosdyn.api.RobotSoftwareRelease.changeset', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='bosdyn.api.RobotSoftwareRelease.api_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_information', full_name='bosdyn.api.RobotSoftwareRelease.build_information', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='install_date', full_name='bosdyn.api.RobotSoftwareRelease.install_date', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='bosdyn.api.RobotSoftwareRelease.parameters', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=676,
)

_ROBOTID.fields_by_name['software_release'].message_type = _ROBOTSOFTWARERELEASE
_ROBOTSOFTWARERELEASE.fields_by_name['version'].message_type = _SOFTWAREVERSION
_ROBOTSOFTWARERELEASE.fields_by_name['changeset_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ROBOTSOFTWARERELEASE.fields_by_name['install_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ROBOTSOFTWARERELEASE.fields_by_name['parameters'].message_type = bosdyn_dot_api_dot_parameter__pb2._PARAMETER
DESCRIPTOR.message_types_by_name['RobotId'] = _ROBOTID
DESCRIPTOR.message_types_by_name['SoftwareVersion'] = _SOFTWAREVERSION
DESCRIPTOR.message_types_by_name['RobotSoftwareRelease'] = _ROBOTSOFTWARERELEASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotId = _reflection.GeneratedProtocolMessageType('RobotId', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTID,
  __module__ = 'bosdyn.api.robot_id_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.RobotId)
  ))
_sym_db.RegisterMessage(RobotId)

SoftwareVersion = _reflection.GeneratedProtocolMessageType('SoftwareVersion', (_message.Message,), dict(
  DESCRIPTOR = _SOFTWAREVERSION,
  __module__ = 'bosdyn.api.robot_id_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.SoftwareVersion)
  ))
_sym_db.RegisterMessage(SoftwareVersion)

RobotSoftwareRelease = _reflection.GeneratedProtocolMessageType('RobotSoftwareRelease', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTSOFTWARERELEASE,
  __module__ = 'bosdyn.api.robot_id_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.RobotSoftwareRelease)
  ))
_sym_db.RegisterMessage(RobotSoftwareRelease)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\014RobotIdProto'))
# @@protoc_insertion_point(module_scope)
