# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/time_sync_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from bosdyn.api import time_sync_pb2 as bosdyn_dot_api_dot_time__sync__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/time_sync_service.proto',
  package='bosdyn.api',
  syntax='proto3',
  serialized_pb=_b('\n\"bosdyn/api/time_sync_service.proto\x12\nbosdyn.api\x1a\x17\x62osdyn/api/header.proto\x1a\x1a\x62osdyn/api/time_sync.proto\"\x98\x01\n\x15TimeSyncUpdateRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12:\n\x13previous_round_trip\x18\x02 \x01(\x0b\x32\x1d.bosdyn.api.TimeSyncRoundTrip\x12\x18\n\x10\x63lock_identifier\x18\x03 \x01(\t\"\xc1\x01\n\x16TimeSyncUpdateResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x37\n\x11previous_estimate\x18\x02 \x01(\x0b\x32\x1c.bosdyn.api.TimeSyncEstimate\x12(\n\x05state\x18\x03 \x01(\x0b\x32\x19.bosdyn.api.TimeSyncState\x12\x18\n\x10\x63lock_identifier\x18\x04 \x01(\t\"\\\n\x15TimeSyncStatusRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x18\n\x10\x63lock_identifier\x18\x02 \x01(\t\"\xf2\x01\n\x16TimeSyncStatusResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12W\n\x14time_sync_status_map\x18\x03 \x03(\x0b\x32\x39.bosdyn.api.TimeSyncStatusResponse.TimeSyncStatusMapEntry\x1aS\n\x16TimeSyncStatusMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bosdyn.api.TimeSyncState:\x02\x38\x01\x32\xc7\x01\n\x0fTimeSyncService\x12Y\n\x0eTimeSyncUpdate\x12!.bosdyn.api.TimeSyncUpdateRequest\x1a\".bosdyn.api.TimeSyncUpdateResponse\"\x00\x12Y\n\x0eTimeSyncStatus\x12!.bosdyn.api.TimeSyncStatusRequest\x1a\".bosdyn.api.TimeSyncStatusResponse\"\x00\x42\x16\x42\x14TimeSyncServiceProtob\x06proto3')
  ,
  dependencies=[bosdyn_dot_api_dot_header__pb2.DESCRIPTOR,bosdyn_dot_api_dot_time__sync__pb2.DESCRIPTOR,])




_TIMESYNCUPDATEREQUEST = _descriptor.Descriptor(
  name='TimeSyncUpdateRequest',
  full_name='bosdyn.api.TimeSyncUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.TimeSyncUpdateRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='previous_round_trip', full_name='bosdyn.api.TimeSyncUpdateRequest.previous_round_trip', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock_identifier', full_name='bosdyn.api.TimeSyncUpdateRequest.clock_identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=256,
)


_TIMESYNCUPDATERESPONSE = _descriptor.Descriptor(
  name='TimeSyncUpdateResponse',
  full_name='bosdyn.api.TimeSyncUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.TimeSyncUpdateResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='previous_estimate', full_name='bosdyn.api.TimeSyncUpdateResponse.previous_estimate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='bosdyn.api.TimeSyncUpdateResponse.state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock_identifier', full_name='bosdyn.api.TimeSyncUpdateResponse.clock_identifier', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=452,
)


_TIMESYNCSTATUSREQUEST = _descriptor.Descriptor(
  name='TimeSyncStatusRequest',
  full_name='bosdyn.api.TimeSyncStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.TimeSyncStatusRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock_identifier', full_name='bosdyn.api.TimeSyncStatusRequest.clock_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=546,
)


_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY = _descriptor.Descriptor(
  name='TimeSyncStatusMapEntry',
  full_name='bosdyn.api.TimeSyncStatusResponse.TimeSyncStatusMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bosdyn.api.TimeSyncStatusResponse.TimeSyncStatusMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='bosdyn.api.TimeSyncStatusResponse.TimeSyncStatusMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=791,
)

_TIMESYNCSTATUSRESPONSE = _descriptor.Descriptor(
  name='TimeSyncStatusResponse',
  full_name='bosdyn.api.TimeSyncStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.TimeSyncStatusResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_sync_status_map', full_name='bosdyn.api.TimeSyncStatusResponse.time_sync_status_map', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=791,
)

_TIMESYNCUPDATEREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_TIMESYNCUPDATEREQUEST.fields_by_name['previous_round_trip'].message_type = bosdyn_dot_api_dot_time__sync__pb2._TIMESYNCROUNDTRIP
_TIMESYNCUPDATERESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
_TIMESYNCUPDATERESPONSE.fields_by_name['previous_estimate'].message_type = bosdyn_dot_api_dot_time__sync__pb2._TIMESYNCESTIMATE
_TIMESYNCUPDATERESPONSE.fields_by_name['state'].message_type = bosdyn_dot_api_dot_time__sync__pb2._TIMESYNCSTATE
_TIMESYNCSTATUSREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY.fields_by_name['value'].message_type = bosdyn_dot_api_dot_time__sync__pb2._TIMESYNCSTATE
_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY.containing_type = _TIMESYNCSTATUSRESPONSE
_TIMESYNCSTATUSRESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
_TIMESYNCSTATUSRESPONSE.fields_by_name['time_sync_status_map'].message_type = _TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY
DESCRIPTOR.message_types_by_name['TimeSyncUpdateRequest'] = _TIMESYNCUPDATEREQUEST
DESCRIPTOR.message_types_by_name['TimeSyncUpdateResponse'] = _TIMESYNCUPDATERESPONSE
DESCRIPTOR.message_types_by_name['TimeSyncStatusRequest'] = _TIMESYNCSTATUSREQUEST
DESCRIPTOR.message_types_by_name['TimeSyncStatusResponse'] = _TIMESYNCSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeSyncUpdateRequest = _reflection.GeneratedProtocolMessageType('TimeSyncUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMESYNCUPDATEREQUEST,
  __module__ = 'bosdyn.api.time_sync_service_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.TimeSyncUpdateRequest)
  ))
_sym_db.RegisterMessage(TimeSyncUpdateRequest)

TimeSyncUpdateResponse = _reflection.GeneratedProtocolMessageType('TimeSyncUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMESYNCUPDATERESPONSE,
  __module__ = 'bosdyn.api.time_sync_service_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.TimeSyncUpdateResponse)
  ))
_sym_db.RegisterMessage(TimeSyncUpdateResponse)

TimeSyncStatusRequest = _reflection.GeneratedProtocolMessageType('TimeSyncStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMESYNCSTATUSREQUEST,
  __module__ = 'bosdyn.api.time_sync_service_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.TimeSyncStatusRequest)
  ))
_sym_db.RegisterMessage(TimeSyncStatusRequest)

TimeSyncStatusResponse = _reflection.GeneratedProtocolMessageType('TimeSyncStatusResponse', (_message.Message,), dict(

  TimeSyncStatusMapEntry = _reflection.GeneratedProtocolMessageType('TimeSyncStatusMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY,
    __module__ = 'bosdyn.api.time_sync_service_pb2'
    # @@protoc_insertion_point(class_scope:bosdyn.api.TimeSyncStatusResponse.TimeSyncStatusMapEntry)
    ))
  ,
  DESCRIPTOR = _TIMESYNCSTATUSRESPONSE,
  __module__ = 'bosdyn.api.time_sync_service_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.TimeSyncStatusResponse)
  ))
_sym_db.RegisterMessage(TimeSyncStatusResponse)
_sym_db.RegisterMessage(TimeSyncStatusResponse.TimeSyncStatusMapEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\024TimeSyncServiceProto'))
_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY.has_options = True
_TIMESYNCSTATUSRESPONSE_TIMESYNCSTATUSMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_TIMESYNCSERVICE = _descriptor.ServiceDescriptor(
  name='TimeSyncService',
  full_name='bosdyn.api.TimeSyncService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=794,
  serialized_end=993,
  methods=[
  _descriptor.MethodDescriptor(
    name='TimeSyncUpdate',
    full_name='bosdyn.api.TimeSyncService.TimeSyncUpdate',
    index=0,
    containing_service=None,
    input_type=_TIMESYNCUPDATEREQUEST,
    output_type=_TIMESYNCUPDATERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TimeSyncStatus',
    full_name='bosdyn.api.TimeSyncService.TimeSyncStatus',
    index=1,
    containing_service=None,
    input_type=_TIMESYNCSTATUSREQUEST,
    output_type=_TIMESYNCSTATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIMESYNCSERVICE)

DESCRIPTOR.services_by_name['TimeSyncService'] = _TIMESYNCSERVICE

# @@protoc_insertion_point(module_scope)
