
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-02T18:19:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bae55cc78fb0ff2f1afc622d1c26d3d6e03aaba8",
 "version": "1.10.0.post.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
