version: 2

build:
    image: latest

python:
   version: 3.8
   install:
      - requirements: ci/requirements/requirements_doc.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: .
   system_packages: true

formats: []
