params:
  reads_layout: "pe"
  interleaved: False
  fq_encoding: "sanger"
  begin: "trimming"
  samples: "samples.tsv"

  simulate:
    do: True
    threads: 8

  raw:
    threads: 8
    save_reads: True
    fastqc:
      do: True

  trimming:
    save_reads: False
    oas1:
      do: False
      quality_system: 33
      min_length: 30
      seed_oa: 0.9
      fragment_oa: 0.8
    sickle:
      do: False
      quality_type: "sanger"
      sickle_pe: ""
      length_cutoff: 51
      quality_cutoff: 20
    fastp:
      do: True
      threads: 4
      disable_adapter_trimming: True
      use_slide_window: True
      compression: 6
      cut_front_window_size: 4
      cut_front_mean_quality: 20
      cut_tail_window_size: 4
      cut_tail_mean_quality: 20
      cut_right_window_size: 4
      cut_right_mean_quality: 20
      length_required: 51
      n_base_limit: 5

  rmhost:
    host_fasta: /home/alienzj/databases/genomepy/hg38/hg38.fa
    threads: 8
    save_reads: True
    save_bam: False
    compression: 6
    bwa:
      do: False
      index_prefix: /home/alienzj/databases/genomepy/hg38/index/bwa/hg38.fa
      minimum_seed_length: 23
    bowtie2:
      do: True
      index_prefix: /home/alienzj/databases/genomepy/hg38/index/bowtie2/hg38

  qcreport:
    do: True
    seqkit:
      threads: 4

  assembly:
    threads: 8
    megahit:
      do: False
      min_contig: 500
      only_save_scaftigs: True
    idba_ud:
      do: False
      mink: 27
      maxk: 127
      step: 10
      min_contig: 500
      only_save_scaftigs: True
    metaspades:
      do: True
      only_assembler: False
      only_save_scaftigs: True
      memory: 20
      kmers: ['21', '29', '39', '59', '79', '99']
    spades:
      do: False
      only_assembler: False
      only_save_scaftigs: True
      memory: 20
      kmers: ['21', '29', '39', '59', '79', '99']

    metaquast:
      do: False
      threads: 8
      min_contig: 500

    report:
      threads: 8
      len_ranges: [0, 1000, 1500, 2000, 2500, 3000]

  coassembly:
    megahit:
      do: False
      threads: 8
      min_contig: 500
      only_save_scaftigs: True

  alignment:
    do: True
    threads: 8
    cal_base_depth: False
    report: True

  binning:
    threads: 8
    metabat2:
      do: True
      min_contig: 1500
      seed: 2020
    maxbin2:
      do: False

  cobinning:
    do: False
    threads: 8
    scaftigs_length: 1000
    vsearch:
      identity: 0.75

  predict:
    threads: 8
    format: "gff"
    scaftigs_to_gene:
      prokka:
        do: False
      prodigal:
        do: False
    bins_to_gene:
      prokka:
        do: False
        kingdom: Bacteria
      prodigal:
        do: True

  checkm:
    do: True
    report: True
    threads: 8
    completeness: 90
    contamination: 10
    standard: "MIMAG" # SGB
    batch_num: 500

  classify:
    threads: 8
    kraken2:
      do: True
      database: /path/to/kraken2/database
      use_mpa_style: False
      report_zero_counts: True
    gtdbtk:
      do: True

  dereplicate:
    drep:
      do: True
      threads: 8
      filtering_genome_min_length: 50000
      filtering_completeness: 75
      filtering_contamination: 25
      genome_comparison_algorithm: "ANImf"
      clustering_primary_ANI: 0.9
      clustering_secondary_ANI: 0.99

  profiling:
    threads: 8
    metaphlan2:
      do: False
      bowtie2db: "/path/to/metaphlan_databases"
      index: "latest"
      bowtie2_presets: "very-sensitive"
      taxonomic_level: "a"
      min_cu_len: 2000
      avoid_disqm: True
      analysis_type: "rel_ab_w_read_stats"
      stat_q: "0.1"
      stat: "tavg_g"
      no_unknown_estimation: False
      input_type: "fastq"
      read_min_len: 70
      no_map: True
      biom: False
    jgi:
      oneway: False
      do: False
      fragment: 1200
      memory_limit: 8G
      compression_level: 6
      taxonomy: /path/to/taxonomy
      index_metadata: /path/to/index_metadata
      index_prefix: /path/to/bowtie2_index_prefix
    humann2:
      do: False
      remove_temp_output: True
      normalize_method: "relab"
      regroup_method: "sum"
      map_database: ["uniref90_go", "uniref90_ko", "uniref90_eggnog", "uniref90_pfam", "uniref90_level4ec", "uniref90_infogo1000", "uniref90_rxn"]


output:
  simulate: "results/00.simulate"
  raw: "results/00.raw"
  trimming: "results/01.trimming"
  rmhost: "results/02.rmhost"
  qcreport: "results/03.qcreport"
  assembly: "results/04.assembly"
  coassembly: "results/04.coassembly"
  alignment: "results/05.alignment"
  binning: "results/06.binning"
  cobinning: "results/06.cobinning"
  predict: "results/07.predict"
  checkm: "results/08.checkm"
  classify: "results/09.classify"
  dereplicate: "results/10.dereplicate"
  profiling: "results/11.profiling"
  upload: "results/99.upload"

upload:
  do: True
  threads: 8
  project_accession: "CNP0000000"

  samples:
    sample_title: ""
    tax_id: "447426"
    organism: "human oral metagenome"
    common_name: ""
    investigation_type: "metagenome"
    collection_date: "2018-11-19"
    env_biom: "saliva"
    env_feature: "saliva"
    env_material: "saliva material"
    geo_loc_name: "China: Shenzhen"
    host: "Homo sapiens"
    lat_lon: "22.35 N 114.27 E"
    strain: "missing"
    estimated_size: "missing"
    isol_growth_condt: "not collected"
    num_replicons: "not collected"
    ref_biomaterial: "not collected"
    ploidy: "missing"
    propagation: "not collected"

  sequencing_run:
    experiment_title: "WGS of human oral metagenome"
    library_name: "LIBRARY_NAME-BARCODE_ID"
    library_strategy: "WGS"
    library_source: "METAGENOMIC"
    library_selection: "RANDOM"
    library_layout: "paired"
    platform: "BGISEQ"
    instrument_model: "BGISEQ-500"
    design_description: "human oral metagenome"
    library_construction_protocol: "RANDOM"
    nominal_size: "350"
    file_type: "fastq"

  assembly:
    assembly_method: "SPAdes"
    assembly_method_version: "v3.13.0"
    assembly_partial: True
    assembly_coverage: "30"
    sequencing_technology: "BGISEQ"
    assembly_min_gap_length: ""
    assembly_mol_type: "genomic DNA"
    reference_genome: ""
