# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/backend/analytics/proto/software_release.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/backend/analytics/proto/software_release.proto',
  package='avsoftware.analytics',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2src/backend/analytics/proto/software_release.proto\x12\x14\x61vsoftware.analytics\"h\n\x0fSoftwareRelease\x12\x0f\n\x07release\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0b\n\x03sha\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61te_of_sha_utc\x18\x04 \x01(\t\x12\x0f\n\x07\x62lessed\x18\x05 \x01(\x08\x62\x06proto3')
)




_SOFTWARERELEASE = _descriptor.Descriptor(
  name='SoftwareRelease',
  full_name='avsoftware.analytics.SoftwareRelease',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='release', full_name='avsoftware.analytics.SoftwareRelease.release', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='avsoftware.analytics.SoftwareRelease.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sha', full_name='avsoftware.analytics.SoftwareRelease.sha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_sha_utc', full_name='avsoftware.analytics.SoftwareRelease.date_of_sha_utc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blessed', full_name='avsoftware.analytics.SoftwareRelease.blessed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['SoftwareRelease'] = _SOFTWARERELEASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SoftwareRelease = _reflection.GeneratedProtocolMessageType('SoftwareRelease', (_message.Message,), dict(
  DESCRIPTOR = _SOFTWARERELEASE,
  __module__ = 'src.backend.analytics.proto.software_release_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.analytics.SoftwareRelease)
  ))
_sym_db.RegisterMessage(SoftwareRelease)


# @@protoc_insertion_point(module_scope)
