# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/common/logging/analytics/slog_analytics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.backend.analytics.proto import field_custom_option_pb2 as src_dot_backend_dot_analytics_dot_proto_dot_field__custom__option__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/common/logging/analytics/slog_analytics.proto',
  package='avsoftware.slog_analytics',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n1src/common/logging/analytics/slog_analytics.proto\x12\x19\x61vsoftware.slog_analytics\x1a\x35src/backend/analytics/proto/field_custom_option.proto\"\xa1\x01\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x0cvalue_string\x18\x02 \x01(\tB\x07\x92\xa6\x1d\x03\x08\x80@\x12\x1e\n\x12value_numeric_data\x18\x03 \x01(\x04\x42\x02\x18\x01\x12\x11\n\tvalue_int\x18\x06 \x01(\x03\x12\x14\n\x0cvalue_double\x18\x07 \x01(\x01\x12\x11\n\tverbosity\x18\x04 \x01(\x05\x12\x12\n\nvalue_type\x18\x05 \x01(\x05\"8\n\x08\x43\x61llSite\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x10\n\x08\x66unction\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\"\xd3\x03\n\x06Record\x12\x10\n\x08severity\x18\x01 \x01(\x05\x12\x11\n\tthread_id\x18\x02 \x01(\x05\x12\x17\n\x0ftime_elapsed_ns\x18\x03 \x01(\x03\x12\x16\n\x0etime_global_ns\x18\x0e \x01(\x03\x12J\n\x14global_clock_type_id\x18\x10 \x01(\x0e\x32,.avsoftware.slog_analytics.GlobalClockTypeId\x12\x14\n\x0c\x63\x61ll_site_id\x18\x04 \x01(\x05\x12\x36\n\tcall_site\x18\x05 \x01(\x0b\x32#.avsoftware.slog_analytics.CallSite\x12,\n\x04tags\x18\x06 \x03(\x0b\x32\x1e.avsoftware.slog_analytics.Tag\x12\x11\n\tslog_text\x18\x07 \x01(\t\x12\x11\n\tflat_text\x18\x08 \x01(\t\x12\x10\n\x08username\x18\t \x01(\t\x12\x10\n\x08hostname\x18\n \x01(\t\x12\x12\n\nprocess_id\x18\x0b \x01(\x03\x12\x0f\n\x07git_sha\x18\x0c \x01(\t\x12\x12\n\ngit_branch\x18\r \x01(\t\x12(\n slog_analytics_converter_version\x18\x11 \x01(\x05*=\n\x11GlobalClockTypeId\x12\x13\n\x0fWALL_TIME_CLOCK\x10\x00\x12\x13\n\x0fGPS_EPOCH_CLOCK\x10\x01\x62\x06proto3')
  ,
  dependencies=[src_dot_backend_dot_analytics_dot_proto_dot_field__custom__option__pb2.DESCRIPTOR,])

_GLOBALCLOCKTYPEID = _descriptor.EnumDescriptor(
  name='GlobalClockTypeId',
  full_name='avsoftware.slog_analytics.GlobalClockTypeId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WALL_TIME_CLOCK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_EPOCH_CLOCK', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=827,
  serialized_end=888,
)
_sym_db.RegisterEnumDescriptor(_GLOBALCLOCKTYPEID)

GlobalClockTypeId = enum_type_wrapper.EnumTypeWrapper(_GLOBALCLOCKTYPEID)
WALL_TIME_CLOCK = 0
GPS_EPOCH_CLOCK = 1



_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='avsoftware.slog_analytics.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='avsoftware.slog_analytics.Tag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='avsoftware.slog_analytics.Tag.value_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222\246\035\003\010\200@'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_numeric_data', full_name='avsoftware.slog_analytics.Tag.value_numeric_data', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_int', full_name='avsoftware.slog_analytics.Tag.value_int', index=3,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_double', full_name='avsoftware.slog_analytics.Tag.value_double', index=4,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbosity', full_name='avsoftware.slog_analytics.Tag.verbosity', index=5,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='avsoftware.slog_analytics.Tag.value_type', index=6,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=297,
)


_CALLSITE = _descriptor.Descriptor(
  name='CallSite',
  full_name='avsoftware.slog_analytics.CallSite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='avsoftware.slog_analytics.CallSite.line', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='function', full_name='avsoftware.slog_analytics.CallSite.function', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='avsoftware.slog_analytics.CallSite.file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=355,
)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='avsoftware.slog_analytics.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='severity', full_name='avsoftware.slog_analytics.Record.severity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='avsoftware.slog_analytics.Record.thread_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_elapsed_ns', full_name='avsoftware.slog_analytics.Record.time_elapsed_ns', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_global_ns', full_name='avsoftware.slog_analytics.Record.time_global_ns', index=3,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_clock_type_id', full_name='avsoftware.slog_analytics.Record.global_clock_type_id', index=4,
      number=16, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_site_id', full_name='avsoftware.slog_analytics.Record.call_site_id', index=5,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_site', full_name='avsoftware.slog_analytics.Record.call_site', index=6,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='avsoftware.slog_analytics.Record.tags', index=7,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slog_text', full_name='avsoftware.slog_analytics.Record.slog_text', index=8,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat_text', full_name='avsoftware.slog_analytics.Record.flat_text', index=9,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='avsoftware.slog_analytics.Record.username', index=10,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='avsoftware.slog_analytics.Record.hostname', index=11,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='avsoftware.slog_analytics.Record.process_id', index=12,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_sha', full_name='avsoftware.slog_analytics.Record.git_sha', index=13,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_branch', full_name='avsoftware.slog_analytics.Record.git_branch', index=14,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slog_analytics_converter_version', full_name='avsoftware.slog_analytics.Record.slog_analytics_converter_version', index=15,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=825,
)

_RECORD.fields_by_name['global_clock_type_id'].enum_type = _GLOBALCLOCKTYPEID
_RECORD.fields_by_name['call_site'].message_type = _CALLSITE
_RECORD.fields_by_name['tags'].message_type = _TAG
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['CallSite'] = _CALLSITE
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.enum_types_by_name['GlobalClockTypeId'] = _GLOBALCLOCKTYPEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'src.common.logging.analytics.slog_analytics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.slog_analytics.Tag)
  ))
_sym_db.RegisterMessage(Tag)

CallSite = _reflection.GeneratedProtocolMessageType('CallSite', (_message.Message,), dict(
  DESCRIPTOR = _CALLSITE,
  __module__ = 'src.common.logging.analytics.slog_analytics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.slog_analytics.CallSite)
  ))
_sym_db.RegisterMessage(CallSite)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(
  DESCRIPTOR = _RECORD,
  __module__ = 'src.common.logging.analytics.slog_analytics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.slog_analytics.Record)
  ))
_sym_db.RegisterMessage(Record)


_TAG.fields_by_name['value_string']._options = None
_TAG.fields_by_name['value_numeric_data']._options = None
# @@protoc_insertion_point(module_scope)
