BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB


BBBBB BBBBBBBBBBBBBBBBBB
  
  XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
       gettext(u'Загрузить zip архив') 
    XXXX
  XXXXX
BBBBBBBB