BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB

BBBBB BBBBBBBBBB
	
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXX
BBBBBBBB

BBBBB BBBBBBBBBX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
        XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFXXXX
        XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
        FFFFFFFFXXXXBBBBFFFFFFFFBBBBB
        XXXXXXXX  gettext(u'Загрузка zip') 
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

	XXXX gettext(u'Загрузить zip архив изображений') XXXXX
	 gettext(u'\n\t\t<p>На этой странице вы можете загрузить несколько изображений одновременно, если у вас есть zip-архив.\n            Изображения могут быть:</p>\n\t\t<ul>\n\t\t\t<li>Добавлены в существующую галерею.</li>\n\t\t\t<li>Или будет создана новая галерея с указанным заголовком.</li>\n\t\t</ul>\n\t') 
		SSSSS SSSS SSSSSSSS SS SSSSSS SSSSSSSSS SSSSSSSSS SSSSSSSSSSS SSSSSSSSSSSSS SSSS S SSS SSSS SSSSSSSSSS
            SSSSSSSSSSS SSSSS SSSSSSSSS
		SSSS
			SSSSSSSSSSSSS S SSSSSSSSSSSS SSSSSSSSSSSSS
			SSSSSSS SSSSS SSSSSSS SSSSS SSSSSSS S SSSSSSSSS SSSSSSSSSSSSSSSS
		SSSSS
	

	BB BBBBBBBBBBB
	    XX XXXXXXXXXXXXXXXXXX
	    BB BBBBBBBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
	    XXXX
	    
	BBBBB

	XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
        BBBBBBBBBB
        XXXXX
            BBB BBBBBBBB BB BBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Загрузить') X XXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXXX

BBBBBBBB