
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-10T00:03:06+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a21794e72821cfc5f7cd0c355e6ddc166585d8d",
 "version": "0.3.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
