# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/sensor/radar/delphi_esr/proto/delphi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.avs.messages import lyft_car_time_pb2 as src_dot_avs_dot_messages_dot_lyft__car__time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/sensor/radar/delphi_esr/proto/delphi.proto',
  package='avsoftware.sensor.radar.delphi.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.src/sensor/radar/delphi_esr/proto/delphi.proto\x12$avsoftware.sensor.radar.delphi.proto\x1a$src/avs/messages/lyft_car_time.proto\"\x9b\x01\n\rDelphiEsrScan\x12.\n\rlyft_car_time\x18\x01 \x01(\x0b\x32\x17.avsoftware.LyftCarTime\x12\x43\n\x05track\x18\x02 \x03(\x0b\x32\x34.avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack\x12\x15\n\racc_track_ids\x18\x03 \x03(\x05\"\x81\x06\n\x0e\x44\x65lphiEsrTrack\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x17\n\x0ftrack_angle_rad\x18\x02 \x01(\x02\x12\x15\n\rtrack_width_m\x18\x03 \x01(\x02\x12K\n\x06status\x18\x04 \x01(\x0e\x32;.avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.Status\x12\x18\n\x10grouping_changed\x18\x05 \x01(\x08\x12\x15\n\rbridge_object\x18\x06 \x01(\x08\x12\x0f\n\x07range_m\x18\x07 \x01(\x02\x12\x16\n\x0erange_rate_mps\x18\x08 \x01(\x02\x12\x18\n\x10range_accel_mpss\x18\t \x01(\x02\x12R\n\nrange_mode\x18\n \x01(\x0e\x32>.avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.RangeMode\x12\x14\n\x0clat_rate_mps\x18\x0b \x01(\x02\x12\x10\n\x08oncoming\x18\x0c \x01(\x08\x12\x10\n\x08power_db\x18\r \x01(\x02\x12\x0e\n\x06moving\x18\x0e \x01(\x08\"\xe6\x01\n\x06Status\x12\x14\n\x10STATUS_NO_TARGET\x10\x00\x12!\n\x1dSTATUS_INVALID_COASTED_TARGET\x10\x06\x12\x15\n\x11STATUS_NEW_TARGET\x10\x01\x12\x1d\n\x19STATUS_NEW_UPDATED_TARGET\x10\x02\x12\x19\n\x15STATUS_UPDATED_TARGET\x10\x03\x12\x1d\n\x19STATUS_NEW_COASTED_TARGET\x10\x07\x12\x19\n\x15STATUS_COASTED_TARGET\x10\x04\x12\x18\n\x14STATUS_MERGED_TARGET\x10\x05\"e\n\tRangeMode\x12\x13\n\x0fRANGE_MODE_NONE\x10\x00\x12\x16\n\x12RANGE_MODE_MR_ONLY\x10\x01\x12\x16\n\x12RANGE_MODE_LR_ONLY\x10\x02\x12\x13\n\x0fRANGE_MODE_BOTH\x10\x03\x62\x06proto3')
  ,
  dependencies=[src_dot_avs_dot_messages_dot_lyft__car__time__pb2.DESCRIPTOR,])



_DELPHIESRTRACK_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_NO_TARGET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_COASTED_TARGET', index=1, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NEW_TARGET', index=2, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NEW_UPDATED_TARGET', index=3, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UPDATED_TARGET', index=4, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NEW_COASTED_TARGET', index=5, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_COASTED_TARGET', index=6, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_MERGED_TARGET', index=7, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=721,
  serialized_end=951,
)
_sym_db.RegisterEnumDescriptor(_DELPHIESRTRACK_STATUS)

_DELPHIESRTRACK_RANGEMODE = _descriptor.EnumDescriptor(
  name='RangeMode',
  full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.RangeMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANGE_MODE_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_MODE_MR_ONLY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_MODE_LR_ONLY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_MODE_BOTH', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=953,
  serialized_end=1054,
)
_sym_db.RegisterEnumDescriptor(_DELPHIESRTRACK_RANGEMODE)


_DELPHIESRSCAN = _descriptor.Descriptor(
  name='DelphiEsrScan',
  full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lyft_car_time', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrScan.lyft_car_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrScan.track', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_track_ids', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrScan.acc_track_ids', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=282,
)


_DELPHIESRTRACK = _descriptor.Descriptor(
  name='DelphiEsrTrack',
  full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track_id', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.track_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_angle_rad', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.track_angle_rad', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_width_m', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.track_width_m', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grouping_changed', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.grouping_changed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bridge_object', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.bridge_object', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_m', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.range_m', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_rate_mps', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.range_rate_mps', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_accel_mpss', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.range_accel_mpss', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_mode', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.range_mode', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_rate_mps', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.lat_rate_mps', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oncoming', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.oncoming', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power_db', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.power_db', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moving', full_name='avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack.moving', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DELPHIESRTRACK_STATUS,
    _DELPHIESRTRACK_RANGEMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=1054,
)

_DELPHIESRSCAN.fields_by_name['lyft_car_time'].message_type = src_dot_avs_dot_messages_dot_lyft__car__time__pb2._LYFTCARTIME
_DELPHIESRSCAN.fields_by_name['track'].message_type = _DELPHIESRTRACK
_DELPHIESRTRACK.fields_by_name['status'].enum_type = _DELPHIESRTRACK_STATUS
_DELPHIESRTRACK.fields_by_name['range_mode'].enum_type = _DELPHIESRTRACK_RANGEMODE
_DELPHIESRTRACK_STATUS.containing_type = _DELPHIESRTRACK
_DELPHIESRTRACK_RANGEMODE.containing_type = _DELPHIESRTRACK
DESCRIPTOR.message_types_by_name['DelphiEsrScan'] = _DELPHIESRSCAN
DESCRIPTOR.message_types_by_name['DelphiEsrTrack'] = _DELPHIESRTRACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DelphiEsrScan = _reflection.GeneratedProtocolMessageType('DelphiEsrScan', (_message.Message,), dict(
  DESCRIPTOR = _DELPHIESRSCAN,
  __module__ = 'src.sensor.radar.delphi_esr.proto.delphi_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.sensor.radar.delphi.proto.DelphiEsrScan)
  ))
_sym_db.RegisterMessage(DelphiEsrScan)

DelphiEsrTrack = _reflection.GeneratedProtocolMessageType('DelphiEsrTrack', (_message.Message,), dict(
  DESCRIPTOR = _DELPHIESRTRACK,
  __module__ = 'src.sensor.radar.delphi_esr.proto.delphi_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.sensor.radar.delphi.proto.DelphiEsrTrack)
  ))
_sym_db.RegisterMessage(DelphiEsrTrack)


# @@protoc_insertion_point(module_scope)
