
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-07T13:37:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d94d3a20948bf05dbf3529b7c7dbd99e4d65e28",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
