# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/avs/messages/resource_usage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.common.time import time_pb2 as src_dot_common_dot_time_dot_time__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/avs/messages/resource_usage.proto',
  package='avsoftware.avs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%src/avs/messages/resource_usage.proto\x12\x0e\x61vsoftware.avs\x1a\x1asrc/common/time/time.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc7\x02\n\x11ResourceUsageInfo\x12,\n\ruser_cpu_time\x18\x01 \x01(\x0b\x32\x15.avsoftware.TimeProto\x12.\n\x0fsystem_cpu_time\x18\x02 \x01(\x0b\x32\x15.avsoftware.TimeProto\x12\x1d\n\x15max_resident_set_size\x18\x03 \x01(\x03\x12\x17\n\x0fsoft_page_fault\x18\x04 \x01(\x03\x12\x17\n\x0fhard_page_fault\x18\x05 \x01(\x03\x12\x1d\n\x15\x62lock_input_operation\x18\x06 \x01(\x03\x12\x1e\n\x16\x62lock_output_operation\x18\x07 \x01(\x03\x12 \n\x18voluntary_context_switch\x18\x08 \x01(\x03\x12\"\n\x1ainvoluntary_context_switch\x18\t \x01(\x03\"f\n\x13ThreadResourceUsage\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x39\n\x0eresource_usage\x18\x02 \x01(\x0b\x32!.avsoftware.avs.ResourceUsageInfob\x06proto3')
  ,
  dependencies=[src_dot_common_dot_time_dot_time__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_RESOURCEUSAGEINFO = _descriptor.Descriptor(
  name='ResourceUsageInfo',
  full_name='avsoftware.avs.ResourceUsageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_cpu_time', full_name='avsoftware.avs.ResourceUsageInfo.user_cpu_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system_cpu_time', full_name='avsoftware.avs.ResourceUsageInfo.system_cpu_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_resident_set_size', full_name='avsoftware.avs.ResourceUsageInfo.max_resident_set_size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='soft_page_fault', full_name='avsoftware.avs.ResourceUsageInfo.soft_page_fault', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hard_page_fault', full_name='avsoftware.avs.ResourceUsageInfo.hard_page_fault', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_input_operation', full_name='avsoftware.avs.ResourceUsageInfo.block_input_operation', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_output_operation', full_name='avsoftware.avs.ResourceUsageInfo.block_output_operation', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voluntary_context_switch', full_name='avsoftware.avs.ResourceUsageInfo.voluntary_context_switch', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='involuntary_context_switch', full_name='avsoftware.avs.ResourceUsageInfo.involuntary_context_switch', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=445,
)


_THREADRESOURCEUSAGE = _descriptor.Descriptor(
  name='ThreadResourceUsage',
  full_name='avsoftware.avs.ThreadResourceUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='avsoftware.avs.ThreadResourceUsage.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource_usage', full_name='avsoftware.avs.ThreadResourceUsage.resource_usage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=549,
)

_RESOURCEUSAGEINFO.fields_by_name['user_cpu_time'].message_type = src_dot_common_dot_time_dot_time__pb2._TIMEPROTO
_RESOURCEUSAGEINFO.fields_by_name['system_cpu_time'].message_type = src_dot_common_dot_time_dot_time__pb2._TIMEPROTO
_THREADRESOURCEUSAGE.fields_by_name['resource_usage'].message_type = _RESOURCEUSAGEINFO
DESCRIPTOR.message_types_by_name['ResourceUsageInfo'] = _RESOURCEUSAGEINFO
DESCRIPTOR.message_types_by_name['ThreadResourceUsage'] = _THREADRESOURCEUSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceUsageInfo = _reflection.GeneratedProtocolMessageType('ResourceUsageInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEUSAGEINFO,
  __module__ = 'src.avs.messages.resource_usage_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.avs.ResourceUsageInfo)
  ))
_sym_db.RegisterMessage(ResourceUsageInfo)

ThreadResourceUsage = _reflection.GeneratedProtocolMessageType('ThreadResourceUsage', (_message.Message,), dict(
  DESCRIPTOR = _THREADRESOURCEUSAGE,
  __module__ = 'src.avs.messages.resource_usage_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.avs.ThreadResourceUsage)
  ))
_sym_db.RegisterMessage(ThreadResourceUsage)


# @@protoc_insertion_point(module_scope)
