[tool.poetry]
name = "torchdataset"
version = "0.1.1"
description = "This is a package to handle various kinds of data in a unified way with Pytorch."
authors = ["popura"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^7.1.2"
sox = "^1.3.7"
torch = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
