[tool.poetry]
name = "pengu"
version = "0.0.1"
description = "WIP"
authors = ["peachanG <kenkman0427@gmail.com>"]
homepage = "https://github.com/peachanG"
repository = "https://github.com/peachanG/pengu"
documentation = "https://peachang.github.io/pengu/"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.6"
tensorflow = "2.2.0"
pytest = {version = "^5.4.3", optional = true, extras = ["test"]}
pytest-cov = {version = "^2.9.0", optional = true, extras = ["test"]}
flake8 = {version = "^3.8.2", optional = true, extras = ["test"]}
mypy = "^0.780"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
test = ["pytest", "pytest-cov", "flake8"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
