################################################################################
#                             music-metadata-tools                             #
#  A collection of tools for manipulating and interacting with music metadata  #
#                  (C) 2009-10, 2015-16, 2019-20 Jeremy Brown                  #
#       Released under version 3.0 of the Non-Profit Open Source License       #
################################################################################

[build-system]
build-backend = "setuptools.build_meta"

requires = [
	"setuptools >= 43.0.0",
	"setuptools_scm[toml] >= 3.4",
	"wheel",
	]

[tool.setuptools_scm]
local_scheme = "no-local-version"
