[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "autoclasstoc"
author = "Kale Kundert"
author-email = "kale@thekunderts.net"
home-page = 'https://github.com/kalekundert/autoclasstoc'
description-file = 'README.rst'
requires-python = "~=3.7"
requires = [
  'sphinx~=3.0',
  'docutils',
]
classifiers = [
  'Programming Language :: Python :: 3',
  'License :: OSI Approved :: MIT License',
]

[tool.flit.metadata.urls]
'Documentation' = 'https://autoclasstoc.readthedocs.io/en/latest/'
'Version Control' = 'https://github.com/kalekundert/autoclasstoc'
'Bug Tracker' = 'https://github.com/kalekundert/autoclasstoc/issues'


