# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_status_controller_api import UserStatusControllerApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserStatusControllerApi(unittest.TestCase):
    """UserStatusControllerApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_status_controller_api.UserStatusControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index(self):
        """Test case for index

        """
        pass


if __name__ == '__main__':
    unittest.main()
