# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.data_cell_controller_api import DataCellControllerApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDataCellControllerApi(unittest.TestCase):
    """DataCellControllerApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.data_cell_controller_api.DataCellControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_data(self):
        """Test case for create_data

        """
        pass

    def test_get_field(self):
        """Test case for get_field

        """
        pass

    def test_get_row(self):
        """Test case for get_row

        """
        pass

    def test_get_table(self):
        """Test case for get_table

        """
        pass


if __name__ == '__main__':
    unittest.main()
