[tool.poetry]
name = "datactl"
version = "0.1.1"
description = ""
authors = ["Mohamed Cherkaoui <chermed@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
fire = "^0.3.1"
toml = "^0.10.1"
pika = {version = "^1.1.0", optional = true}
redis = {version = "^3.5.2", optional = true}
pymongo = {version = "^3.10.1", optional = true}
termcolor = "^1.1.0"
terminaltables = "^3.1.0"
pyyaml = "^5.3.1"
pendulum = "^2.1.0"
celery = {version = "^4.4.2", optional = true}
requests = {version = "^2.23.0", optional = true}


[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipdb = "^0.13.2"
autopep8 = "^1.5.2"
rope = "^0.17.0"
pylint = "^2.5.2"
twine = "^3.1.1"

[tool.poetry.scripts]
datactl = 'datactl.datactl:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

