repos:
- hooks:
  - exclude: .bumpversion.cfg
    id: trailing-whitespace
  - exclude: .bumpversion.cfg
    id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: check-ast
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
- hooks:
  - args:
    - --config=tox.ini
    id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - id: black
    language_version: python3.7
  repo: https://github.com/ambv/black
  rev: 19.10b0
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v1.25.2
- hooks:
  - args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --use-parentheses
    - --line-width=88
    id: isort
  repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
- hooks:
  - id: seed-isort-config
  repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
