import abc
import builtins
import datetime
import enum
import typing

import jsii
import jsii.compat
import publication

import aws_cdk.alexa_ask
import aws_cdk.aws_accessanalyzer
import aws_cdk.aws_acmpca
import aws_cdk.aws_amazonmq
import aws_cdk.aws_amplify
import aws_cdk.aws_apigateway
import aws_cdk.aws_apigatewayv2
import aws_cdk.aws_appconfig
import aws_cdk.aws_applicationautoscaling
import aws_cdk.aws_appmesh
import aws_cdk.aws_appstream
import aws_cdk.aws_appsync
import aws_cdk.aws_athena
import aws_cdk.aws_autoscaling
import aws_cdk.aws_autoscalingplans
import aws_cdk.aws_backup
import aws_cdk.aws_batch
import aws_cdk.aws_budgets
import aws_cdk.aws_cassandra
import aws_cdk.aws_ce
import aws_cdk.aws_certificatemanager
import aws_cdk.aws_chatbot
import aws_cdk.aws_cloud9
import aws_cdk.aws_cloudfront
import aws_cdk.aws_cloudtrail
import aws_cdk.aws_cloudwatch
import aws_cdk.aws_codebuild
import aws_cdk.aws_codecommit
import aws_cdk.aws_codedeploy
import aws_cdk.aws_codeguruprofiler
import aws_cdk.aws_codepipeline
import aws_cdk.aws_codestar
import aws_cdk.aws_codestarconnections
import aws_cdk.aws_codestarnotifications
import aws_cdk.aws_cognito
import aws_cdk.aws_config
import aws_cdk.aws_datapipeline
import aws_cdk.aws_dax
import aws_cdk.aws_detective
import aws_cdk.aws_directoryservice
import aws_cdk.aws_dlm
import aws_cdk.aws_dms
import aws_cdk.aws_docdb
import aws_cdk.aws_dynamodb
import aws_cdk.aws_ec2
import aws_cdk.aws_ecr
import aws_cdk.aws_ecs
import aws_cdk.aws_efs
import aws_cdk.aws_eks
import aws_cdk.aws_elasticache
import aws_cdk.aws_elasticbeanstalk
import aws_cdk.aws_elasticloadbalancing
import aws_cdk.aws_elasticloadbalancingv2
import aws_cdk.aws_elasticsearch
import aws_cdk.aws_emr
import aws_cdk.aws_events
import aws_cdk.aws_eventschemas
import aws_cdk.aws_fms
import aws_cdk.aws_fsx
import aws_cdk.aws_gamelift
import aws_cdk.aws_globalaccelerator
import aws_cdk.aws_glue
import aws_cdk.aws_greengrass
import aws_cdk.aws_guardduty
import aws_cdk.aws_iam
import aws_cdk.aws_imagebuilder
import aws_cdk.aws_inspector
import aws_cdk.aws_iot
import aws_cdk.aws_iot1click
import aws_cdk.aws_iotanalytics
import aws_cdk.aws_iotevents
import aws_cdk.aws_iotthingsgraph
import aws_cdk.aws_kinesis
import aws_cdk.aws_kinesisanalytics
import aws_cdk.aws_kinesisfirehose
import aws_cdk.aws_kms
import aws_cdk.aws_lakeformation
import aws_cdk.aws_lambda
import aws_cdk.aws_logs
import aws_cdk.aws_macie
import aws_cdk.aws_managedblockchain
import aws_cdk.aws_mediaconvert
import aws_cdk.aws_medialive
import aws_cdk.aws_mediastore
import aws_cdk.aws_msk
import aws_cdk.aws_neptune
import aws_cdk.aws_networkmanager
import aws_cdk.aws_opsworks
import aws_cdk.aws_opsworkscm
import aws_cdk.aws_pinpoint
import aws_cdk.aws_pinpointemail
import aws_cdk.aws_qldb
import aws_cdk.aws_ram
import aws_cdk.aws_rds
import aws_cdk.aws_redshift
import aws_cdk.aws_resourcegroups
import aws_cdk.aws_robomaker
import aws_cdk.aws_route53
import aws_cdk.aws_route53resolver
import aws_cdk.aws_s3
import aws_cdk.aws_sagemaker
import aws_cdk.aws_sam
import aws_cdk.aws_sdb
import aws_cdk.aws_secretsmanager
import aws_cdk.aws_securityhub
import aws_cdk.aws_servicecatalog
import aws_cdk.aws_servicediscovery
import aws_cdk.aws_ses
import aws_cdk.aws_sns
import aws_cdk.aws_sqs
import aws_cdk.aws_ssm
import aws_cdk.aws_stepfunctions
import aws_cdk.aws_synthetics
import aws_cdk.aws_transfer
import aws_cdk.aws_waf
import aws_cdk.aws_wafregional
import aws_cdk.aws_wafv2
import aws_cdk.aws_workspaces
import aws_cdk.core
import constructs

__jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/cloudformation-include", "1.42.1", __name__[0:-6], "cloudformation-include@1.42.1.jsii.tgz")

__all__ = [
    "__jsii_assembly__",
]

publication.publish()
