[tool.poetry]
name = "bbbmon"
version = "0.1.32"
description = "A small CLI utility to monitor bbb usage"
authors = ["David Huss <david.huss@hfbk-hamburg.de>"]
maintainers = ["David Huss <david.huss@hfbk-hamburg.de>"]
license = "GPL-3.0+"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "License :: Free for non-commercial use",
    "License :: Free For Educational Use",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.6",
    "Topic :: System :: Monitoring",
    "Topic :: Communications :: Conferencing"
]

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.23.0"
click = "^7.1.2"
click-help-colors = "^0.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
bbbmon = "bbbmon.bbbmon:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

