language: python
sudo: false
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
# Builds on pypy with C extension fail for some reason:
# - pypy
- pypy3.5
env:
- PYTHONHASHSEED=random
  PURE=false
matrix:
  include:
    - python: 3.6
      env: PURE=true
    - python: 2.7
      env: PURE=true
    - python: pypy3.5
      env: PURE=true
    - python: pypy
      env: PURE=true
install:
- travis_retry pip install -U pip setuptools
script:
- if [ $PURE = false ]; then python setup.py build_ext -i; fi
- python -m unittest patiencediff.test_patiencediff
- if [ $PURE = true ]; then SETUP_ARGS=--pure; fi
- python setup.py $SETUP_ARGS bdist_wheel
deploy:
  provider: pypi
  user: breezy-bot
  password:
    secure: Oe3m50K6LIgjBSTS/tJMW5D7BCMVjbkVS4z78igaldM+Tcy/F5ZxjwOJ/xvLXovf+B2BAP7O+tRqlJ6lax2gE/AWVy47aW/JMZYTgdihUDNGyZ1PqzYVaBAsTlJ1UYDSxpm7PkWqTA1MC0IXuTpV6O3x2XbuSvNlBGoNovFCY1T+blGl9xayo+mlt7kZ5NwJZsP7T2b3mkhtUHIoh13fAZFygit+DooFydnl1RWf33XksW7mdn3hJkvMKqXgYNIGrZTTNzFrBIBCCO30WRrFuk/8qddE5WYfQ7KfLIVEYionUSIZKIvF3B1W9lXz5HW5K7ifjpku6GD4g7lOUtAwU/jaKq+/kPC/4gMuuzr9kRYTaAZtdrvCrWuS3DLvsNDdfpNFcvD4OHVmKgCCZIvIMwDYk6Swa2Nrbnb/btKUpa029Nn+k4E483p7zEZTQBZxQkkUj83Sanp469IbRCzsIy6cUu1Q/R/uNKfDiWR3TtQeQHAIju1PCvR9rmB2vhFJMytzVT5koHQnchhx7R+LYaPbweAVwdUK5BPxdOiheSiBKiNXj4otlZnT7hBPBrqIDqUZKIPDwU0XQjPjHXaYwWbitVJXLopONHZGqSa6QYlAxXw/EDfaOR2eqN3g/DZ3UYF54GuPVJIyjJIt6v6Mwkm6j+jVfCVTNUnzEmfWvCg=
  skip_cleanup: true
  skip_existing: true
  file_glob: true
  file:
  - dist/patiencediff*.whl
  - dist/patiencediff*.tar.gz
  on:
    tags: true
    repo: breezy-team/patiencediff
