[tool.poetry]
name = "crystal_toolkit"
version = "2020.06.04"
description = ""
authors = ["Matthew Horton <mkhorton@lbl.gov>"]

[tool.poetry.dependencies]
python = "^3.7"
dash = "^1.12.0"
plotly = "^4.5.4"
dash-daq = "^0.4.0"
gunicorn = "^20.0.4"
redis = "^3.4.1"
Flask-Caching = "^1.8.0"
gevent = "^1.4.0"
dash-mp-components = ">=0.0.24"
pymatgen = "^2020.4.29"
scikit-learn = "^0.22.2"
webcolors = "^1.11.1"
pydantic = "^1.4"
robocrys = "^0.2.1"
typing-extensions = { version = "^3.7", python = "~3.7" }
scikit-image = "^0.17.2"
habanero = "^0.7.2"
hiphive = "^0.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^2.2.0"
dash = {extras = ["testing"], version = "^1.11.0"}
pytest = "^5.3.5"
sphinx = "^2.4.4"
sphinx_rtd_theme = "^0.4.3"
recommonmark = "^0.6.0"
dephell = "^0.8.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
