[tool.poetry]
name = "poethepoet"
version = "0.1.0"
description = "A task runner that works well with poetry."
authors = ["Nat Noordanus <n@natn.me>"]
readme = "README.rst"
license = "MIT"
repository =  "https://github.com/nat-n/poethepoet"
homepage =  "https://github.com/nat-n/poethepoet"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.1"
poetry = "^1.0.5"
pastel = "^0.2.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
bpython = "^0.19"
mypy = "^0.770"
pylint = "^2.5.2"
pytest = "^5.2"
pytest-cov = "^2.9.0"

[tool.poetry.scripts]
poe = "poethepoet.cli:main"

[tool.poe.tasks]
# Dev actions
format = "black ."
clean = """
  # multiline commands including comments work too!
  rm -rf .coverage
         .mypy_cache
         .pytest_cache
         dist
         ./**/__pycache__
"""
# Code quality checks
test = "pytest --cov=poethepoet tests"
types = "mypy poethepoet --ignore-missing-imports"
lint = "pylint poethepoet"
style = "black . --check --diff"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
