[tool.poetry]
name = "transmission-rpc"
version = "3.0.0a1"
description = "Python module that implements the Transmission bittorent client RPC protocol"
authors = ["Trim21 <i@trim21.me>"]
readme = 'README.md'
repository = 'https://github.com/Trim21/transmission-rpc'
license = 'MIT'
packages = [{ include = 'transmission_rpc' }]
classifiers = [
  'Intended Audience :: Developers',
  'Development Status :: 2 - Pre-Alpha',
  'License :: OSI Approved :: MIT License',
  'Topic :: Communications :: File Sharing',
  'Topic :: Internet',
  'Topic :: Software Development :: Version Control :: Git',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
]

[tool.poetry.dependencies]
python = "^3.6.1"
# dependencies
requests = "^2.23.0"
yarl = "^1.4.2"
# build cos
sphinx = { version = "^2.2", optional = true }
sphinx-rtd-theme = { version = "^0.4.3", optional = true }

[tool.poetry.extras]
docs = ['sphinx', 'sphinx-rtd-theme']

[tool.poetry.dev-dependencies]
# tests
pytest = "==5.4.2"
coverage = "5.1"
# linter and formatter
pre-commit = { version = "==2.4.0", markers = "implementation_name != 'pypy'" }
mypy = { version = "^0.770", markers = "implementation_name != 'pypy'" }
flake8-comprehensions = "==3.2.2"
flake8-bugbear = "==20.1.4"
flake8-mutable = "1.2.0"
yapf = "0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
