[tool.poetry]
name = "arcane-requests"
version = "0.1.1"
description = "Utility functions for requests"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"
backoff = "^1.10.0"
arcane-firebase = "0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
