name: Django Extra Checks CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e $(tox -a | grep $PYTHON_VERSION  | python -c "import sys;print(sys.stdin.read().strip().replace('\n', ' -e '))")
        env:
          PYTHON_VERSION: ${{ matrix.python }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e flake8 -e black -e isort -e manifest

  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.ref == 'refs/heads/master'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install twine
        run: pip install twine
      - name: Deploy
        run: echo 'placeholder'
