XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
        BBBB
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
        BBBBB

        BBB B BB BBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB BB B
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        BBBBBB

        BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBB
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB
    XXXXX
XXXXXX