[tool.poetry]
name = "slow-django"
version = "1.1.0"
description = "Django, but slower"
readme = "README.md"
homepage = "https://github.com/pbexe/slow-django"
repository = "https://github.com/pbexe/slow-django"
authors = ["pbexe"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
