# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Public/prog/python3/prettyetc/prettyetc/qtui/components/design/details.ui',
# licensing of '/home/Public/prog/python3/prettyetc/prettyetc/qtui/components/design/details.ui' applies.
#
# Created: Sun Sep 29 11:19:13 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_details(object):
    def setupUi(self, details):
        details.setObjectName("details")
        details.resize(480, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(details.sizePolicy().hasHeightForWidth())
        details.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        details.setFont(font)
        self.rootLayout = QtWidgets.QVBoxLayout(details)
        self.rootLayout.setObjectName("rootLayout")
        self.fieldname = QtWidgets.QLabel(details)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(50)
        font.setBold(False)
        self.fieldname.setFont(font)
        self.fieldname.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.fieldname.setObjectName("fieldname")
        self.rootLayout.addWidget(self.fieldname)
        self.details_container = QtWidgets.QWidget(details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_container.sizePolicy().hasHeightForWidth())
        self.details_container.setSizePolicy(sizePolicy)
        self.details_container.setObjectName("details_container")
        self.details_layout = QtWidgets.QGridLayout(self.details_container)
        self.details_layout.setContentsMargins(10, 20, 10, 1)
        self.details_layout.setVerticalSpacing(20)
        self.details_layout.setObjectName("details_layout")
        self.details_label_2 = QtWidgets.QLabel(self.details_container)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.details_label_2.setFont(font)
        self.details_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.details_label_2.setObjectName("details_label_2")
        self.details_layout.addWidget(self.details_label_2, 2, 0, 1, 1)
        self.field_attributes = QtWidgets.QTreeWidget(self.details_container)
        self.field_attributes.setObjectName("field_attributes")
        self.details_layout.addWidget(self.field_attributes, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.details_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.details_layout.addWidget(self.line, 1, 0, 1, 2)
        self.details_label_1 = QtWidgets.QLabel(self.details_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_label_1.sizePolicy().hasHeightForWidth())
        self.details_label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.details_label_1.setFont(font)
        self.details_label_1.setObjectName("details_label_1")
        self.details_layout.addWidget(self.details_label_1, 0, 0, 1, 1)
        self.field_description = QtWidgets.QLabel(self.details_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_description.sizePolicy().hasHeightForWidth())
        self.field_description.setSizePolicy(sizePolicy)
        self.field_description.setText("Some long description")
        self.field_description.setAlignment(QtCore.Qt.AlignCenter)
        self.field_description.setObjectName("field_description")
        self.details_layout.addWidget(self.field_description, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.details_layout.addItem(spacerItem, 3, 0, 1, 2)
        self.rootLayout.addWidget(self.details_container)

        self.retranslateUi(details)
        QtCore.QMetaObject.connectSlotsByName(details)

    def retranslateUi(self, details):
        details.setWindowTitle(QtWidgets.QApplication.translate("details", "Form", None, -1))
        self.fieldname.setText(QtWidgets.QApplication.translate("details", "Name", None, -1))
        self.details_label_2.setText(QtWidgets.QApplication.translate("details", "Attributes:", None, -1))
        self.field_attributes.headerItem().setText(0, QtWidgets.QApplication.translate("details", "name", None, -1))
        self.field_attributes.headerItem().setText(1, QtWidgets.QApplication.translate("details", "value", None, -1))
        self.details_label_1.setText(QtWidgets.QApplication.translate("details", "Description:", None, -1))

