[tool.poetry]
name = "bigbluebutton2"
version = "0.1.0dev1"
description = "Sophisticated Python client library for BigBlueButton™ with Django integration"
authors = ["Dominik George <dominik.george@teckids.org>", "Tom Teichler <tom.teichler@teckids.org"]
license = "MIT"
readme = "README.rst"
homepage = "https://infrablue.edugit.io"
repository = "https://edugit.org/infrablue/python-bigbluebutton2"
documentation = "https://infrablue.edugit.io/python-bigbluebutton2/docs/html/"
packages = [
    { include = "bigbluebutton" },
]
keywords = ["conference", "classroom", "audio", "video", "bigbluebutton"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX",
    "Topic :: Communications :: Conferencing",
    "Topic :: Education",
    "Topic :: Internet :: Proxy Servers",
    "Typing :: Typed",
]


[tool.poetry.dependencies]
python = "^3.6"
xmltodict = "^0.12.0"
inflection = "^0.4.0"
click = {version = "^7.1.1", optional = true}
toml = {version = "^0.10.0", optional = true}
tabulate = {version = "^0.8.7", optional = true}
requests = "^2.23.0"
click-log = "^0.3.2"
sadf = { version = "^0.1.2", optional = true }
django = {version = "^3.0.6", optional = true}
dicttoxml = {version = "^1.7.4", optional = true}
defusedxml = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-cov = "^2.9.0"
pytest-sugar = "^0.9.3"
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.8.2"
flake8-black = "^0.2.0"
flake8-mypy = "^17.8.0"
flake8-bandit = "^2.1.2"
flake8-isort = "^3.0.0"
flake8-builtins = "^1.5.3"
flake8-docstrings = "^1.5.0"
flake8-rst-docstrings = "^0.0.13"
safety = "^1.9.0"
sphinx = "^3.0.4"
sphinx-autodoc-typehints = "^1.10.3"
pytest-django = "^3.9.0"
sphinx_rtd_theme = "^0.4.3"
sphinxcontrib-django = "^0.5.1"

[tool.poetry.extras]
cli = ["click", "toml", "tabulate", "xdg"]
django = ["dicttoxml", "django"]
sysstat = ["sadf"]

[tool.poetry.scripts]
bbb-cli = "bigbluebutton.cli:bbb"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
