
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-01T21:52:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fa5114449ac5c62ae52a036235362e9a1981e3a",
 "version": "1.9.4.post.dev76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
