[tool.poetry]
name = "alacritty-colorscheme"
version = "0.1.0"
description = ""
authors = ["Safar Ligal <weathermist@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"ruamel.yaml" = "^0.16.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
alacritty-colorscheme = 'alacritty_colorscheme.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
