
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-06T16:05:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1264b3bee89ec3dd70cccba1158f598084a1f51e",
 "version": "v0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
