[tool.poetry]
name = "index.py"
version = "0.10.3"
description = "An easy-to-use asynchronous web framework based on ASGI."
authors = ["abersheeran <me@abersheeran.com>"]
license = "Apache-2.0"
homepage = "https://github.com/abersheeran/index.py"
repository = "https://github.com/abersheeran/index.py"
documentation = "https://index-py.abersheeran.com/"
classifiers=[
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
]
packages = [
    { include = "indexpy" },
]

[tool.poetry.scripts]
index-cli = "indexpy.cli:main"

[tool.poetry.dependencies]
python = "^3.6"
starlette = "^0.13.1"
gunicorn = "^20.0.4"
uvicorn = "^0.11.3"
a2wsgi = "^0.3.4"
aiofiles = "^0.5.0"
jinja2 = "^2.10.3"
python-multipart = "^0.0.5"
pyyaml = "^5.3"
pydantic = "^1.5"
watchdog = "^0.10.2"
contextvars = {version = "^2.4", python = "~3.6"}
requests = {version = "^2.23.0", optional = true}
pytest = {version = "^5.4.2", optional = true}

[tool.poetry.extras]
test = ["pytest", "requests"]

[tool.poetry.dev-dependencies]
mypy = "*"
flake8 = "*"
black = {version = "*", allow-prereleases = true}
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
pytest-asyncio = "^0.12"
django = "^3.0.2"
# only docs
mkdocs = "*"
mkdocs-material = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
