
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-04T00:56:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7b84a62fbc446e4d2087dced9b73447150d4ffd",
 "version": "1.10.0.post.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
