# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_container
from pulpcore.client.pulp_container.api.v2_blobs__api import V2BlobsApi  # noqa: E501
from pulpcore.client.pulp_container.rest import ApiException


class TestV2BlobsApi(unittest.TestCase):
    """V2BlobsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_container.api.v2_blobs__api.V2BlobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_partial_update(self):
        """Test case for partial_update

        Partially update an upload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
