# Generated by Django 3.0.6 on 2020-05-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corgy_accounts', '0002_snippet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='SnippetModel',
        ),
    ]
