[tool.poetry]
name = "opennem"
version = "0.1.0"
description = "opennem engine agent"
authors = ["Dylan McConnell <dylan.mcconnell@unimelb.edu.au>"]
license = "MIT"
include = [
  'scrapy.cfg'
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
pandas = "^1.0.4"
sqlalchemy = "^1.3.17"
mysqlclient = "^1.4.6"
pyyaml = "^5.3.1"
datadog = "^0.36.0"
python-dotenv = "^0.13.0"
sentry-sdk = "^0.14.4"
scrapy = "^2.1.0"
smart_open = "^2.0.0"
pydantic = "^1.5.1"
alembic = "^1.4.2"
twine = "^3.1.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "19.10b0"
flake8 = "^3.7.8"
isort = "^4.3.21"
pylint = "^2.2"
rope = "^0.16.0"
pylint-django = "^2.0.14"
ipython = "^7.13.0"
jupyter = "^1.0.0"
sqlacodegen = "^2.1.0"
pylint-sqlalchemy = "^0.2.0"

[tool.poetry.scripts]
bluestoned = 'opennem.cli:main'

[tool.black]
line-length = 79
target_version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |node_modules
  |_build
  |buck-out
  |build
  |dist
  |media
  |infrastructure
  |templates
  |locale
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
