# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/avs/messages/guid_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/avs/messages/guid_message.proto',
  package='avsoftware.avs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#src/avs/messages/guid_message.proto\x12\x0e\x61vsoftware.avs\"$\n\x04GUID\x12\r\n\x05upper\x18\x01 \x01(\x04\x12\r\n\x05lower\x18\x02 \x01(\x04\x62\x06proto3')
)




_GUID = _descriptor.Descriptor(
  name='GUID',
  full_name='avsoftware.avs.GUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upper', full_name='avsoftware.avs.GUID.upper', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lower', full_name='avsoftware.avs.GUID.lower', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['GUID'] = _GUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GUID = _reflection.GeneratedProtocolMessageType('GUID', (_message.Message,), dict(
  DESCRIPTOR = _GUID,
  __module__ = 'src.avs.messages.guid_message_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.avs.GUID)
  ))
_sym_db.RegisterMessage(GUID)


# @@protoc_insertion_point(module_scope)
