# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/avs/messages/mission.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.avs.messages import guid_message_pb2 as src_dot_avs_dot_messages_dot_guid__message__pb2
from FireSpark.protos.src.avs.messages import user_session_pb2 as src_dot_avs_dot_messages_dot_user__session__pb2
from FireSpark.protos.src.avs.messages import lyft_car_time_pb2 as src_dot_avs_dot_messages_dot_lyft__car__time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/avs/messages/mission.proto',
  package='avsoftware.avs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1esrc/avs/messages/mission.proto\x12\x0e\x61vsoftware.avs\x1a#src/avs/messages/guid_message.proto\x1a#src/avs/messages/user_session.proto\x1a$src/avs/messages/lyft_car_time.proto\"\xdb\x03\n\x07Mission\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.avsoftware.avs.GUID\x12\x10\n\x08jira_url\x18\x02 \x01(\t\x12\x0f\n\x07odd_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12(\n\nsession_id\x18\x05 \x01(\x0b\x32\x14.avsoftware.avs.GUID\x12\x15\n\ractivity_name\x18\x06 \x01(\t\x12\x0e\n\x06\x63\x61r_id\x18\x07 \x01(\t\x12\x33\n\x12mission_start_time\x18\x08 \x01(\x0b\x32\x17.avsoftware.LyftCarTime\x12\x32\n\x11mission_stop_time\x18\t \x01(\x0b\x32\x17.avsoftware.LyftCarTime\x12\x31\n\x0cuser_session\x18\n \x03(\x0b\x32\x1b.avsoftware.avs.UserSession\x12\x35\n\x0emission_status\x18\x0b \x01(\x0e\x32\x1d.avsoftware.avs.MissionStatus\x12\x31\n\x0cmission_type\x18\x0c \x01(\x0e\x32\x1b.avsoftware.avs.MissionType\x12\x1f\n\x17mission_message_counter\x18\r \x01(\x03*6\n\rMissionStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02*\xd4\x01\n\x0bMissionType\x12\x0b\n\x07NOT_SET\x10\x00\x12\t\n\x05SETUP\x10\x01\x12\x0f\n\x0bMDC_MAPPING\x10\x02\x12\x12\n\x0eMDC_PERCEPTION\x10\x03\x12\x18\n\x14\x41UTONOMY_DEVELOPMENT\x10\x04\x12\x14\n\x10\x41UTONOMY_RELEASE\x10\x05\x12\x13\n\x0f\x41UTONOMY_ACTIVE\x10\x06\x12\x13\n\x0fTROUBLESHOOTING\x10\x07\x12\t\n\x05\x42REAK\x10\x08\x12\t\n\x05OTHER\x10\t\x12\x18\n\x14\x41UTONOMY_EXPLORATORY\x10\nb\x06proto3')
  ,
  dependencies=[src_dot_avs_dot_messages_dot_guid__message__pb2.DESCRIPTOR,src_dot_avs_dot_messages_dot_user__session__pb2.DESCRIPTOR,src_dot_avs_dot_messages_dot_lyft__car__time__pb2.DESCRIPTOR,])

_MISSIONSTATUS = _descriptor.EnumDescriptor(
  name='MissionStatus',
  full_name='avsoftware.avs.MissionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=640,
  serialized_end=694,
)
_sym_db.RegisterEnumDescriptor(_MISSIONSTATUS)

MissionStatus = enum_type_wrapper.EnumTypeWrapper(_MISSIONSTATUS)
_MISSIONTYPE = _descriptor.EnumDescriptor(
  name='MissionType',
  full_name='avsoftware.avs.MissionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SETUP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDC_MAPPING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDC_PERCEPTION', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMY_DEVELOPMENT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMY_RELEASE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMY_ACTIVE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROUBLESHOOTING', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BREAK', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMY_EXPLORATORY', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=697,
  serialized_end=909,
)
_sym_db.RegisterEnumDescriptor(_MISSIONTYPE)

MissionType = enum_type_wrapper.EnumTypeWrapper(_MISSIONTYPE)
UNKNOWN = 0
ACTIVE = 1
INACTIVE = 2
NOT_SET = 0
SETUP = 1
MDC_MAPPING = 2
MDC_PERCEPTION = 3
AUTONOMY_DEVELOPMENT = 4
AUTONOMY_RELEASE = 5
AUTONOMY_ACTIVE = 6
TROUBLESHOOTING = 7
BREAK = 8
OTHER = 9
AUTONOMY_EXPLORATORY = 10



_MISSION = _descriptor.Descriptor(
  name='Mission',
  full_name='avsoftware.avs.Mission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='avsoftware.avs.Mission.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jira_url', full_name='avsoftware.avs.Mission.jira_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='odd_url', full_name='avsoftware.avs.Mission.odd_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='avsoftware.avs.Mission.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='avsoftware.avs.Mission.session_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_name', full_name='avsoftware.avs.Mission.activity_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_id', full_name='avsoftware.avs.Mission.car_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission_start_time', full_name='avsoftware.avs.Mission.mission_start_time', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission_stop_time', full_name='avsoftware.avs.Mission.mission_stop_time', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_session', full_name='avsoftware.avs.Mission.user_session', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission_status', full_name='avsoftware.avs.Mission.mission_status', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission_type', full_name='avsoftware.avs.Mission.mission_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission_message_counter', full_name='avsoftware.avs.Mission.mission_message_counter', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=638,
)

_MISSION.fields_by_name['id'].message_type = src_dot_avs_dot_messages_dot_guid__message__pb2._GUID
_MISSION.fields_by_name['session_id'].message_type = src_dot_avs_dot_messages_dot_guid__message__pb2._GUID
_MISSION.fields_by_name['mission_start_time'].message_type = src_dot_avs_dot_messages_dot_lyft__car__time__pb2._LYFTCARTIME
_MISSION.fields_by_name['mission_stop_time'].message_type = src_dot_avs_dot_messages_dot_lyft__car__time__pb2._LYFTCARTIME
_MISSION.fields_by_name['user_session'].message_type = src_dot_avs_dot_messages_dot_user__session__pb2._USERSESSION
_MISSION.fields_by_name['mission_status'].enum_type = _MISSIONSTATUS
_MISSION.fields_by_name['mission_type'].enum_type = _MISSIONTYPE
DESCRIPTOR.message_types_by_name['Mission'] = _MISSION
DESCRIPTOR.enum_types_by_name['MissionStatus'] = _MISSIONSTATUS
DESCRIPTOR.enum_types_by_name['MissionType'] = _MISSIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mission = _reflection.GeneratedProtocolMessageType('Mission', (_message.Message,), dict(
  DESCRIPTOR = _MISSION,
  __module__ = 'src.avs.messages.mission_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.avs.Mission)
  ))
_sym_db.RegisterMessage(Mission)


# @@protoc_insertion_point(module_scope)
