# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/avs/messages/perf_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/avs/messages/perf_message.proto',
  package='avsoftware.performance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#src/avs/messages/perf_message.proto\x12\x16\x61vsoftware.performance\"\x1e\n\x0bPerfMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x18\n\x08PerfDone\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x62\x06proto3')
)




_PERFMESSAGE = _descriptor.Descriptor(
  name='PerfMessage',
  full_name='avsoftware.performance.PerfMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='avsoftware.performance.PerfMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=93,
)


_PERFDONE = _descriptor.Descriptor(
  name='PerfDone',
  full_name='avsoftware.performance.PerfDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='avsoftware.performance.PerfDone.done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['PerfMessage'] = _PERFMESSAGE
DESCRIPTOR.message_types_by_name['PerfDone'] = _PERFDONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PerfMessage = _reflection.GeneratedProtocolMessageType('PerfMessage', (_message.Message,), dict(
  DESCRIPTOR = _PERFMESSAGE,
  __module__ = 'src.avs.messages.perf_message_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.performance.PerfMessage)
  ))
_sym_db.RegisterMessage(PerfMessage)

PerfDone = _reflection.GeneratedProtocolMessageType('PerfDone', (_message.Message,), dict(
  DESCRIPTOR = _PERFDONE,
  __module__ = 'src.avs.messages.perf_message_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.performance.PerfDone)
  ))
_sym_db.RegisterMessage(PerfDone)


# @@protoc_insertion_point(module_scope)
