[tool.poetry]
name = "SandsPythonFunctions"
version = "0.0.1a7"
description = "Functions I use regularly with my python projects"
authors = ["ldsands <ldsands@outlook.com>"]
repository = "https://github.com/ldsands/SandsPythonFunctions"
license = "MIT"
readme = "README.md"
packages = [
    { include = "SandsPythonFunctions", from = "src" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
# bs4 = "^0.0.1"
altair = "^4.1.0"
gensim = "^3.8.3"
nltk = "^3.5"
notebook = "^6.0.3"
pandas = "^1.0.3"
pyarrow = "^0.16.0"
pyemd = "^0.5.1"
python = "^3.8"
spacy = "^2.2"
wmd = "^1.3.2"
zstandard = "^0.13.0"
altair_saver = "^0.5.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.1"
pytest = "^5.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# [[tool.poetry.source]]
# name = "TestPyPI"
# url = "https://test.pypi.org/legacy/"
# default = true
