# Base Configuration file for artellapipe-tools-shadersmanager in Solstice

# Defines icon of the tool
icon: shadersmanager

# URL to tool documentation web page
help_url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/shadersmanager/