# Base Configuration file for artellapipe-tools-bugtracker in Solstice

# Defines icon of the tool
icon: alembic

# URL to tool documentation web page
help_url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/alembicmanager/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False