# Base Configuration for Artella Assets for Solstice

# Defines dictionary of asset types (Props, Characters, etc) used by the project
types:
  Props:
    class: solstice.assets.prop.SolsticeProp
    files:
      - textures
      - model
      - shading
      - shader
      - shaders
      - shadersmapping
      - rig
      - alembic
      - gpualembic
      - standin
  BackgroundElements:
    class: solstice.assets.backgroundelement.SolsticeBackgroundElement
    files:
      - textures
      - model
      - shading
      - shader
      - shaders
      - shadersmapping
      - rig
      - alembic
      - gpualembic
      - standin
  Characters:
    class: solstice.assets.character.SolsticeCharacter
    files:
      - textures
      - model
      - shading
      - shader
      - shaders
      - shadersmapping
      - rig
      - groom
      - alembic
      - gpualembic
      - standin
  Sets:
    class: solstice.assets.set.SolsticeSet
    files:
      - model

# Defines list of files that must be available to consider an asset published
must_file_types:
  - textures
  - model
  - shading
  - shaders
  - rig
  - gpualembic
  - standin

# Defines list of paths that should be ignored during asset searching
ignored_paths:
  - "PIPELINE"
  - "lighting"
  - "Light Rigs"
  - "S_CH_02_summer_scripts"