version: 1
disable_existing_loggers: true
formatters:
  standard:
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "[%(asctime)s] %(levelname)-7s | %(message)s"
  simple:
    datefmt: "%H:%M:%S"
    format: "[%(asctime)s] %(levelname)-7s | %(message)s"
  minimal:
    format: "%(levelname)-7s | %(message)s"
  message:
    format: "%(message)s"
handlers:
  main_log:
    level: WARNING
    formatter: standard
    class: logging.handlers.RotatingFileHandler
    filename: ~/.skcom/logs/skcom.log
  setup_log:
    level: DEBUG
    formatter: standard
    class: logging.handlers.RotatingFileHandler
    filename: ~/.skcom/logs/setup.log
  console:
    level: DEBUG
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  console_mini:
    level: INFO
    formatter: minimal
    class: logging.StreamHandler
    stream: ext://sys.stdout
  telegram:
    level: DEBUG
    formatter: message
    class: busm.BusmHandler
loggers:
  skcom:
    level: DEBUG
    handlers:
      - main_log
      - console
    propagate: yes
  helper:
    level: DEBUG
    handlers:
      - setup_log
      - console_mini
    propagate: yes
  bot:
    level: DEBUG
    handlers:
      # - telegram
      - console
    propagate: yes
