[tool.poetry]
name = "telegram-stats-bot"
version = "0.1.0"
description = "A logging and statistics bot for Telegram based on python-telegram-bot."
authors = ["Michael DM Dryden <mk.dryden@utoronto.ca>"]
license = "gpl-3.0-or-later"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
python-telegram-bot = "^12.7"
sqlalchemy = {version="^1.3.17", extras = ["postgresql_psycopg2binary"]}
pandas = "^1.0.4"
seaborn = "^0.10.1"
numpy = "^1.18.4"
matplotlib = "^3.2.1"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
