db:
    image: postgres:11
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
backend:
    build: backend
    ports:
        - "3001:3001"
    volumes:
        - ./backend:/code
    depends_on:
        - db
