[tool.poetry]
name = "smb_storage"
version = "0.1.0"
description = ""
authors = ["pat-rapidai <sheehan@rapid.ai>"]

[tool.poetry.dependencies]
python = "^2.7"
pysmb = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
