# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/backend/analytics/proto/pr_event_metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.backend.analytics.proto import field_custom_option_pb2 as src_dot_backend_dot_analytics_dot_proto_dot_field__custom__option__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/backend/analytics/proto/pr_event_metrics.proto',
  package='avsoftware.github_pr_metrics',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2src/backend/analytics/proto/pr_event_metrics.proto\x12\x1c\x61vsoftware.github_pr_metrics\x1a\x35src/backend/analytics/proto/field_custom_option.proto\"\'\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\\\n\x08Reviewer\x12\x30\n\x04user\x18\x01 \x01(\x0b\x32\".avsoftware.github_pr_metrics.User\x12\x1e\n\x16\x61ssignment_utc_seconds\x18\x02 \x01(\x03\">\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tadditions\x18\x02 \x01(\x05\x12\x11\n\tdeletions\x18\x03 \x01(\x05\"\xcd\x01\n\x06Status\x12\x1c\n\x0b\x64\x65scription\x18\x01 \x01(\tB\x07\x92\xa6\x1d\x03\x08\x80@\x12\x11\n\tmerged_by\x18\x02 \x01(\t\x12\x11\n\tadditions\x18\x03 \x01(\x05\x12\x11\n\tdeletions\x18\x04 \x01(\x05\x12\x39\n\treviewers\x18\x05 \x03(\x0b\x32&.avsoftware.github_pr_metrics.Reviewer\x12\x31\n\x05\x66iles\x18\x06 \x03(\x0b\x32\".avsoftware.github_pr_metrics.File\"R\n\x07\x43omment\x12\x30\n\x04user\x18\x01 \x01(\x0b\x32\".avsoftware.github_pr_metrics.User\x12\x15\n\x04\x62ody\x18\x02 \x01(\tB\x07\x92\xa6\x1d\x03\x08\x80@\"1\n\x0bPullRequest\x12\x12\n\nrepository\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\"\x84\x02\n\x05\x45vent\x12\x19\n\x11\x65vent_utc_seconds\x18\x01 \x01(\x03\x12\x35\n\x02pr\x18\x02 \x01(\x0b\x32).avsoftware.github_pr_metrics.PullRequest\x12;\n\nevent_type\x18\x03 \x01(\x0e\x32\'.avsoftware.github_pr_metrics.EventType\x12\x34\n\x06status\x18\x04 \x01(\x0b\x32$.avsoftware.github_pr_metrics.Status\x12\x36\n\x07\x63omment\x18\x05 \x01(\x0b\x32%.avsoftware.github_pr_metrics.Comment*^\n\tEventType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nPR_CREATED\x10\x01\x12\r\n\tPR_MERGED\x10\x02\x12\x12\n\x0eREVIEW_COMMENT\x10\x03\x12\x11\n\rISSUE_COMMENT\x10\x04\x62\x06proto3')
  ,
  dependencies=[src_dot_backend_dot_analytics_dot_proto_dot_field__custom__option__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='avsoftware.github_pr_metrics.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PR_CREATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PR_MERGED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVIEW_COMMENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISSUE_COMMENT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=944,
  serialized_end=1038,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
UNKNOWN = 0
PR_CREATED = 1
PR_MERGED = 2
REVIEW_COMMENT = 3
ISSUE_COMMENT = 4



_USER = _descriptor.Descriptor(
  name='User',
  full_name='avsoftware.github_pr_metrics.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='avsoftware.github_pr_metrics.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='avsoftware.github_pr_metrics.User.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=178,
)


_REVIEWER = _descriptor.Descriptor(
  name='Reviewer',
  full_name='avsoftware.github_pr_metrics.Reviewer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='avsoftware.github_pr_metrics.Reviewer.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assignment_utc_seconds', full_name='avsoftware.github_pr_metrics.Reviewer.assignment_utc_seconds', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=272,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='avsoftware.github_pr_metrics.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='avsoftware.github_pr_metrics.File.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additions', full_name='avsoftware.github_pr_metrics.File.additions', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletions', full_name='avsoftware.github_pr_metrics.File.deletions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=336,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='avsoftware.github_pr_metrics.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='avsoftware.github_pr_metrics.Status.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222\246\035\003\010\200@'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merged_by', full_name='avsoftware.github_pr_metrics.Status.merged_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additions', full_name='avsoftware.github_pr_metrics.Status.additions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletions', full_name='avsoftware.github_pr_metrics.Status.deletions', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviewers', full_name='avsoftware.github_pr_metrics.Status.reviewers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='avsoftware.github_pr_metrics.Status.files', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=544,
)


_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='avsoftware.github_pr_metrics.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='avsoftware.github_pr_metrics.Comment.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='avsoftware.github_pr_metrics.Comment.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222\246\035\003\010\200@'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=628,
)


_PULLREQUEST = _descriptor.Descriptor(
  name='PullRequest',
  full_name='avsoftware.github_pr_metrics.PullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository', full_name='avsoftware.github_pr_metrics.PullRequest.repository', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='avsoftware.github_pr_metrics.PullRequest.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=679,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='avsoftware.github_pr_metrics.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_utc_seconds', full_name='avsoftware.github_pr_metrics.Event.event_utc_seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pr', full_name='avsoftware.github_pr_metrics.Event.pr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='avsoftware.github_pr_metrics.Event.event_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='avsoftware.github_pr_metrics.Event.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='avsoftware.github_pr_metrics.Event.comment', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=942,
)

_REVIEWER.fields_by_name['user'].message_type = _USER
_STATUS.fields_by_name['reviewers'].message_type = _REVIEWER
_STATUS.fields_by_name['files'].message_type = _FILE
_COMMENT.fields_by_name['user'].message_type = _USER
_EVENT.fields_by_name['pr'].message_type = _PULLREQUEST
_EVENT.fields_by_name['event_type'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['status'].message_type = _STATUS
_EVENT.fields_by_name['comment'].message_type = _COMMENT
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Reviewer'] = _REVIEWER
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Comment'] = _COMMENT
DESCRIPTOR.message_types_by_name['PullRequest'] = _PULLREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.User)
  ))
_sym_db.RegisterMessage(User)

Reviewer = _reflection.GeneratedProtocolMessageType('Reviewer', (_message.Message,), dict(
  DESCRIPTOR = _REVIEWER,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.Reviewer)
  ))
_sym_db.RegisterMessage(Reviewer)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.File)
  ))
_sym_db.RegisterMessage(File)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.Status)
  ))
_sym_db.RegisterMessage(Status)

Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
  DESCRIPTOR = _COMMENT,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.Comment)
  ))
_sym_db.RegisterMessage(Comment)

PullRequest = _reflection.GeneratedProtocolMessageType('PullRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLREQUEST,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.PullRequest)
  ))
_sym_db.RegisterMessage(PullRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'src.backend.analytics.proto.pr_event_metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.github_pr_metrics.Event)
  ))
_sym_db.RegisterMessage(Event)


_STATUS.fields_by_name['description']._options = None
_COMMENT.fields_by_name['body']._options = None
# @@protoc_insertion_point(module_scope)
