# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/directory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/directory.proto',
  package='bosdyn.api',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x62osdyn/api/directory.proto\x12\nbosdyn.api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n\x0cServiceEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tauthority\x18\x03 \x01(\t\x12/\n\x0blast_update\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13user_token_required\x18\x05 \x01(\x08\x12\"\n\x1a\x61pplication_token_required\x18\x06 \x01(\x08\x12\x1b\n\x13permission_required\x18\x07 \x01(\tB\x10\x42\x0e\x44irectoryProtob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SERVICEENTRY = _descriptor.Descriptor(
  name='ServiceEntry',
  full_name='bosdyn.api.ServiceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.ServiceEntry.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='bosdyn.api.ServiceEntry.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authority', full_name='bosdyn.api.ServiceEntry.authority', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_update', full_name='bosdyn.api.ServiceEntry.last_update', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_token_required', full_name='bosdyn.api.ServiceEntry.user_token_required', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='application_token_required', full_name='bosdyn.api.ServiceEntry.application_token_required', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='permission_required', full_name='bosdyn.api.ServiceEntry.permission_required', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=280,
)

_SERVICEENTRY.fields_by_name['last_update'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ServiceEntry'] = _SERVICEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceEntry = _reflection.GeneratedProtocolMessageType('ServiceEntry', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEENTRY,
  __module__ = 'bosdyn.api.directory_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.ServiceEntry)
  ))
_sym_db.RegisterMessage(ServiceEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\016DirectoryProto'))
# @@protoc_insertion_point(module_scope)
