[tool.poetry]
name = "berhoelODF"
version = "0.2.2"
description = "Lightweight and limited access to odf files using lxml."

packages = [
    { include = "berhoel" },
]
exclude=["**/.#*.py", "**/#*.py#"]

authors = ["Berthold Höllmann <berthold-gitlab@xn--hllmanns-n4a.de>"]
license = "MIT"

repository = "https://gitlab.com/berhoel/python/berhoelodf.git"
homepage = "https://python.xn--hllmanns-n4a.de/berhoelodf/"
documentation = "https://www.höllmanns.de/python/berhoelODF/"
readme = "README.rst"

classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.5.0"
pdoc3 = "^0.8.1"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tox = "^3.15.1"
pdbpp = "^0.10.2"
Sphinx = "^3.0.4"
sphinx-rtd-theme = "^0.4.3"
blacker = "^0.1.0"
flake8 = "^3.8.2"
pylint = "^2.5.2"
rope = "^0.17.0"
numpydoc = "^1.0.0"

[tool.isort]
multi_line_output = 5
include_trailing_comma = true
use_parentheses = true
indent = '    '
length_sort = true
line_length = 88
use_parantheses = true
balanced_wrapping = true
import_heading_stdlib = 'Standard libraries.'
import_heading_thirdparty = 'Third party libraries.'
known_first_party = ['berhoel']

[flake8]
max-line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
