# This file is part of CoVeriTeam, a tool for on-demand composition of cooperative verification systems:
# https://gitlab.com/sosy-lab/software/coveriteam
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

actor_name: test-goal-extractor
toolinfo_module: "condtest-extractor.py"
archive:
  location: "https://gitlab.com/sosy-lab/software/conditional-testing/-/archive/v3.0/conditional-testing-v3.0.zip"
options: []
resourcelimits:
  memlimit: "15 GB"
  timelimit: "15 min"
  cpuCores: "8"
format_version: '1.1'
