
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-10T11:53:04+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a1e61bf03c2619b5bdfd43ccdf54f3cb80a59c9",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
