[tool.poetry]
name = "aiohttp-rpc"
version = "0.1.0"
description = ""
authors = ["expert-m <michael@sulyak.info>"]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
tox = "^3.15.1"
pytest-asyncio = "^0.12.0"
pytest-aiohttp = "^0.3.0"
pytest-mock = "^3.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
