[tool.poetry]
name = "piaf"
version = "0.1a1"
description = "A FIPA-compliant Agent Platform written in python."
authors = ["Pierre DUBAILLAY <pierredubaillay@outlook.fr>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/ornythorinque/piaf"
keywords = ["Python Agent Framework", "multi-agent", "asyncio"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
sphinx = "^3"
sphinx_rtd_theme = "^0.4.3"
mypy = "^0"
pydocstyle = "^5"
black = {version = "^19.10b0", allow-prereleases = true}
flake8 = "^3.7.9"
coverage = {version = "^5.1", extras = ["toml"]}
rstcheck = "^3.3.1"

[tool.coverage.run]
branch = true
data_file = ".report/coverage/data_db"
source = ["piaf"]
omit = ["*/examples/*"]
command_line = "-m pytest"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError()",
    "if __name__ == \"__main__\"",
    "if TYPE_CHECKING:"
]
fail_under = 80

[tool.coverage.html]
directory = ".report/coverage/html"

[tool.coverage.xml]
output = ".report/coverage/xml/coverage.xml"

[tool.coverage.json]
output = ".report/coverage/json/coverage.json"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
