# A sample configuration for fedora-messaging. This file is in the TOML format.
# For complete details on all configuration options, see the documentation.

amqp_url = "amqp://"

publish_exchange = "amq.topic"

callback = "robosignatory.consumer:Consumer"

# The topic_prefix configuration value will add a prefix to the topics of every sent message.
# This is used for migrating from fedmsg, and should not be used afterwards.
topic_prefix = "org.fedoraproject.dev"

# Note the double brackets below.
# To add another binding, add another [[bindings]] section.
[[bindings]]
queue = "robosignatory"
exchange = "amq.topic"
routing_keys = [
    "org.fedoraproject.*.pungi.compose.ostree",
    "org.fedoraproject.*.coreos.build.request.artifacts-sign",
    "org.fedoraproject.*.coreos.build.request.ostree-sign",
    "org.fedoraproject.*.buildsys.tag",
]

[[bindings]]
queue = "robosignatory"
exchange = "zmq.topic"
routing_keys = [
    "org.fedoraproject.*.pungi.compose.ostree",
]

[tls]
ca_cert = "/etc/pki/tls/certs/ca-bundle.crt"
keyfile = "/my/client/key.pem"
certfile = "/my/client/cert.pem"

[client_properties]
app = "RoboSignatory"

[queues.robosignatory]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.robosignatory]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "INFO"
handlers = ["console"]


# robosignatory consumer configuration
[consumer_config]

    [consumer_config.signing]
    # This should be the name of an entrypoint plugin that provides
    # SigningHelper functionality.
    backend = "sigul"
    # These are arguments to the __init__ method of that helper.
    user = "robosignatory"
    passphrase_file = "robosignatory.pass"
    config_file = "/etc/sigul/client.conf"

    [consumer_config.koji_instances]
    # The keys here need to be the same in the sigul bridge
        [consumer_config.koji_instances.primary]
        url = 'http://koji.fedoraproject.org/kojihub'
        mbs_user = 'mbs/mbs.example.com'

            [consumer_config.koji_instances.primary.options]
            # Only ssl and kerberos are supported at the moment
            authmethod = 'ssl'
            cert = 'robosignatory.cert'
            serverca = 'servcer-ca.cert'

            [[consumer_config.koji_instances.primary.tags]]
            from = 'rawhide-signcandidate'
            to = 'rawhide'
            key = 'fedora26'
            keyid = 'xxxxxxxx'

                [consumer_config.koji_instances.primary.tags.sidetags]
                pattern = '<to>-build-side-<seq_id>'
                from = '<sidetag>-pending-signing'
                to = '<sidetag>-testing'
                trusted_taggers = ['bodhi']

            [[consumer_config.koji_instances.primary.tags]]
            from = 'rawhide-modular-signcandidate'
            to = 'rawhide-modular'
            key = 'fedora26'
            keyid = 'xxxxxxxx'
            type = 'modular'

    [consumer_config.ostree_refs]
        [consumer_config.ostree_refs."fedora-atomic/25/x86_64/docker-host"]
        directory = '/mnt/koji/compose/atomic/25/'
        key = 'fedora-25'

    [consumer_config.coreos]
    bucket = "robosig-dev-fcos-builds"
    # Only set key if you want to override key detection that detects
    # which key to use based on FCOS version numbers.
    key = "coreos"

        [consumer_config.coreos.aws]
        access_key = "ACCESS_KEY"
        access_secret = "SECRET"
        region = "us-east-1"
