[tool.poetry]
name = "time-int"
version = "0.0.1"
description = "Subclass of integer representing seconds since UNIX epoch"
authors = ["Andrew Allaire <andrew.allaire@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^5.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
