[tool.poetry]
name = "sardine"
version = "0.0.0b3"
description = "Manage your docker-composes as if they were snipets"
authors = ["Javier Luna molina <javierlunamolina@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
GitPython = "^3.1.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.1"
mypy = "^0.770"
mkdocs = "^1.1.2"

[tool.poetry.scripts]
sardine = "sardine.cli.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
