# AUTOGENERATED! DO NOT EDIT! File to edit: 02_predictive_analysis.ipynb (unless otherwise specified).

__all__ = ['predicter']

# Cell
from newstrends import loader,

# Cell
class predicter:

    def __init__(self):
        self.loaded=False
        self.articleDir = ""


    def test():return True