[tool]
[tool.poetry]
name = "django-concurrency"
version = "2.1a0"
description = "Optimistic lock implementation for Django. Prevents users from doing concurrent editing."
license = "MIT License"
keywords = ["django", "concurrency", "optimistic", "lock", "locking", "concurrent", "editing"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Programming Language :: Python", "Framework :: Django :: 1.11", "Framework :: Django :: 2.1", "Framework :: Django :: 2.2", "Framework :: Django :: 3.0", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Topic :: Software Development :: Libraries :: Application Frameworks", "Topic :: Software Development :: Libraries :: Python Modules"]
authors = ["Stefano Apostolico <s.apostolico@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/saxix/django-concurrency"

[tool.poetry.dependencies]
python = ">=3.5"

[tool.poetry.dev-dependencies]
pytest = ">=5.3"
pre-commit = "^1.21.0"
isort = "^4.3.21"
django-webtest = "^1.9.7"
pytest-cov = "^2.8.1"
pytest-django = "^3.7.0"
pytest-echo = "^1.7.1"
pytest-pythonpath = "^0.7.3"
check-manifest = "^0.40"
sphinx = "^2.3.1"
