XXXXXXX
XXXX XXXX XXXXXXXXX XXX
BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX
        BB BBBBBBBBBBBBB
            XXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXX XXX
            XXXX XXXXXXX
        BBBBB
        XXXX XXXX X XXX
        FFFF
        XXXX XXXX X XXX
        FFFF
    XXXX
BBBBBB
XXXX XXXX XXXXXX XXX
BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX
        XX XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXX XXXXXX XXX
                XXXX XXXXXXX
            BBBB
                XXXX XXXXXXXXX XXXX XXX XXXXXXXXX
                
            BBBBB
        XXXX
    XXXX
BBBBBB