
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-08T09:18:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "48a7d6e6085034a0cbd1001b802c52a855fbfc3a",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
