[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "hor2vec"
author = "Frank Jheng"
author-email = "m157q.tw@gmail.com"
home-page = "https://github.com/M157q/hor2vec"
description-file="README.md"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

[tool.flit.scripts]
hor2vec = "hor2vec.__main__:main"
