# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/sensor/lidar/proto/lidar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.avs.messages import lyft_car_time_pb2 as src_dot_avs_dot_messages_dot_lyft__car__time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/sensor/lidar/proto/lidar.proto',
  package='avsoftware.sensor.lidar.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"src/sensor/lidar/proto/lidar.proto\x12\x1d\x61vsoftware.sensor.lidar.proto\x1a$src/avs/messages/lyft_car_time.proto\"_\n\x0bLidarPacket\x12;\n\x1a\x66irst_firing_lyft_car_time\x18\x01 \x01(\x0b\x32\x17.avsoftware.LyftCarTime\x12\x13\n\x0b\x64\x61ta_packet\x18\x02 \x01(\x0c\">\n\x10PandarCorrection\x12\x15\n\relevation_deg\x18\x01 \x01(\x02\x12\x13\n\x0b\x61zimuth_deg\x18\x02 \x01(\x02\"\xe6\x03\n\x0fLidarPacketList\x12L\n\nlidar_type\x18\x01 \x01(\x0e\x32\x38.avsoftware.sensor.lidar.proto.LidarPacketList.LidarType\x12@\n\x0clidar_packet\x18\x02 \x03(\x0b\x32*.avsoftware.sensor.lidar.proto.LidarPacket\x12J\n\x11pandar_correction\x18\x03 \x03(\x0b\x32/.avsoftware.sensor.lidar.proto.PandarCorrection\"\xf6\x01\n\tLidarType\x12\x16\n\x12LIDAR_TYPE_NOT_SET\x10\x00\x12\x18\n\x14LIDAR_TYPE_PANDAR_40\x10\x01\x12\x19\n\x15LIDAR_TYPE_PANDAR_40P\x10\x02\x12\x19\n\x15LIDAR_TYPE_OUSTER_OS1\x10\x03\x12&\n\x1eLIDAR_TYPE_PANDAR_40P_CCW_ONLY\x10\x04\x1a\x02\x08\x01\x12\x1d\n\x19LIDAR_TYPE_PANDAR_40P_CCW\x10\x05\x12\x1b\n\x17LIDAR_TYPE_PANDAR_64_CW\x10\x06\x12\x1d\n\x19LIDAR_TYPE_VELODYNE_VLP16\x10\x07\x62\x06proto3')
  ,
  dependencies=[src_dot_avs_dot_messages_dot_lyft__car__time__pb2.DESCRIPTOR,])



_LIDARPACKETLIST_LIDARTYPE = _descriptor.EnumDescriptor(
  name='LidarType',
  full_name='avsoftware.sensor.lidar.proto.LidarPacketList.LidarType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_NOT_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_PANDAR_40', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_PANDAR_40P', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_OUSTER_OS1', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_PANDAR_40P_CCW_ONLY', index=4, number=4,
      serialized_options=_b('\010\001'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_PANDAR_40P_CCW', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_PANDAR_64_CW', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_TYPE_VELODYNE_VLP16', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=509,
  serialized_end=755,
)
_sym_db.RegisterEnumDescriptor(_LIDARPACKETLIST_LIDARTYPE)


_LIDARPACKET = _descriptor.Descriptor(
  name='LidarPacket',
  full_name='avsoftware.sensor.lidar.proto.LidarPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_firing_lyft_car_time', full_name='avsoftware.sensor.lidar.proto.LidarPacket.first_firing_lyft_car_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_packet', full_name='avsoftware.sensor.lidar.proto.LidarPacket.data_packet', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=202,
)


_PANDARCORRECTION = _descriptor.Descriptor(
  name='PandarCorrection',
  full_name='avsoftware.sensor.lidar.proto.PandarCorrection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elevation_deg', full_name='avsoftware.sensor.lidar.proto.PandarCorrection.elevation_deg', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='azimuth_deg', full_name='avsoftware.sensor.lidar.proto.PandarCorrection.azimuth_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=266,
)


_LIDARPACKETLIST = _descriptor.Descriptor(
  name='LidarPacketList',
  full_name='avsoftware.sensor.lidar.proto.LidarPacketList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lidar_type', full_name='avsoftware.sensor.lidar.proto.LidarPacketList.lidar_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lidar_packet', full_name='avsoftware.sensor.lidar.proto.LidarPacketList.lidar_packet', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pandar_correction', full_name='avsoftware.sensor.lidar.proto.LidarPacketList.pandar_correction', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIDARPACKETLIST_LIDARTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=755,
)

_LIDARPACKET.fields_by_name['first_firing_lyft_car_time'].message_type = src_dot_avs_dot_messages_dot_lyft__car__time__pb2._LYFTCARTIME
_LIDARPACKETLIST.fields_by_name['lidar_type'].enum_type = _LIDARPACKETLIST_LIDARTYPE
_LIDARPACKETLIST.fields_by_name['lidar_packet'].message_type = _LIDARPACKET
_LIDARPACKETLIST.fields_by_name['pandar_correction'].message_type = _PANDARCORRECTION
_LIDARPACKETLIST_LIDARTYPE.containing_type = _LIDARPACKETLIST
DESCRIPTOR.message_types_by_name['LidarPacket'] = _LIDARPACKET
DESCRIPTOR.message_types_by_name['PandarCorrection'] = _PANDARCORRECTION
DESCRIPTOR.message_types_by_name['LidarPacketList'] = _LIDARPACKETLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarPacket = _reflection.GeneratedProtocolMessageType('LidarPacket', (_message.Message,), dict(
  DESCRIPTOR = _LIDARPACKET,
  __module__ = 'src.sensor.lidar.proto.lidar_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.sensor.lidar.proto.LidarPacket)
  ))
_sym_db.RegisterMessage(LidarPacket)

PandarCorrection = _reflection.GeneratedProtocolMessageType('PandarCorrection', (_message.Message,), dict(
  DESCRIPTOR = _PANDARCORRECTION,
  __module__ = 'src.sensor.lidar.proto.lidar_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.sensor.lidar.proto.PandarCorrection)
  ))
_sym_db.RegisterMessage(PandarCorrection)

LidarPacketList = _reflection.GeneratedProtocolMessageType('LidarPacketList', (_message.Message,), dict(
  DESCRIPTOR = _LIDARPACKETLIST,
  __module__ = 'src.sensor.lidar.proto.lidar_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.sensor.lidar.proto.LidarPacketList)
  ))
_sym_db.RegisterMessage(LidarPacketList)


_LIDARPACKETLIST_LIDARTYPE.values_by_name["LIDAR_TYPE_PANDAR_40P_CCW_ONLY"]._options = None
# @@protoc_insertion_point(module_scope)
