
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-09T12:51:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0c81eb2c2efd0691c1443e78592c627aa31193f",
 "version": "0.3.0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
