# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/localization/proto/metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.slam.metrics.proto import metrics_pb2 as src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/localization/proto/metrics.proto',
  package='avsoftware.localization',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$src/localization/proto/metrics.proto\x12\x17\x61vsoftware.localization\x1a$src/slam/metrics/proto/metrics.proto\"1\n\x11LocalizationDebug\x12\x1c\n\x14localization_delay_s\x18\x01 \x01(\x01\"\xc5\x02\n\x07Metrics\x12\x0f\n\x07git_sha\x18\x01 \x01(\t\x12\x14\n\x0cgit_sha_date\x18\x02 \x01(\t\x12%\n\x05input\x18\x03 \x01(\x0b\x32\x16.avsoftware.slam.Input\x12\'\n\x06geomap\x18\x04 \x01(\x0b\x32\x17.avsoftware.slam.Geomap\x12\x1b\n\x13time_to_localize_ms\x18\x05 \x01(\x03\x12\x1a\n\x12localization_ratio\x18\x06 \x01(\x02\x12(\n\x07metrics\x18\x07 \x03(\x0b\x32\x17.avsoftware.slam.Metric\x12\x44\n\x16meters_per_large_error\x18\x0b \x01(\x0b\x32$.avsoftware.slam.MetersPerLargeError\x12\x0c\n\x04\x61rgs\x18\x08 \x03(\t\x12\x0c\n\x04tags\x18\t \x03(\tb\x06proto3')
  ,
  dependencies=[src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2.DESCRIPTOR,])




_LOCALIZATIONDEBUG = _descriptor.Descriptor(
  name='LocalizationDebug',
  full_name='avsoftware.localization.LocalizationDebug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localization_delay_s', full_name='avsoftware.localization.LocalizationDebug.localization_delay_s', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=152,
)


_METRICS = _descriptor.Descriptor(
  name='Metrics',
  full_name='avsoftware.localization.Metrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_sha', full_name='avsoftware.localization.Metrics.git_sha', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_sha_date', full_name='avsoftware.localization.Metrics.git_sha_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='avsoftware.localization.Metrics.input', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geomap', full_name='avsoftware.localization.Metrics.geomap', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_to_localize_ms', full_name='avsoftware.localization.Metrics.time_to_localize_ms', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='localization_ratio', full_name='avsoftware.localization.Metrics.localization_ratio', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='avsoftware.localization.Metrics.metrics', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meters_per_large_error', full_name='avsoftware.localization.Metrics.meters_per_large_error', index=7,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='avsoftware.localization.Metrics.args', index=8,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='avsoftware.localization.Metrics.tags', index=9,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=480,
)

_METRICS.fields_by_name['input'].message_type = src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2._INPUT
_METRICS.fields_by_name['geomap'].message_type = src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2._GEOMAP
_METRICS.fields_by_name['metrics'].message_type = src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2._METRIC
_METRICS.fields_by_name['meters_per_large_error'].message_type = src_dot_slam_dot_metrics_dot_proto_dot_metrics__pb2._METERSPERLARGEERROR
DESCRIPTOR.message_types_by_name['LocalizationDebug'] = _LOCALIZATIONDEBUG
DESCRIPTOR.message_types_by_name['Metrics'] = _METRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocalizationDebug = _reflection.GeneratedProtocolMessageType('LocalizationDebug', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZATIONDEBUG,
  __module__ = 'src.localization.proto.metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.localization.LocalizationDebug)
  ))
_sym_db.RegisterMessage(LocalizationDebug)

Metrics = _reflection.GeneratedProtocolMessageType('Metrics', (_message.Message,), dict(
  DESCRIPTOR = _METRICS,
  __module__ = 'src.localization.proto.metrics_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.localization.Metrics)
  ))
_sym_db.RegisterMessage(Metrics)


# @@protoc_insertion_point(module_scope)
