# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric6/Plugins/CheckerPlugins/CodeStyleChecker/CodeStyleCheckerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeStyleCheckerDialog(object):
    def setupUi(self, CodeStyleCheckerDialog):
        CodeStyleCheckerDialog.setObjectName("CodeStyleCheckerDialog")
        CodeStyleCheckerDialog.resize(800, 700)
        CodeStyleCheckerDialog.setSizeGripEnabled(True)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(CodeStyleCheckerDialog)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mainWidget = QtWidgets.QTabWidget(CodeStyleCheckerDialog)
        self.mainWidget.setObjectName("mainWidget")
        self.configureTab = QtWidgets.QWidget()
        self.configureTab.setObjectName("configureTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.configureTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.optionsTabWidget = QtWidgets.QTabWidget(self.configureTab)
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.globalOptionsTab = QtWidgets.QWidget()
        self.globalOptionsTab.setObjectName("globalOptionsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.globalOptionsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.globalOptionsTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.excludeFilesEdit = E5ClearableLineEdit(self.globalOptionsTab)
        self.excludeFilesEdit.setObjectName("excludeFilesEdit")
        self.gridLayout_2.addWidget(self.excludeFilesEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.globalOptionsTab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.excludeMessagesEdit = E5ClearableLineEdit(self.globalOptionsTab)
        self.excludeMessagesEdit.setObjectName("excludeMessagesEdit")
        self.gridLayout_2.addWidget(self.excludeMessagesEdit, 1, 1, 1, 1)
        self.excludeMessagesSelectButton = QtWidgets.QToolButton(self.globalOptionsTab)
        self.excludeMessagesSelectButton.setObjectName("excludeMessagesSelectButton")
        self.gridLayout_2.addWidget(self.excludeMessagesSelectButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.globalOptionsTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.includeMessagesEdit = E5ClearableLineEdit(self.globalOptionsTab)
        self.includeMessagesEdit.setObjectName("includeMessagesEdit")
        self.gridLayout_2.addWidget(self.includeMessagesEdit, 2, 1, 1, 1)
        self.includeMessagesSelectButton = QtWidgets.QToolButton(self.globalOptionsTab)
        self.includeMessagesSelectButton.setObjectName("includeMessagesSelectButton")
        self.gridLayout_2.addWidget(self.includeMessagesSelectButton, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.globalOptionsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.fixIssuesEdit = E5ClearableLineEdit(self.globalOptionsTab)
        self.fixIssuesEdit.setObjectName("fixIssuesEdit")
        self.gridLayout_2.addWidget(self.fixIssuesEdit, 3, 1, 1, 1)
        self.fixIssuesSelectButton = QtWidgets.QToolButton(self.globalOptionsTab)
        self.fixIssuesSelectButton.setObjectName("fixIssuesSelectButton")
        self.gridLayout_2.addWidget(self.fixIssuesSelectButton, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.globalOptionsTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.noFixIssuesEdit = E5ClearableLineEdit(self.globalOptionsTab)
        self.noFixIssuesEdit.setObjectName("noFixIssuesEdit")
        self.gridLayout_2.addWidget(self.noFixIssuesEdit, 4, 1, 1, 1)
        self.noFixIssuesSelectButton = QtWidgets.QToolButton(self.globalOptionsTab)
        self.noFixIssuesSelectButton.setObjectName("noFixIssuesSelectButton")
        self.gridLayout_2.addWidget(self.noFixIssuesSelectButton, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repeatCheckBox = QtWidgets.QCheckBox(self.globalOptionsTab)
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.horizontalLayout.addWidget(self.repeatCheckBox)
        self.fixIssuesCheckBox = QtWidgets.QCheckBox(self.globalOptionsTab)
        self.fixIssuesCheckBox.setEnabled(False)
        self.fixIssuesCheckBox.setObjectName("fixIssuesCheckBox")
        self.horizontalLayout.addWidget(self.fixIssuesCheckBox)
        self.ignoredCheckBox = QtWidgets.QCheckBox(self.globalOptionsTab)
        self.ignoredCheckBox.setEnabled(False)
        self.ignoredCheckBox.setObjectName("ignoredCheckBox")
        self.horizontalLayout.addWidget(self.ignoredCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 2)
        self.optionsTabWidget.addTab(self.globalOptionsTab, "")
        self.specificOptionsTab = QtWidgets.QWidget()
        self.specificOptionsTab.setObjectName("specificOptionsTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.specificOptionsTab)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.specificOptionsTab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 1102))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineLengthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.lineLengthSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineLengthSpinBox.setMinimum(60)
        self.lineLengthSpinBox.setMaximum(119)
        self.lineLengthSpinBox.setProperty("value", 79)
        self.lineLengthSpinBox.setObjectName("lineLengthSpinBox")
        self.gridLayout_5.addWidget(self.lineLengthSpinBox, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.docLineLengthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.docLineLengthSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.docLineLengthSpinBox.setMinimum(60)
        self.docLineLengthSpinBox.setMaximum(119)
        self.docLineLengthSpinBox.setProperty("value", 79)
        self.docLineLengthSpinBox.setObjectName("docLineLengthSpinBox")
        self.gridLayout_5.addWidget(self.docLineLengthSpinBox, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.blankBeforeTopLevelSpinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.blankBeforeTopLevelSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blankBeforeTopLevelSpinBox.setMinimum(1)
        self.blankBeforeTopLevelSpinBox.setMaximum(10)
        self.blankBeforeTopLevelSpinBox.setProperty("value", 2)
        self.blankBeforeTopLevelSpinBox.setObjectName("blankBeforeTopLevelSpinBox")
        self.gridLayout_3.addWidget(self.blankBeforeTopLevelSpinBox, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.blankBeforeMethodSpinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.blankBeforeMethodSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blankBeforeMethodSpinBox.setMinimum(1)
        self.blankBeforeMethodSpinBox.setMaximum(10)
        self.blankBeforeMethodSpinBox.setProperty("value", 1)
        self.blankBeforeMethodSpinBox.setObjectName("blankBeforeMethodSpinBox")
        self.gridLayout_3.addWidget(self.blankBeforeMethodSpinBox, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.hangClosingCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.hangClosingCheckBox.setObjectName("hangClosingCheckBox")
        self.verticalLayout_2.addWidget(self.hangClosingCheckBox)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.docTypeComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.docTypeComboBox.setObjectName("docTypeComboBox")
        self.horizontalLayout_3.addWidget(self.docTypeComboBox)
        spacerItem4 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.encodingsEdit = E5ClearableLineEdit(self.groupBox_4)
        self.encodingsEdit.setObjectName("encodingsEdit")
        self.horizontalLayout_6.addWidget(self.encodingsEdit)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.copyrightFileSizeSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.copyrightFileSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyrightFileSizeSpinBox.setMaximum(4096)
        self.copyrightFileSizeSpinBox.setObjectName("copyrightFileSizeSpinBox")
        self.gridLayout.addWidget(self.copyrightFileSizeSpinBox, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(324, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.copyrightAuthorEdit = E5ClearableLineEdit(self.groupBox_5)
        self.copyrightAuthorEdit.setObjectName("copyrightAuthorEdit")
        self.gridLayout.addWidget(self.copyrightAuthorEdit, 1, 1, 1, 2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.futuresList = QtWidgets.QListWidget(self.groupBox_6)
        self.futuresList.setAlternatingRowColors(True)
        self.futuresList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.futuresList.setObjectName("futuresList")
        self.horizontalLayout_7.addWidget(self.futuresList)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.builtinsAssignmentList = QtWidgets.QTreeWidget(self.groupBox_7)
        self.builtinsAssignmentList.setAlternatingRowColors(True)
        self.builtinsAssignmentList.setRootIsDecorated(False)
        self.builtinsAssignmentList.setObjectName("builtinsAssignmentList")
        self.horizontalLayout_8.addWidget(self.builtinsAssignmentList)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addBuiltinButton = QtWidgets.QToolButton(self.groupBox_7)
        self.addBuiltinButton.setText("+")
        self.addBuiltinButton.setObjectName("addBuiltinButton")
        self.verticalLayout_5.addWidget(self.addBuiltinButton, 0, QtCore.Qt.AlignHCenter)
        self.deleteBuiltinButton = QtWidgets.QToolButton(self.groupBox_7)
        self.deleteBuiltinButton.setText("-")
        self.deleteBuiltinButton.setObjectName("deleteBuiltinButton")
        self.verticalLayout_5.addWidget(self.deleteBuiltinButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.aggressiveCheckBox = QtWidgets.QCheckBox(self.groupBox_9)
        self.aggressiveCheckBox.setObjectName("aggressiveCheckBox")
        self.verticalLayout_3.addWidget(self.aggressiveCheckBox)
        self.verticalLayout_6.addWidget(self.groupBox_9)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(313, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 2, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.complexitySpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.complexitySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.complexitySpinBox.setMaximum(100)
        self.complexitySpinBox.setProperty("value", 10)
        self.complexitySpinBox.setObjectName("complexitySpinBox")
        self.gridLayout_4.addWidget(self.complexitySpinBox, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineComplexitySpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.lineComplexitySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineComplexitySpinBox.setMaximum(100)
        self.lineComplexitySpinBox.setProperty("value", 15)
        self.lineComplexitySpinBox.setObjectName("lineComplexitySpinBox")
        self.gridLayout_4.addWidget(self.lineComplexitySpinBox, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineComplexityScoreSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.lineComplexityScoreSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineComplexityScoreSpinBox.setMaximum(100)
        self.lineComplexityScoreSpinBox.setProperty("value", 10)
        self.lineComplexityScoreSpinBox.setObjectName("lineComplexityScoreSpinBox")
        self.gridLayout_4.addWidget(self.lineComplexityScoreSpinBox, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.minAnnotationsCoverageSpinBox = QtWidgets.QSpinBox(self.groupBox_10)
        self.minAnnotationsCoverageSpinBox.setMaximum(100)
        self.minAnnotationsCoverageSpinBox.setObjectName("minAnnotationsCoverageSpinBox")
        self.gridLayout_6.addWidget(self.minAnnotationsCoverageSpinBox, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(352, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.maxAnnotationsComplexitySpinBox = QtWidgets.QSpinBox(self.groupBox_10)
        self.maxAnnotationsComplexitySpinBox.setMinimum(1)
        self.maxAnnotationsComplexitySpinBox.setMaximum(9)
        self.maxAnnotationsComplexitySpinBox.setObjectName("maxAnnotationsComplexitySpinBox")
        self.gridLayout_6.addWidget(self.maxAnnotationsComplexitySpinBox, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.optionsTabWidget.addTab(self.specificOptionsTab, "")
        self.horizontalLayout_2.addWidget(self.optionsTabWidget)
        self.line = QtWidgets.QFrame(self.configureTab)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.configureTab)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.loadDefaultButton = QtWidgets.QPushButton(self.configureTab)
        self.loadDefaultButton.setObjectName("loadDefaultButton")
        self.verticalLayout.addWidget(self.loadDefaultButton)
        self.storeDefaultButton = QtWidgets.QPushButton(self.configureTab)
        self.storeDefaultButton.setObjectName("storeDefaultButton")
        self.verticalLayout.addWidget(self.storeDefaultButton)
        self.resetDefaultButton = QtWidgets.QPushButton(self.configureTab)
        self.resetDefaultButton.setObjectName("resetDefaultButton")
        self.verticalLayout.addWidget(self.resetDefaultButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.mainWidget.addTab(self.configureTab, "")
        self.runTab = QtWidgets.QWidget()
        self.runTab.setObjectName("runTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.runTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.resultList = QtWidgets.QTreeWidget(self.runTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.resultList.sizePolicy().hasHeightForWidth())
        self.resultList.setSizePolicy(sizePolicy)
        self.resultList.setAlternatingRowColors(True)
        self.resultList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.resultList.setObjectName("resultList")
        self.verticalLayout_7.addWidget(self.resultList)
        self.checkProgressLabel = E5SqueezeLabelPath(self.runTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkProgressLabel.sizePolicy().hasHeightForWidth())
        self.checkProgressLabel.setSizePolicy(sizePolicy)
        self.checkProgressLabel.setText("")
        self.checkProgressLabel.setObjectName("checkProgressLabel")
        self.verticalLayout_7.addWidget(self.checkProgressLabel)
        self.checkProgress = QtWidgets.QProgressBar(self.runTab)
        self.checkProgress.setProperty("value", 0)
        self.checkProgress.setOrientation(QtCore.Qt.Horizontal)
        self.checkProgress.setObjectName("checkProgress")
        self.verticalLayout_7.addWidget(self.checkProgress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.runTab)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.restartButton = QtWidgets.QPushButton(self.runTab)
        self.restartButton.setObjectName("restartButton")
        self.verticalLayout_8.addWidget(self.restartButton)
        self.fixButton = QtWidgets.QPushButton(self.runTab)
        self.fixButton.setObjectName("fixButton")
        self.verticalLayout_8.addWidget(self.fixButton)
        spacerItem10 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.mainWidget.addTab(self.runTab, "")
        self.verticalLayout_9.addWidget(self.mainWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(CodeStyleCheckerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_9.addWidget(self.buttonBox)

        self.retranslateUi(CodeStyleCheckerDialog)
        self.mainWidget.setCurrentIndex(0)
        self.optionsTabWidget.setCurrentIndex(0)
        self.repeatCheckBox.toggled['bool'].connect(self.fixIssuesCheckBox.setEnabled)
        self.repeatCheckBox.toggled['bool'].connect(self.ignoredCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CodeStyleCheckerDialog)
        CodeStyleCheckerDialog.setTabOrder(self.mainWidget, self.optionsTabWidget)
        CodeStyleCheckerDialog.setTabOrder(self.optionsTabWidget, self.excludeFilesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeFilesEdit, self.excludeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesEdit, self.excludeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesSelectButton, self.includeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesEdit, self.includeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesSelectButton, self.fixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesEdit, self.fixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesSelectButton, self.noFixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesEdit, self.noFixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesSelectButton, self.repeatCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.repeatCheckBox, self.fixIssuesCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesCheckBox, self.ignoredCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.ignoredCheckBox, self.scrollArea)
        CodeStyleCheckerDialog.setTabOrder(self.scrollArea, self.lineLengthSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineLengthSpinBox, self.docLineLengthSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.docLineLengthSpinBox, self.blankBeforeTopLevelSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.blankBeforeTopLevelSpinBox, self.blankBeforeMethodSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.blankBeforeMethodSpinBox, self.hangClosingCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.hangClosingCheckBox, self.docTypeComboBox)
        CodeStyleCheckerDialog.setTabOrder(self.docTypeComboBox, self.encodingsEdit)
        CodeStyleCheckerDialog.setTabOrder(self.encodingsEdit, self.copyrightFileSizeSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.copyrightFileSizeSpinBox, self.copyrightAuthorEdit)
        CodeStyleCheckerDialog.setTabOrder(self.copyrightAuthorEdit, self.futuresList)
        CodeStyleCheckerDialog.setTabOrder(self.futuresList, self.builtinsAssignmentList)
        CodeStyleCheckerDialog.setTabOrder(self.builtinsAssignmentList, self.addBuiltinButton)
        CodeStyleCheckerDialog.setTabOrder(self.addBuiltinButton, self.deleteBuiltinButton)
        CodeStyleCheckerDialog.setTabOrder(self.deleteBuiltinButton, self.aggressiveCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.aggressiveCheckBox, self.complexitySpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.complexitySpinBox, self.lineComplexitySpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineComplexitySpinBox, self.lineComplexityScoreSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineComplexityScoreSpinBox, self.minAnnotationsCoverageSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.minAnnotationsCoverageSpinBox, self.maxAnnotationsComplexitySpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.maxAnnotationsComplexitySpinBox, self.loadDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.loadDefaultButton, self.storeDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.storeDefaultButton, self.resetDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.resetDefaultButton, self.startButton)
        CodeStyleCheckerDialog.setTabOrder(self.startButton, self.resultList)
        CodeStyleCheckerDialog.setTabOrder(self.resultList, self.restartButton)
        CodeStyleCheckerDialog.setTabOrder(self.restartButton, self.fixButton)

    def retranslateUi(self, CodeStyleCheckerDialog):
        _translate = QtCore.QCoreApplication.translate
        CodeStyleCheckerDialog.setWindowTitle(_translate("CodeStyleCheckerDialog", "Code Style Check Result"))
        CodeStyleCheckerDialog.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Code Style Check Results</b>\n"
"<p>This dialog shows the results of the code style check. Double clicking an\n"
"entry will open an editor window and position the cursor at the respective line and position.</p>"))
        self.label_2.setText(_translate("CodeStyleCheckerDialog", "Exclude Files:"))
        self.excludeFilesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter filename patterns of files to be excluded separated by a comma"))
        self.label.setText(_translate("CodeStyleCheckerDialog", "Exclude Messages:"))
        self.excludeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be excluded separated by a comma"))
        self.excludeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_3.setText(_translate("CodeStyleCheckerDialog", "Included Messages:"))
        self.includeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be included separated by a comma"))
        self.includeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_4.setText(_translate("CodeStyleCheckerDialog", "Fix Issues:"))
        self.fixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues to be fixed automatically (leave empty to fix all)"))
        self.fixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_6.setText(_translate("CodeStyleCheckerDialog", "Don\'t Fix Issues:"))
        self.noFixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues not to be fixed automatically"))
        self.noFixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.repeatCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to repeat each message type"))
        self.repeatCheckBox.setText(_translate("CodeStyleCheckerDialog", "Repeat messages"))
        self.fixIssuesCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to fix some issues"))
        self.fixIssuesCheckBox.setText(_translate("CodeStyleCheckerDialog", "Fix issues automatically"))
        self.ignoredCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to show ignored issues"))
        self.ignoredCheckBox.setText(_translate("CodeStyleCheckerDialog", "Show ignored"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.globalOptionsTab), _translate("CodeStyleCheckerDialog", "Global Options"))
        self.groupBox.setTitle(_translate("CodeStyleCheckerDialog", "Source Style"))
        self.label_5.setText(_translate("CodeStyleCheckerDialog", "Max. Line Length:"))
        self.lineLengthSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed line length (PEP-8: 79 characters)"))
        self.label_17.setText(_translate("CodeStyleCheckerDialog", "Max. Documentation Line Length:"))
        self.docLineLengthSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed line length (PEP-8: 79 characters)"))
        self.groupBox_8.setTitle(_translate("CodeStyleCheckerDialog", "Blank Lines Before"))
        self.label_15.setText(_translate("CodeStyleCheckerDialog", "Top Level Classes and Functions:"))
        self.blankBeforeTopLevelSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the number of blank lines before top level classes and functions"))
        self.label_16.setText(_translate("CodeStyleCheckerDialog", "Methods and Nested Classes and Functions:"))
        self.blankBeforeMethodSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the number of blank lines before methods and nested classes or functions"))
        self.hangClosingCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to allow hanging closing brackets"))
        self.hangClosingCheckBox.setText(_translate("CodeStyleCheckerDialog", "Allow hanging closing brackets"))
        self.groupBox_2.setTitle(_translate("CodeStyleCheckerDialog", "Documentation Style"))
        self.label_7.setText(_translate("CodeStyleCheckerDialog", "Docstring Type:"))
        self.docTypeComboBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select the rule set for docstrings"))
        self.groupBox_4.setTitle(_translate("CodeStyleCheckerDialog", "Coding Line"))
        self.label_9.setText(_translate("CodeStyleCheckerDialog", "Valid Encodings:"))
        self.encodingsEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter valid encodings separated by a comma (leave empty to use defaults)"))
        self.groupBox_5.setTitle(_translate("CodeStyleCheckerDialog", "Copyright"))
        self.label_10.setText(_translate("CodeStyleCheckerDialog", "Min. File Size:"))
        self.copyrightFileSizeSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the minimum size a file must have to be checked (0 for all files)"))
        self.label_11.setText(_translate("CodeStyleCheckerDialog", "Author:"))
        self.copyrightAuthorEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter a copyright author name to check for (leave empty to omit this check)"))
        self.groupBox_6.setTitle(_translate("CodeStyleCheckerDialog", "Future Imports"))
        self.label_12.setText(_translate("CodeStyleCheckerDialog", "Expected Imports:"))
        self.futuresList.setSortingEnabled(True)
        self.groupBox_7.setTitle(_translate("CodeStyleCheckerDialog", "Ignore Built-ins Assignment"))
        self.builtinsAssignmentList.setSortingEnabled(True)
        self.builtinsAssignmentList.headerItem().setText(0, _translate("CodeStyleCheckerDialog", "Left"))
        self.builtinsAssignmentList.headerItem().setText(1, _translate("CodeStyleCheckerDialog", "Right"))
        self.addBuiltinButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to add a built-in assignment to be ignored"))
        self.deleteBuiltinButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to delete the selected entries"))
        self.groupBox_9.setTitle(_translate("CodeStyleCheckerDialog", "Commented Code"))
        self.aggressiveCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to search for commented code more aggressively. This may increase the number of false positives."))
        self.aggressiveCheckBox.setText(_translate("CodeStyleCheckerDialog", "Search aggressively"))
        self.groupBox_3.setTitle(_translate("CodeStyleCheckerDialog", "Code Complexity"))
        self.label_8.setText(_translate("CodeStyleCheckerDialog", "Max. McCabe Complexity:"))
        self.complexitySpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed code complexity (McCabe: 10)"))
        self.label_13.setText(_translate("CodeStyleCheckerDialog", "Max. Line Complexity:"))
        self.lineComplexitySpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum complexity (number of nodes) for a line of code"))
        self.label_14.setText(_translate("CodeStyleCheckerDialog", "Max. Line Complexity Score:"))
        self.lineComplexityScoreSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed median for line complexity"))
        self.groupBox_10.setTitle(_translate("CodeStyleCheckerDialog", "Type Annotations"))
        self.label_18.setText(_translate("CodeStyleCheckerDialog", "Min. Coverage:"))
        self.minAnnotationsCoverageSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the minimum percentage of type annotations"))
        self.minAnnotationsCoverageSpinBox.setSpecialValueText(_translate("CodeStyleCheckerDialog", "off"))
        self.minAnnotationsCoverageSpinBox.setSuffix(_translate("CodeStyleCheckerDialog", "%"))
        self.label_19.setText(_translate("CodeStyleCheckerDialog", "Max. Complexity:"))
        self.maxAnnotationsComplexitySpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum type annotation complexity"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.specificOptionsTab), _translate("CodeStyleCheckerDialog", "Specific Options"))
        self.startButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to start the code style check run"))
        self.startButton.setText(_translate("CodeStyleCheckerDialog", "&Start"))
        self.loadDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to load the default values"))
        self.loadDefaultButton.setText(_translate("CodeStyleCheckerDialog", "&Load Defaults"))
        self.storeDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to store the current values as defaults"))
        self.storeDefaultButton.setText(_translate("CodeStyleCheckerDialog", "St&ore Defaults"))
        self.resetDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to reset the default values"))
        self.resetDefaultButton.setText(_translate("CodeStyleCheckerDialog", "&Reset Defaults"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.configureTab), _translate("CodeStyleCheckerDialog", "Configure"))
        self.resultList.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Result List</b>\n"
"<p>This list shows the results of the code style check. Double clicking\n"
"an entry will open this entry in an editor window and position the cursor at\n"
"the respective line and position.</p>"))
        self.resultList.setSortingEnabled(True)
        self.resultList.headerItem().setText(0, _translate("CodeStyleCheckerDialog", "File/Line"))
        self.resultList.headerItem().setText(1, _translate("CodeStyleCheckerDialog", "Code"))
        self.resultList.headerItem().setText(2, _translate("CodeStyleCheckerDialog", "Message"))
        self.checkProgress.setToolTip(_translate("CodeStyleCheckerDialog", "Shows the progress of the code style check"))
        self.checkProgress.setFormat(_translate("CodeStyleCheckerDialog", "%v/%m Files"))
        self.restartButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to restart the code style check run"))
        self.restartButton.setText(_translate("CodeStyleCheckerDialog", "Restart"))
        self.fixButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to fix the selected issues"))
        self.fixButton.setText(_translate("CodeStyleCheckerDialog", "&Fix Selected"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.runTab), _translate("CodeStyleCheckerDialog", "Run"))
from E5Gui.E5LineEdit import E5ClearableLineEdit
from E5Gui.E5SqueezeLabels import E5SqueezeLabelPath
