
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-31T21:41:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "76797d98a656c19a6e2e780468071c2ad74c8b9c",
 "version": "0.0.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
