
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-03T15:15:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "39b26796d17d82ea20aac65b91041373be344f38",
 "version": "3.1.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
