# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/planning/proto/planning_diagnostic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FireSpark.protos.src.planning.proto import latency_pb2 as src_dot_planning_dot_proto_dot_latency__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/planning/proto/planning_diagnostic.proto',
  package='avsoftware.planning',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,src/planning/proto/planning_diagnostic.proto\x12\x13\x61vsoftware.planning\x1a src/planning/proto/latency.proto\"\xf5\x01\n\x17PlanningDiagnosticProto\x12\x17\n\x0fplan_duration_s\x18\x01 \x01(\x01\x12\x18\n\x10solve_duration_s\x18\x02 \x01(\x01\x12\x1e\n\x16solver_total_iteration\x18\x03 \x01(\x04\x12\x1b\n\x13relative_cost_error\x18\x04 \x01(\x01\x12\x1f\n\x17\x63ost_gradient_magnitude\x18\x05 \x01(\x01\x12\x15\n\rlearning_rate\x18\x06 \x01(\x01\x12\x32\n\x07latency\x18\x07 \x01(\x0b\x32!.avsoftware.planning.LatencyProtob\x06proto3')
  ,
  dependencies=[src_dot_planning_dot_proto_dot_latency__pb2.DESCRIPTOR,])




_PLANNINGDIAGNOSTICPROTO = _descriptor.Descriptor(
  name='PlanningDiagnosticProto',
  full_name='avsoftware.planning.PlanningDiagnosticProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plan_duration_s', full_name='avsoftware.planning.PlanningDiagnosticProto.plan_duration_s', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solve_duration_s', full_name='avsoftware.planning.PlanningDiagnosticProto.solve_duration_s', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solver_total_iteration', full_name='avsoftware.planning.PlanningDiagnosticProto.solver_total_iteration', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relative_cost_error', full_name='avsoftware.planning.PlanningDiagnosticProto.relative_cost_error', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost_gradient_magnitude', full_name='avsoftware.planning.PlanningDiagnosticProto.cost_gradient_magnitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='avsoftware.planning.PlanningDiagnosticProto.learning_rate', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='avsoftware.planning.PlanningDiagnosticProto.latency', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=349,
)

_PLANNINGDIAGNOSTICPROTO.fields_by_name['latency'].message_type = src_dot_planning_dot_proto_dot_latency__pb2._LATENCYPROTO
DESCRIPTOR.message_types_by_name['PlanningDiagnosticProto'] = _PLANNINGDIAGNOSTICPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlanningDiagnosticProto = _reflection.GeneratedProtocolMessageType('PlanningDiagnosticProto', (_message.Message,), dict(
  DESCRIPTOR = _PLANNINGDIAGNOSTICPROTO,
  __module__ = 'src.planning.proto.planning_diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.planning.PlanningDiagnosticProto)
  ))
_sym_db.RegisterMessage(PlanningDiagnosticProto)


# @@protoc_insertion_point(module_scope)
