# coding: utf-8

"""
    STACKL

    stackl  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import stackl_client
from stackl_client.models.connection_credentials import ConnectionCredentials  # noqa: E501
from stackl_client.rest import ApiException

class TestConnectionCredentials(unittest.TestCase):
    """ConnectionCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConnectionCredentials
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = stackl_client.models.connection_credentials.ConnectionCredentials()  # noqa: E501
        if include_optional :
            return ConnectionCredentials(
                username = '0', 
                password = '0'
            )
        else :
            return ConnectionCredentials(
        )

    def testConnectionCredentials(self):
        """Test ConnectionCredentials"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
