# Generated by Django 3.0.6 on 2020-06-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corgy_mdm', '0002_employmentquality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentQuality',
            new_name='EmploymentQualityModel',
        ),
    ]
