[tool.poetry]
name = "ATgfe"
version = "0.2.60"
description = "Automated Transparent Genetic Feature Engineering or ATgfe"
license = "MIT"
readme = "README.md"
authors = ["ahmed-mohamed-sn <hanoush87@gmail.com>"]
homepage = "https://github.com/ahmed-mohamed-sn/ATgfe"
repository = "https://github.com/ahmed-mohamed-sn/ATgfe"
keywords = ["Python", "Machine Learning", "Feature Engineering", "Genetic Algorithms", "Explainable"]
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Legal Industry",
    "Intended Audience :: Customer Service",
    "Intended Audience :: Other Audience",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.6"
deap = "^1.3"
pandas = "^0.25.2"
scipy = "^1.3"
numpy = "^1.17"
sympy = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
yellowbrick = "^1.0"
scikit_learn = "^0.21.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
