# Generated by Django 2.2.12 on 2020-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid19', '0008_remove_city_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryShortCode',
            new_name='countryCode',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='countryShortCode',
            new_name='countryCode',
        ),
        migrations.RemoveField(
            model_name='city',
            name='countryShortCode',
        ),
        migrations.RemoveField(
            model_name='province',
            name='countryShortCode',
        ),
        migrations.AddField(
            model_name='city',
            name='countryCode',
            field=models.CharField(default='CN', max_length=20, verbose_name='countryCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='countryCode',
            field=models.CharField(default='CN', max_length=20, verbose_name='countryCode'),
            preserve_default=False,
        ),
    ]
