browse_url:
  description: Open a URL in the default browser on the host machine of Open Peer Power.
  fields:
    url:
      description: The URL to open.
      example: "https://www.open-peer-power.io"
