XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXX
    XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXXXXXXXX
    XXXXX
        BBB BBBBBB BB BBBBBBB
            XXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                        BB BBBBBBBBBBB  BB BBBBBBBBBBBBBBB
                       XXXXXXX
                        BBBBB
                X
                BB BBBBBBBBBBB
                    XXXX XXXXXXX
                BBBBB
                XXXXXXX
            XXXXXXXX
        BBBBBB
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

