[tool.poetry]
name = "tsdoc"
version = "0.1.1"
description = "TSDoc is an embedded comment language for TechSmart code files."
license = "CC-BY-NC-ND-4.0"
authors = ["Ryan Sobol <ryan.sobol@techsmart.codes>"]

[tool.poetry.dependencies]
python = "^3.8"
attrs = "^19.3.0"
textx_ls_core = "^0.1.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.770"
pytest = "^5.2"

[tool.poetry.plugins.textx_languages]
"tsdoc.python" = "tsdoc.python:register"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
