[tool.poetry]
name = "ghupdate"
version = "0.1.1"
description = ""
authors = ["Dimitrios Strantsalis <dstrants@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
cement = "^3.0.4"
jinja2 = "^2.11.2"
pyyaml = "^5.3.1"
colorlog = "^4.1.0"
rich = "^1.2.3"
pygithub = "^1.51"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
