[tool.poetry]
name = "python-golos"
version = "1.1.0"
description = "Python library for Golos blockchain"
authors = ["Vladimir Kamarzin <vvk@vvk.pp.ru>"]
license = "MIT"
repository = "https://github.com/bitfag/golos-python"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 5 - Production/Stable"
]
packages = [
    { include = "golosbase" },
    { include = "golos" },
]

[tool.poetry.dependencies]
python = "^3.6.1"
funcy = "^1.14"
langdetect = "^1.0.8"
scrypt = "^0.8.13"
toolz = "^0.10.0"
websocket-client = "^0.56"
ecdsa = "^0.13"
voluptuous = "^0.11.7"
certifi = "^2020.4.5"
prettytable = "^0.7.2"
pylibscrypt = "^1.8.0"
ujson = "^2.0.3"
urllib3 = "^1.25.9"
w3lib = "^1.21.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.2.0"
pytest = "^5.4.1"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \venv
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
