[tool.towncrier]
    package="nucypher"
    package_dir="nucypher"
    filename = "docs/source/release_notes/releases.rst"
    directory = "newsfragments"
    underlines = ["-", "~", "^", "*"]
    issue_format = "`#{issue} <https://github.com/nucypher/nucypher/issues/{issue}>`__"
    title_format = "v{version} ({project_date})"
