#=========================================================================
# Mentor Calibre Fill
#=========================================================================
# Author : Christopher Torng
# Date   : April 6, 2020
#

name: mentor-calibre-fill

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.gds
  - adk

outputs:
  - design.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Generate the dummy fill GDS
  - envsubst < fill.runset.template > fill.runset
  - calibre -gui -drc -batch -runset fill.runset
  # Merge the design GDS with the dummy fill GDS
  - calibredrv -a layout filemerge \
               -infile [list -name inputs/design.gds -suffix _design] \
               -infile [list -name {fill_gds} -suffix _fill] \
               -createtop {design_name}_filled \
               -out design_filled.gds
  - mkdir -p outputs && cd outputs
  - ln -sf ../design_filled.gds design.gds


#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  # Use the rule deck "inputs/adk/${fill_rule_deck}"
  fill_rule_deck: calibre-fill.rule
  fill_gds: FEOL.gds

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m outputs/design.gds \
               -l inputs/adk/calibre.layerprops

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design.gds' )

postconditions:

  - assert File( 'outputs/design.gds' )


