[tool.poetry]
name = "urmarketscraper"
version = "1.1.0"
description = "Collects market offers for Urban Rivals."
authors = ["Brent Spector <brent.spector@yahoo.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/brentspector/urmarketscraper"

[tool.poetry.dependencies]
python = "^3.8"
bs4 = "^0.0.1"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
sphinx = "^2.4.3"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
