[tool.poetry]
name = "pecho"
version = "0.5.2"
description = "Easy way to write things like status bars"
authors = ["Nihaal Sangha <me@niha.al>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nihaals/pecho"

[tool.poetry.dependencies]
python = "^3.6"
colorama = { version = "^0.4.3", optional = true }

[tool.poetry.extras]
windows = ["colorama"]

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
include = '\.pyi?$'

[tool.isort]
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
