[tool.poetry]
name = "arcane-clients"
version = "0.1.1"
description = "Utility functions to interact with our clients_service"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
arcane-requests = "0.1.1"
requests = "^2.23.0"
backoff = "^1.10.0"
# arcane-core = "1.0.0" (optional)

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
