[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dnnv"
author = "David Shriver"
author-email = "dls2fc@virginia.edu"
home-page = "https://github.com/dlshriver/DNNV"
description-file = "README.md"
requires = [
    "numpy==1.18",
    "onnx==1.6",
    "psutil==5.6",
    "scipy==1.3",
    "tensorflow==1.15",
    "keras==2.3",
]
requires-python = "==3.7"

[tool.flit.metadata.requires-extra]
test = ["toml==0.10", "coverage==5.0", "torch==1.5", "torchvision==0.6"]
doc = ["sphinx"]
dev = ["black", "mypy"]

[tool.flit.scripts]
dnnv = "dnnv.__main__:_main"

[tool.coverage.run]
branch = true
command_line = "-m unittest discover -v -p *_tests.py"
concurrency = ["multiprocessing", "thread"]
parallel = true
source = ["dnnv"]
