# Base Configuration file for artellapipe-libs-kitsu for Solstice

# Defines the Kitsu Project ID
project_id: "a9efcb03-a1ca-4827-b95d-83f937b283f9"

# Defines the URL of the Kitsu project
project_url: "https://solstice-short-film.cg-wire.com/productions/a9efcb03-a1ca-4827-b95d-83f937b283f9/assets"

# Defines Gazu API url of the Kitsu project
gazu_api: "https://solstice-short-film.cg-wire.com/api"

# Defines custom attribute to use to identify Kitsu assets
custom_id_attribute: "id"

# Defines custom attribute to use to identify Kitsu published assets
custom_is_published_attribute: "published"