# Generated by Django 3.0.6 on 2020-06-01 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corgy_mdm', '0006_auto_20200601_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRelationshipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime_number', models.UUIDField(default=uuid.uuid4, editable=False, help_text='prime number is unique code for any master data', verbose_name='prime number')),
                ('code', models.CharField(blank=True, default='', help_text='Law-abiding master data code', max_length=100, null=True, verbose_name='code')),
                ('name', models.CharField(default=None, help_text='Humanized name of master data', max_length=1000, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, help_text='Long description', max_length=10000, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Legal relationship',
                'verbose_name_plural': 'Legal relationships',
            },
        ),
    ]
