[tool.poetry]
name = "cmd-help"
version = "0.0.0"
description = ""
authors = ["guaifish <guaifish@foxmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/guaifish/cmd-help"
homepage = "https://github.com/guaifish/cmd-help"
packages = [
    { include = "src/"},
]
keywords = []

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"