# Generated by Django 2.2.12 on 2020-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid19', '0010_remove_province_provinceshortname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
