# Generated by Django 2.2.12 on 2020-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid19', '0011_delete_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='provinceName',
            field=models.CharField(default=None, max_length=50, verbose_name='provinceName'),
            preserve_default=False,
        ),
    ]
