CMD_APP_CREATE = 'create a new app'
OPT_APP_CREATE_DESCRIPTION = 'sets a description for your app'
OPT_APP_CREATE_POOL = 'defines which pool your app will be deployed'
OPT_APP_CREATE_TEAM = 'describes which team is responsible for the created app'
OPT_APP_CREATE_ROUTER = 'defines the router to be used'
OPT_APP_CREATE_PLAN = ' parameter defines the plan to be used'
OPT_APP_CREATE_TAG = 'sets a tag to your app. You can set multiple parameters'
OPT_APP_CREATE_DEPENDENCY = 'sets inspect file to create app dependencies. You can set multiple parameters'
OPT_APP_CREATE_ROUTER_opt = 'KEY=VALUE \n\n' \
                            'Allow passing custom parameters to the router used by the application\'s plan. ' \
                            'You can set multiple parameters'
CMD_APP_DEPLOY = 'deploy the source to shipa server'
OPT_APP_DEPLOY_APP = 'specify which app you want to deploy'
OPT_APP_DEPLOY_STEP_INTERVAL = 'single step duration. supported min: m, hour:h, second:s. ex. 1m, 60s, 1h'
OPT_APP_DEPLOY_STEPS = 'steps for canary deployment'
OPT_APP_DEPLOY_DIRECTORY = 'directory to deploy (default .)'
OPT_APP_DEPLOY_STEP_WEIGHT = 'deploy step weight'
CMD_APP_REMOVE = 'remove a shipa app'
OPT_APP_REMOVE_APP = 'specify which app you want to remove'
CMD_APP_MOVE = 'move a shipa app to another pool'
OPT_APP_MOVE_APP = 'specify which app you want to move'
OPT_APP_MOVE_POOL = 'specify which pool you want to move'
CMD_POOL_ADD = 'adds a new app'
OPT_POOL_PUBLIC = 'make pool public (all teams can use it)'
OPT_POOL_DEFAULT = 'make pool default (when none is specified during app-create this pool will be used)'
OPT_POOL_PROVISIONER = 'provisioner associated to the pool (empty for default docker provisioner)'
OPT_POOL_PLAN = 'the plan when adding app to this pool'
OPT_POOL_QUOTA_LIMIT = 'quota limit for app when adding it to this pool'
OPT_POOL_NAMESPACE = 'kubernetes namespace for this pool'
OPT_POOL_DRIVER = 'node drivers accepted in pool'
CMD_POOL_REMOVE = 'remove an existing pool.'
CMD_POOL_UPDATE = 'updates attributes for a pool.'
