[tool.poetry]
name = "chalice-cdk"
version = "0.1.0"
description = ""
authors = ["Stephan Fitzpatrick <knowsuchagency@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
"aws_cdk.core" = "^1.42.1"
"aws_cdk.aws_s3_assets" = "^1.42.1"
chalice = "^1.14.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
invoke = "^1.4.1"
toml = "^0.10.1"
pre-commit = "^2.4.0"
qypi = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
