[tool.poetry]
name = "TCCR"
version = "0.1.0"
description = "A simple library for changing the color of text in the console, in different ways. Even a child will understand :)))"
authors = ["Nikita Finogenov"]

[tool.poetry.dependencies]
python = "2.7.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
