[tool.poetry]
name = "YoungOnes-Auth"
version = "0.0.7"
description = "Python Auth Adapter for YoungOnes Authentication"
authors = ["Alex Pedersen <alex@youngones.works>"]
packages = [
    { include = "youngones" }
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
pyyaml = "^5.3"


[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
bandit = "^1.6.2"
black = "^19.10b0"
pylint = "^2.4.4"
poetry = "^1.0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
