[tool.poetry]
name = "defaultenv"
version = "0.0.13"
description = "Environment and .env file reader"
authors = ["Grigory Bakunov <thebobuk@ya.ru>"]
repository = "http://github.com/bobuk/defaultenv"
readme = "README.md"
classifiers=[
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

packages = [
    { include = "./defaultenv.py" }
]

[tool.poetry.dependencies]
python = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"