[tool.poetry]
name = "sphinxawesome-sampdirective"
version = "1.0.0"
description = "A Sphinx directive for literal blocks with emphasis"
license = "MIT"
readme = "README.md"
authors = ["Kai Welke <kai687@pm.me>"]
repository = "https://github.com/kai687/sphinxawesome-sampdirective"
classifiers = [
  'Programming Language :: Python',
  'Framework :: Sphinx',
  'Framework :: Sphinx :: Extension',
  'Topic :: Documentation',
  'Topic :: Documentation :: Sphinx',
  'Topic :: Software Development :: Documentation'
]
packages = [
  { include = "sphinxawesome" }
]

[tool.poetry.dependencies]
python = "^3.6"
sphinx = ">=2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.9"
pre-commit = "^2.1.1"

[tool.black]
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
  \.git
| \.github
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
