site_name: OpenVisionCapsules Documentation
theme: readthedocs
nav:
  - Introduction: "index.md"
  - File Structure: "file_structure.md"
  - Runtime Environment: "runtime_environment.md"
  - The Capsule Class: "capsule_class.md"
  - Backends: "backends.md"
  - Inputs and Outputs: "inputs_and_outputs.md"
  - Options: "options.md"
  - Creating a Capsule: "creating_a_capsule.md"
  - Stream State: "stream_state.md"
