[tool.poetry]
name = "desdeo-tools"
version = "0.2.6"
description = "Generic tools and design language used in the DESDEO framework"
authors = ["Bhupinder Saini", "Giovanni Misitano"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"
pandas = "^0.25.3"
scipy = "^1.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pylint = "^2.4"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
jupyter = "^1.0"
matplotlib = "^3.2.1"
pytest = "^5.4.1"
rope = "^0.16.0"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
