[tool.poetry]
name = "configdir"
version = "0.1.0"
description = ""
authors = ["Michael Thornton <six8@devdetails.com>"]

[tool.poetry.dependencies]
python = "^2.7 || ^3.6 ||  ^3.7"

[tool.poetry.dev-dependencies]
pytest = [
    {version = "^4", python = "~2.7"},
    {version = "^5", python = ">=3.6"}
]
pyyaml = "^5.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
