language: python
sudo: false
cache: pip


python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - PYTHONHASHSEED=random
    TEST_REQUIRE="gevent greenlet geventhttpclient fastimport"
    TYPING_REQUIRE=mypy
    PURE=false

matrix:
  include:
    - python: 3.7
      env: TEST_REQUIRE=fastimport
      dist: xenial
      sudo: true
    - python: 3.8
      env: TEST_REQUIRE=fastimport
      dist: xenial
      sudo: true
    - python: 3.8
      env: TEST_REQUIRE=fastimport
      dist: xenial
      sudo: true
    - python: 3.6
      env: PURE=true
    - python: pypy3
      env: MYPY_REQUIRE=

install:
  - travis_retry pip install -U pip coverage codecov flake8 $TYPING_REQUIRE $TEST_REQUIRE

script:
  - if [ $PURE = false ]; then python setup.py build_ext -i; fi
  - python -m coverage run -p -m unittest dulwich.tests.test_suite

  # Style
  - make style
  - if [ $MYPY_REQUIRE != "" ]; then make typing; fi

  - if [ $PURE = true ]; then SETUP_ARGS=--pure; fi
  - python setup.py $SETUP_ARGS bdist_wheel

after_success:
  - python -m coverage combine
  - codecov

deploy:
  provider: pypi
  user: dulwich-bot
  password:
    secure: Q8DDDojBugQWzXvmmEQiU90UkVPk+OYoFZwv1H9LYpQ4u5CfwQNWpf8qXYhlGMdr/gzWaSWsqLvgWLpzfkvqS4Vyk2bO9mr+dSskfD8uwc82LiiL9CNd/NY03CjH9RaFgVMD/+exMjY/yCtlyH1jL4kjgOyNnC+x4B37CliZHcE=
  skip_cleanup: true
  skip_existing: true
  file_glob: true
  file:
    - dist/dulwich*.whl
    - dist/dulwich*.tar.gz
  on:
    tags: true
    repo: dulwich/dulwich
