[tool.poetry]
name = "redis-tracker"
version = "1.1"
description = "simple redis key tracker for stdout and prometheus"
readme="README.md"
authors = ["bernardas ališauskas <bernardas.alisauskas@pm.me>"]
license = "GPL-3.0-or-later"
classifiers = [
    'Environment :: Console',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Operating System :: POSIX',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
packages = [{include="tracker.py"}]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
redis-tracker = 'tracker:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
