# See https://github.com/LiliC/travis-minikube for Travis+Minikube.
# This affects the env & before_script sections, and some functional tests.
language: python
sudo: required
dist: xenial
services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_IN_STYLE=true
    - MINIKUBE_HOME=$HOME
    - MINIKUBE_VERSION=latest
  matrix:
    - KUBERNETES_VERSION=latest CLIENT=yes  # only one "yes" is enough
    - KUBERNETES_VERSION=latest CLIENT=no
    - KUBERNETES_VERSION=v1.16.0 CLIENT=no
    - KUBERNETES_VERSION=v1.16.0 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.15.0 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.14.0 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.13.0 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.12.0 CLIENT=no CRDAPI=v1beta1
#    - KUBERNETES_VERSION=v1.11.10  # Minikube fails on CRI preflight checks
#    - KUBERNETES_VERSION=v1.10.13  # CRDs require spec.version, which fails on 1.14

# Only one Python version is tested with all supported K8s versions: to check for API compatibility.
# Other Python versions are tested with only one K8s version: if it works for one, it works for all.
# One look-ahead Python dev version is tested for preview, but is optional.
python:
  - "3.8"
matrix:
  include:
    - python: "3.7"
      env: KUBERNETES_VERSION=latest CLIENT=yes
    - python: "3.7"
      env: KUBERNETES_VERSION=latest CLIENT=no
    - python: "3.9-dev"
  allow_failures:
    - python: "3.9-dev"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y conntrack  # see #334

before_script:
  - tools/minikube-for-travis.sh
  - tools/kubernetes-client.sh

script:
  - pytest --cov=kopf --cov-branch
  - coveralls || true
  - codecov --flags unit
  - pytest --only-e2e  # NB: after the coverage uploads!
  - mypy kopf --strict --pretty

deploy:
  provider: pypi
  user: nolar
  password:
    secure: "hvXIiqAAzsB5p++rv12XJM6WtuUHa9YnvoY12HfdZeLcim+/TQpMM0qThF0Y7tLcgAq/CqIOVoawOxDU+yKtzEbDqOd7wVIu8Z9tlnaIXIobV7BmLqeeqHAWNRB95fbkPWVUp0Ff0pdV4lvNwzw9qI4sB4J+x3k5sgiLKGh/JIxJpMxZTpQzsaxPsbIh4nbTebysdKfRsBbtUGx6Z1JK9vlK+a+fTho3hpmbv5Ku6z8JZePx2Ox0hugTCak556lDy4Psa6Hhnf69Rm05wfr7n4zIkU1/0zt1q+ggPs6L+Hc5PbBxWw1zUWn8YvNiSpEqiwuRZ9rgJl396g2ge2eUNwTjnc7qmbxgO8Ue3GuqRzokXzeAlS6MNSFfjzENrL+FjMUiHEWiP8HOpWfd2vVSK7Sp2HLE0NKWIhn38w3VhMz++rOPn8OdL4+K48BUSYod051+CJnjczcCWYyfoK4pvajOtsTgswnJvVG1it2iEdS/j7U1KslKfR3A38ojzwyrFb3F4XQ4D4yZxYIz0E0xl3X0q63vGibvGsFLgnD4okUq6r3k4TvoWn5rbN4039CcQbhVZrAaDzdvrTGiSTXMEMklr0G8rQEq6SQOsclMB6Db4ttnLOj5rk14gs0FvhvR/R4wF1SMAK2IzhgEx1S78xIvralrk+anHIWydhm+P8A="
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true  # prohibit local versions not on the releases
