{% import '_helpers.jinja' as helpers with context %}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: {{ container.name }}
  labels:
    {{ helpers.common_labels() | indent(4) }}
    {{ helpers.container_labels() | indent(4) }}
spec:
  selector:
    matchLabels:
      {{ helpers.common_labels() | indent(6) }}
      {{ helpers.container_labels() | indent(6) }}
  template:
    metadata:
      labels:
        {{ helpers.common_labels() | indent(8) }}
        {{ helpers.container_labels() | indent(8) }}
    spec:
      containers:
        - name: {{ container.name }}
          image: {{ container.config.image }}
          {% if container.config.ports %}
          ports:
          {% for port in container.config.ports %}
            - containerPort: {{ port }}
          {% endfor %}
          {% endif %}
          {% if container.config.environment %}
          env:
          {% for name, value in container.config.environment.items() %}
            - name: {{ name }}
              value: {{ value | quote }}
          {% endfor %}
          {% endif %}
      automountServiceAccountToken: false
