[tool.poetry]
name = "redisbench-admin"
version = "0.1.6"
description = "Redis benchmark run helper. A wrapper around ftsb_redisearch ( future versions will also support redis-benchmark and memtier_benchmark )."
authors = ["filipecosta90 <filipecosta.90@gmail.com>"]

[tool.poetry.scripts]
redisbench-admin = "redisbench_admin.cli:main"

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0.4"
humanize = "^2.4.0"
requests = "^2.23.0"
py_cpuinfo = "^5.0.0"
redis = "^3.5.3"
boto3 = "^1.13.24"
tqdm = "^4.46.1"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
