# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/carviz/proto/carviz_init_timing_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/carviz/proto/carviz_init_timing_stats.proto',
  package='avsoftware.carviz',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/src/carviz/proto/carviz_init_timing_stats.proto\x12\x11\x61vsoftware.carviz\"H\n\x15PluginInitTimingStats\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x1a\n\x12plugin_init_time_s\x18\x02 \x01(\x01\"\xf3\x02\n\x15\x43\x61rvizInitTimingStats\x12\x19\n\x11total_init_time_s\x18\x01 \x01(\x01\x12\x1f\n\x17load_all_plugins_time_s\x18\x02 \x01(\x01\x12\x1b\n\x13load_configs_time_s\x18\x03 \x01(\x01\x12\x16\n\x0einit_qt_time_s\x18\x04 \x01(\x01\x12\x1d\n\x15init_main_view_time_s\x18\x05 \x01(\x01\x12\x1f\n\x17init_main_window_time_s\x18\x06 \x01(\x01\x12\x1a\n\x12init_viewer_time_s\x18\x07 \x01(\x01\x12\x1f\n\x17init_config_data_time_s\x18\x08 \x01(\x01\x12 \n\x18init_ui_theme_mgr_time_s\x18\t \x01(\x01\x12J\n\x18plugin_init_timing_stats\x18\n \x03(\x0b\x32(.avsoftware.carviz.PluginInitTimingStatsb\x06proto3')
)




_PLUGININITTIMINGSTATS = _descriptor.Descriptor(
  name='PluginInitTimingStats',
  full_name='avsoftware.carviz.PluginInitTimingStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plugin_name', full_name='avsoftware.carviz.PluginInitTimingStats.plugin_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plugin_init_time_s', full_name='avsoftware.carviz.PluginInitTimingStats.plugin_init_time_s', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=142,
)


_CARVIZINITTIMINGSTATS = _descriptor.Descriptor(
  name='CarvizInitTimingStats',
  full_name='avsoftware.carviz.CarvizInitTimingStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_init_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.total_init_time_s', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_all_plugins_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.load_all_plugins_time_s', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_configs_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.load_configs_time_s', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_qt_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_qt_time_s', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_main_view_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_main_view_time_s', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_main_window_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_main_window_time_s', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_viewer_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_viewer_time_s', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_config_data_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_config_data_time_s', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_ui_theme_mgr_time_s', full_name='avsoftware.carviz.CarvizInitTimingStats.init_ui_theme_mgr_time_s', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plugin_init_timing_stats', full_name='avsoftware.carviz.CarvizInitTimingStats.plugin_init_timing_stats', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=516,
)

_CARVIZINITTIMINGSTATS.fields_by_name['plugin_init_timing_stats'].message_type = _PLUGININITTIMINGSTATS
DESCRIPTOR.message_types_by_name['PluginInitTimingStats'] = _PLUGININITTIMINGSTATS
DESCRIPTOR.message_types_by_name['CarvizInitTimingStats'] = _CARVIZINITTIMINGSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PluginInitTimingStats = _reflection.GeneratedProtocolMessageType('PluginInitTimingStats', (_message.Message,), dict(
  DESCRIPTOR = _PLUGININITTIMINGSTATS,
  __module__ = 'src.carviz.proto.carviz_init_timing_stats_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.carviz.PluginInitTimingStats)
  ))
_sym_db.RegisterMessage(PluginInitTimingStats)

CarvizInitTimingStats = _reflection.GeneratedProtocolMessageType('CarvizInitTimingStats', (_message.Message,), dict(
  DESCRIPTOR = _CARVIZINITTIMINGSTATS,
  __module__ = 'src.carviz.proto.carviz_init_timing_stats_pb2'
  # @@protoc_insertion_point(class_scope:avsoftware.carviz.CarvizInitTimingStats)
  ))
_sym_db.RegisterMessage(CarvizInitTimingStats)


# @@protoc_insertion_point(module_scope)
