repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: '.travis.yml'
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: "master" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies: [flake8-import-order, flake8-bugbear]
  - repo: local
    hooks:
      - id: update-travis
        name: Update travis job definition
        description: Ensures that travis job definition are up to date.
        entry: scripts/make_travisconf.py
        files: '.*travis.*'
        stages: [commit]
        language: script
