
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-01T15:01:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3c4e67fd99115d9e0f7c717a1486392881d75f6",
 "version": "1.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
