[tool.poetry]
name = "az-vt"
version = "0.0.1"
description = "az-vt"
authors = ["Stefano Borini"]
packages = [
    { include = "vt", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
