CASETYPES = [
    {
        "name": "ban",
        "default_setting": True,
        "color": 0xF50A0A,
        "image": "<a:BantScrub:705843389047767100>",
        "case_str": "Ban",
        "audit_type": "ban",
    },
    {
        "name": "kick",
        "default_setting": True,
        "color": 0xFFBA01,
        "image": "<:imheadout:626236854047473667>",
        "case_str": "Kick",
        "audit_type": "kick",
    },
    {
        "name": "hackban",
        "default_setting": True,
        "color": 0xFA3CB6,
        "image": "<a:bruhgetgot:697309398221062254>",
        "case_str": "Hackban",
        "audit_type": "ban",
    },
    {
        "name": "tempban",
        "default_setting": True,
        "image": "\N{ALARM CLOCK}\N{HAMMER}",
        "case_str": "Tempban",
        "audit_type": "ban",
    },
    {
        "name": "softban",
        "default_setting": True,
        "color": 0x111111,
        "image": "<a:watching:654688237239009280>",
        "case_str": "Softban",
        "audit_type": "ban",
    },
    {
        "name": "unban",
        "default_setting": True,
        "color": 0x01FF1E,
        "image": "<a:welcomegold1:686173247083249672> <a:welcomegold2:686173247066341403>",
        "case_str": "Unban",
        "audit_type": "unban",
    },
    {
        "name": "voiceban",
        "default_setting": True,
        "image": "<a:rejected:694386391416832000>",
        "case_str": "Voice Ban",
        "audit_type": "member_update",
    },
    {
        "name": "voiceunban",
        "default_setting": True,
        "image": "<a:approved:694386358344482867>",
        "case_str": "Voice Unban",
        "audit_type": "member_update",
    },
    {
        "name": "vmute",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Voice Mute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "cmute",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Channel Mute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "smute",
        "default_setting": True,
        "image": "<a:sprayNOPE:688648007453114376>",
        "case_str": "Server Mute",
        "audit_type": "member_update",
    },
    {
        "name": "vunmute",
        "default_setting": False,
        "image": "<a:owowutsdis:652657081584844813>",
        "case_str": "Voice Unmute",
        "audit_type": "member_update",
    },
    {
        "name": "cunmute",
        "default_setting": False,
        "image": "\N{SPEAKER}",
        "case_str": "Channel Unmute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "sunmute",
        "default_setting": True,
        "image": "<a:owowutsdis:652657081584844813>",
        "case_str": "Server Unmute",
        "audit_type": "member_update",
    },
    {
        "name": "vkick",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Voice Kick",
    },
]
