BBBB BBBBBBBBB BBBBBBBBB

BBBBBBBBBBB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX
                BB BBBBBBBBB
                    
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB

                    XX XXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

                    XX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
        XXXX
        XXXXXFFFFXXXXXX
        XXXX
        XXXX XXXXXXXXXXXXX
            XXXXXXXX X  X XXXXXXX X 
        XXXXXX
    XXXXXX
    BB BBB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
            
        XXXXXX
    BBBBB

BBBBBBBBBBBBBB