[tool.poetry]
name = "zeroed"
version = "0.1.0rc1"
description = "Zeroed is a CLI package for resetting trash and apps to the settings of certain apps on Linux."
readme = "README.rst"
authors = ["William C. Canin <william.costa.canin@gmail.com>"]
license = "MIT license"
keywords=["zeroed", "reset"]
homepage = 'https://github.com/snakypy/zeroed'
repository = 'https://github.com/snakypy/zeroed'
include = ['LICENSE']
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX',
    'Programming Language :: Python :: 3'
]
packages = [
    { include = 'zeroed' }
]

[tool.poetry.scripts]
zeroed = 'zeroed.cli:main'
[tool.poetry.urls]
'Bug Tracker' = 'https://github.com/snakypy/zeroed/issues'

[tool.poetry.dependencies]
python = '^3.8'
click = '^7.1.1'
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
pre-commit = '^2.2.0'
flake8 = '^3.7.9'
black = '^19.10b0'
tox = '^3.14.5'
sphinx = '^2.3.1'
sphinx-rtd-theme = '^0.4.3'
recommonmark = '^0.6.0'
pytest = '^5.3.5'
pytest-runner = '^5.2'
eqversion = "^0.1.3"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \venv
    | build
    | venv
    | dist
    | docs
    | tmp
  )/
)
'''

[build-system]
requires = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'
