[tool.poetry]
name = "epb"
version = "0.2.0"
description = "Energy performance of buildings"
authors = ["Arthur White <arthur@white.li>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/immoveable/epb-py"
classifiers = [
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.2"
pycodestyle = "^2.6.0"
mypy = "^0.770"
pydocstyle = "^5.0.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
