[tool.poetry]
name = "pysanejs"
version = "1.1"
description = "Python client for SaneJS"
authors = ["Raphaël Vinot <raphael@vinot.info>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/CIRCL/PySaneJS"

readme = "README.md"
classifiers=[
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]


[tool.poetry.scripts]
sanejs = "pysanejs:main"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
mypy = "^0.761"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
