site_name: SharePoint Too
site_author: Tim Santor
site_description: Python Boilerplate contains all the boilerplate you need to create a Python package.
copyright: Tim Santor
theme: material
use_directory_urls: false
dev_addr: 127.0.0.1:8989

repo_url: https://bitbucket.org/tsantor/sharepoint-too/
project_slug: Bitbucket


markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

extra_css:
  - css/extra.css
